/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2022-2022. All rights reserved.
 * Description: 校准涉及到的phy寄存器操作接口
 * Date: 2022-10-22
 */

#ifndef __FE_HAL_PHY_REG_IF_HOST_H__
#define __FE_HAL_PHY_REG_IF_HOST_H__

#include "osal_types.h"
#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif
#ifndef _PRE_WLAN_ATE
// 动态功率
osal_void hal_set_dyn_tx_power_cali_dyn_tx_power_cali(osal_u32 dyn_tx_power_cali);
osal_void hal_set_tx_power_accum_delay_power_accum_delay(osal_u32 power_accum_delay);
osal_void hal_set_cali_new_add_reg_cfg_fb_pwr_calc_prd(osal_u32 cfg_fb_pwr_calc_prd);
// TPC ram 读写
osal_void hal_set_tpc_ram_access_reg1_cfg_tpc_ram_access_mode(osal_u32 cfg_tpc_ram_access_mode);
osal_void hal_set_tpc_ram_access_reg1_cfg_indirect_rw_mode(osal_u32 cfg_indirect_rw_mode);
osal_void hal_set_tpc_ram_access_reg1_cfg_tpc_table_access_addr(osal_u32 cfg_tpc_table_access_addr);
#endif
osal_void hal_set_tpc_ram_access_reg2_cfg_tpc_table_wr_data(osal_u32 cfg_tpc_table_wr_data);
#ifndef _PRE_WLAN_ATE
// 二级映射
osal_void hal_set_rf_ppa_code_lut0_cfg_rf_ppa_code_lut0(osal_u32 cfg_rf_ppa_code_lut0);
osal_u32 hal_get_rf_ppa_code_lut0_cfg_rf_ppa_code_lut0(osal_void);
osal_void hal_set_rf_ppa_code_lut0_cfg_rf_ppa_code_lut1(osal_u32 cfg_rf_ppa_code_lut1);
osal_u32 hal_get_rf_ppa_code_lut0_cfg_rf_ppa_code_lut1(osal_void);
osal_void hal_set_rf_ppa_code_lut1_cfg_rf_ppa_code_lut2(osal_u32 cfg_rf_ppa_code_lut2);
osal_u32 hal_get_rf_ppa_code_lut1_cfg_rf_ppa_code_lut2(osal_void);
osal_void hal_set_rf_ppa_code_lut1_cfg_rf_ppa_code_lut3(osal_u32 cfg_rf_ppa_code_lut3);
osal_u32 hal_get_rf_ppa_code_lut1_cfg_rf_ppa_code_lut3(osal_void);
osal_void hal_set_rf_ppa_code_lut2_cfg_rf_ppa_code_lut4(osal_u32 cfg_rf_ppa_code_lut4);
osal_u32 hal_get_rf_ppa_code_lut2_cfg_rf_ppa_code_lut4(osal_void);
osal_void hal_set_rf_ppa_code_lut2_cfg_rf_ppa_code_lut5(osal_u32 cfg_rf_ppa_code_lut5);
osal_u32 hal_get_rf_ppa_code_lut2_cfg_rf_ppa_code_lut5(osal_void);
osal_void hal_set_rf_ppa_code_lut3_cfg_rf_ppa_code_lut6(osal_u32 cfg_rf_ppa_code_lut6);
osal_u32 hal_get_rf_ppa_code_lut3_cfg_rf_ppa_code_lut6(osal_void);
osal_void hal_set_rf_ppa_code_lut3_cfg_rf_ppa_code_lut7(osal_u32 cfg_rf_ppa_code_lut7);
osal_u32 hal_get_rf_ppa_code_lut3_cfg_rf_ppa_code_lut7(osal_void);
osal_void hal_set_rf_ppa_code_lut4_cfg_rf_ppa_code_lut8(osal_u32 cfg_rf_ppa_code_lut8);
osal_u32 hal_get_rf_ppa_code_lut4_cfg_rf_ppa_code_lut8(osal_void);
osal_void hal_set_rf_ppa_code_lut4_cfg_rf_ppa_code_lut9(osal_u32 cfg_rf_ppa_code_lut9);
osal_u32 hal_get_rf_ppa_code_lut4_cfg_rf_ppa_code_lut9(osal_void);
#endif
osal_void hal_set_rf_pa_code_lut0_cfg_rf_pa_code_lut0(osal_u32 cfg_rf_pa_code_lut0);
osal_void hal_set_rf_pa_code_lut0_cfg_rf_pa_code_lut1(osal_u32 cfg_rf_pa_code_lut1);
osal_void hal_set_rf_pa_code_lut1_cfg_rf_pa_code_lut2(osal_u32 cfg_rf_pa_code_lut2);
osal_void hal_set_rf_pa_code_lut1_cfg_rf_pa_code_lut3(osal_u32 cfg_rf_pa_code_lut3);
osal_void hal_set_rf_pa_code_lut2_cfg_rf_pa_code_lut4(osal_u32 cfg_rf_pa_code_lut4);
osal_void hal_set_rf_pa_code_lut2_cfg_rf_pa_code_lut5(osal_u32 cfg_rf_pa_code_lut5);
osal_void hal_set_rf_pa_code_lut3_cfg_rf_pa_code_lut6(osal_u32 cfg_rf_pa_code_lut6);
osal_void hal_set_rf_pa_code_lut3_cfg_rf_pa_code_lut7(osal_u32 cfg_rf_pa_code_lut7);
osal_void hal_set_rf_pa_code_lut4_cfg_rf_pa_code_lut8(osal_u32 cfg_rf_pa_code_lut8);
osal_void hal_set_rf_pa_code_lut4_cfg_rf_pa_code_lut9(osal_u32 cfg_rf_pa_code_lut9);
// dbb sacle shadow
osal_void hal_set_tpc_boundary_threshold1_cfg_tpc_boundary_0(osal_u32 cfg_tpc_boundary_0);
osal_void hal_set_tpc_boundary_threshold1_cfg_tpc_boundary_1(osal_u32 cfg_tpc_boundary_1);
osal_void hal_set_tpc_boundary_threshold1_cfg_tpc_boundary_2(osal_u32 cfg_tpc_boundary_2);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_3(osal_u32 cfg_tpc_boundary_3);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_4(osal_u32 cfg_tpc_boundary_4);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_5(osal_u32 cfg_tpc_boundary_5);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_6(osal_u32 cfg_tpc_boundary_6);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_0(osal_u32 cfg_dbb_scale_shadow_0);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_0(osal_void);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_1(osal_u32 cfg_dbb_scale_shadow_1);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_1(osal_void);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_2(osal_u32 cfg_dbb_scale_shadow_2);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_2(osal_void);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_3(osal_u32 cfg_dbb_scale_shadow_3);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_3(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_4(osal_u32 cfg_dbb_scale_shadow_4);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_4(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_5(osal_u32 cfg_dbb_scale_shadow_5);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_5(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_6(osal_u32 cfg_dbb_scale_shadow_6);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_6(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_7(osal_u32 cfg_dbb_scale_shadow_7);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_7(osal_void);
osal_u32 hal_get_he_tx_foc_power_boost_win_ctrl_cfg_tx_power_boost_bypass(osal_void);
osal_void hal_set_phy_bw_mode_cfg_phy_bw_mode(osal_u32 cfg_phy_bw_mode);
#ifdef _PRE_WLAN_FEATURE_DAQ
void hal_set_sample_cfg_2_cfg_debug_sample_by_len(osal_u32 cfg_debug_sample_by_len);
void hal_set_sample_cfg_0_cfg_debug_sample_end_mode(osal_u32 cfg_debug_sample_end_mode);
void hal_set_sample_cfg_0_cfg_debug_sample_start_mode(osal_u32 cfg_debug_sample_start_mode);
void hal_set_sample_cfg_2_cfg_with_sample_delay_en(osal_u32 cfg_with_sample_delay_en);
void hal_set_sample_cfg_2_cfg_debug_sample_delay(osal_u32 cfg_debug_sample_delay);
void hal_set_sample_cfg_2_cfg_with_mac_tsf_en(osal_u32 cfg_with_mac_tsf_en);
void hal_set_sample_cfg_2_cfg_with_mac_info_en(osal_u32 cfg_with_mac_info_en);
void hal_set_sample_cfg_0_cfg_debug_sample_en(osal_u32 cfg_debug_sample_en);
void hal_set_wlbb_clr_sample_clear_sample_done(osal_u32 clear_sample_done);
osal_void hal_set_sample_cfg_0_cfg_phy_data_sample_cg_bps(osal_u32 cfg_phy_data_sample_cg_bps);
osal_void hal_set_sample_cfg_0_cfg_phy_data_sample_clk_en(osal_u32 cfg_phy_data_sample_clk_en);
#endif
#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif  // __CALI_PHY_REG_IF_H__