/*
 * Copyright (c) @CompanyNameMagicTag 2021-2021. All rights reserved.
 * Description:  Default memory configurations
 * Author: @CompanyNameTag
 * Create:  2021-06-16
 */

#ifndef CCORE_MEMORY_CONFIG_H
#define CCORE_MEMORY_CONFIG_H

#include "memory_config_common.h"

#define CT_SRAM_ORIGIN  0x00010000
#if defined(CONFIG_DEVICE_MODE) || defined(_PRE_FEATURE_WS53_DEVICE_MODE) || defined(TEST_SUITE)
#define CT_SRAM_LENGTH  0x13F00
#else
#define CT_SRAM_LENGTH  0xFF00
#endif
#define CT_SRAM_END     (CT_SRAM_ORIGIN + CT_SRAM_LENGTH)

#define CT_PRESERVE_SHARE_ORIGIN CT_SRAM_END
#define CT_PRESERVE_SHARE_LENGTH 0x100

#define CCORE_RAM_STARTUP_ADDR      CT_SRAM_ORIGIN
#define CCORE_RAM_STARTUP_LEN       0x80

#define CCORE_RAM_SECOND_ADDR       (CT_SRAM_ORIGIN + CCORE_RAM_STARTUP_LEN)
#define CCORE_RAM_SECOND_LEN        (CT_SRAM_LENGTH - CCORE_RAM_STARTUP_LEN)

#define CT_ROM_ORIGIN   0x40000
#define CT_ROM_LENGTH   0x48000
#define CT_ROM_END      (CT_ROM_ORIGIN + CT_ROM_LENGTH)

#define EM_MUX_RAM_ORIGIN           0x30000
#define EM_MUX_RAM_LEN              0x2000

#define IPC_BUFF_SHARE_ORIGIN       0x80000

#define CCORE_ROM_START_ORIGIN   CT_ROM_ORIGIN
#define CCORE_ROM_START_LENGTH   0x340

#define CCORE_ROM_CODE_ORIGIN       (CT_ROM_ORIGIN + CCORE_ROM_START_LENGTH)
#define CCORE_ROM_CODE_LENGTH       (CT_ROM_LENGTH - CCORE_ROM_START_LENGTH)

#define CCORE_FLASH_PROGRAM_ORIGIN  FALSH_CCORE_PROGRAM_ORIGIN
#define CCORE_FLASH_PROGRAM_LENGTH  FLASH_CCORE_PROGRAM_LENGTH
#define CCORE_FLASH_PROGRAM_END     (APP_FLASH_PROGRAM_ORIGIN + APP_FLASH_PROGRAM_LENGTH)

#define CCORE_FLASH_ROM_ADDR        (CCORE_FLASH_PROGRAM_ORIGIN - CODE_INFO_OFFSET)
#define CCORE_FLASH_ROM_LEN         0x0

#define CCORE_FLASH_STARTUP_ADDR    (FALSH_CCORE_PROGRAM_ORIGIN + CCORE_FLASH_ROM_LEN)
#define CCORE_FLASH_STARTUP_LEN     CCORE_RAM_STARTUP_LEN

#define CCORE_FLASH_SECOND_ADDR     (CCORE_FLASH_STARTUP_ADDR + CCORE_RAM_STARTUP_LEN)
#define CCORE_FLASH_SECOND_LEN      (FLASH_CCORE_PROGRAM_LENGTH - CCORE_FLASH_ROM_LEN - CCORE_RAM_STARTUP_LEN)

#define C_USER_HEAP_LEN          0x6000
#define C_USER_STACK_LEN         0x1000

#define C_USER_SMALL_HEAP_LEN    0x4000 /* CONFIG_MCU_MODE_3 only, heap size 16k */

#if defined(CONFIG_DEVICE_MODE) || defined(_PRE_FEATURE_WS53_DEVICE_MODE)
#define C_USER_HEAP_ADDR         (CT_SRAM_END - C_USER_HEAP_LEN)
#define C_USER_STACK_ADDR        (C_USER_HEAP_ADDR - C_USER_STACK_LEN)
#else
#define C_USER_HEAP_ADDR         (ACORE_MUX_RAM_END - C_USER_HEAP_LEN)
#define C_USER_STACK_ADDR        (CT_SRAM_END - C_USER_STACK_LEN)
#endif
#define C_IPC_BUFF_ADDR          (C_USER_STACK_ADDR - IPC_BUFF_SHARE_LEN)
#define C_USER_PATCH_LEN         1956
#define C_USER_PATCH_ADDR        (C_IPC_BUFF_ADDR - C_USER_PATCH_LEN)

#endif /* End of CCORE_MEMORY_CONFIG_H */
