/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { AbilityInfo } from 'bundleManager.AbilityInfo';
import { ExtensionAbilityInfo } from 'bundleManager.ExtensionAbilityInfo';
import { Metadata } from 'bundleManager.Metadata';
import bundleManager from '@ohos.bundle.bundleManager';
import { HapModuleInfo, Dependency, PreloadItem, RouterItem, DataItem } from 'bundleManager.HapModuleInfo'

export class HapModuleInfoInner implements HapModuleInfo {
  readonly name: string = "";
  readonly icon: string = "";
  readonly iconId: long;
  readonly label: string = "";
  readonly labelId: long;
  readonly description: string = "";
  readonly descriptionId: long;
  readonly mainElementName: string = "";
  readonly abilitiesInfo: Array<AbilityInfo> = new Array<AbilityInfo>;
  readonly extensionAbilitiesInfo: Array<ExtensionAbilityInfo> = new Array<ExtensionAbilityInfo>;
  readonly metadata: Array<Metadata> = new Array<Metadata>;
  readonly deviceTypes: Array<string> = new Array<string>;
  readonly installationFree: boolean;
  readonly hashValue: string = "";
  readonly type: bundleManager.ModuleType = bundleManager.ModuleType.ENTRY;
  readonly dependencies: Array<Dependency> = new Array<Dependency>;
  readonly preloads: Array<PreloadItem> = new Array<PreloadItem>;
  readonly fileContextMenuConfig: string = "";
  readonly routerMap: Array<RouterItem> = new Array<RouterItem>;
  readonly nativeLibraryPath: string = "";
  readonly codePath: string = "";

  constructor() { }
  constructor(name: string,
    icon: string,
    iconId: long,
    label: string,
    labelId: long,
    description: string,
    descriptionId: long,
    mainElementName: string,
    abilitiesInfo: Array<AbilityInfo>,
    extensionAbilitiesInfo: Array<ExtensionAbilityInfo>,
    metadata: Array<Metadata>,
    deviceTypes: Array<string>,
    installationFree: boolean,
    hashValue: string,
    type: bundleManager.ModuleType,
    dependencies: Array<Dependency>,
    preloads: Array<PreloadItem>,
    fileContextMenuConfig: string,
    routerMap: Array<RouterItem>,
    nativeLibraryPath: string,
    codePath: string) {
      this.name = name;
      this.icon = icon;
      this.iconId = iconId;
      this.label = label;
      this.labelId = labelId;
      this.description = description;
      this.descriptionId = descriptionId;
      this.mainElementName = mainElementName;
      this.abilitiesInfo = abilitiesInfo;
      this.extensionAbilitiesInfo = extensionAbilitiesInfo;
      this.metadata = metadata;
      this.deviceTypes = deviceTypes;
      this.installationFree = installationFree;
      this.hashValue = hashValue;
      this.type = type;
      this.dependencies = dependencies;
      this.preloads = preloads;
      this.fileContextMenuConfig = fileContextMenuConfig;
      this.routerMap = routerMap;
      this.nativeLibraryPath = nativeLibraryPath;
      this.codePath = codePath;
  }
  constructor(abilitiesInfo: Array<AbilityInfo>, extensionAbilitiesInfo: Array<ExtensionAbilityInfo>) {
      this.abilitiesInfo = abilitiesInfo;
      this.extensionAbilitiesInfo = extensionAbilitiesInfo;
  }
}

export class DependencyInner implements Dependency {
  readonly moduleName: string = "";
  readonly bundleName: string = "";
  readonly versionCode: long;

  constructor() { }
  constructor(moduleName: string, bundleName: string, versionCode: long) {
    this.moduleName = moduleName;
    this.bundleName = bundleName;
    this.versionCode = versionCode;
  }
}

export class PreloadItemInner implements PreloadItem {
  readonly moduleName: string = "";

  constructor() { }
  constructor(moduleName: string) {
    this.moduleName = moduleName;
  }
}

export class RouterItemInner implements RouterItem {
  readonly name: string = "";
  readonly pageSourceFile: string = "";
  readonly buildFunction: string = "";
  readonly customData: string = "";
  readonly data: Array<DataItem> = new Array<DataItem>;

  constructor() { }
  constructor(name: string, pageSourceFile: string, buildFunction: string, customData: string, data: Array<DataItem>) {
    this.name = name;
    this.pageSourceFile = pageSourceFile;
    this.buildFunction = buildFunction;
    this.customData = customData;
    this.data = data;
  }
}

export class DataItemInner implements DataItem {
  readonly key: string = "";
  readonly value: string = "";

  constructor() { }
  constructor(key: string, value: string) {
    this.key = key;
    this.value = value;
  }
}