/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import bundleManager from '@ohos.bundle.bundleManager';
import { SharedBundleInfo, SharedModuleInfo } from 'bundleManager.SharedBundleInfo'

export class SharedBundleInfoInner implements SharedBundleInfo {
  public readonly name: string = '';
  public readonly compatiblePolicy: bundleManager.CompatiblePolicy =
    bundleManager.CompatiblePolicy.BACKWARD_COMPATIBILITY;
  public readonly sharedModuleInfo: Array<SharedModuleInfo> = new Array<SharedModuleInfo>;

  constructor() { }
  constructor(name: string,
    compatiblePolicy: bundleManager.CompatiblePolicy,
    sharedModuleInfo: Array<SharedModuleInfo>) {
      this.name = name;
      this.compatiblePolicy = compatiblePolicy;
      this.sharedModuleInfo = sharedModuleInfo;
  }
}

export class SharedModuleInfoInner implements SharedModuleInfo {
  public readonly name: string = '';
  public readonly versionCode: long;
  public readonly versionName: string = '';
  public readonly description: string = '';
  public readonly descriptionId: long;

  constructor() { }
  constructor(name: string,
    versionCode: long,
    versionName: string,
    description: string,
    descriptionId: long) {
      this.name = name;
      this.versionCode = versionCode;
      this.versionName = versionName;
      this.description = description;
      this.descriptionId = descriptionId;
  }
}
