# Copyright (c) 2023 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//base/hiviewdfx/hiview/hiview.gni")
import("//build/ohos.gni")

config("ucolletciton_utility_config") {
  visibility = [ "*:*" ]
  include_dirs = [
    "$hiview_interfaces/inner_api/unified_collection",
    "$hiview_interfaces/inner_api/unified_collection/utility",
    "$hiview_interfaces/inner_api/unified_collection/resource",
  ]
}

ohos_shared_library("libucollection_utility") {
  cflags_cc = [ "-Os" ]
  branch_protector_ret = "pac_ret"

  public_configs = [ ":ucolletciton_utility_config" ]
  sources = []

  deps = [ "$hiview_framework/native/unified_collection:ucollection_source" ]

  external_deps = [ "hilog:libhilog" ]

  version_script = "libucollectionutility.map"

  if (has_hiprofiler) {
    external_deps += [ "hiprofiler:libnative_daemon_client" ]
  }

  innerapi_tags = [ "platformsdk" ]
  part_name = "hiview"
  subsystem_name = "hiviewdfx"
}

config("ucolletciton_graphic_config") {
  visibility = [ "*:*" ]
  include_dirs = [
    "$hiview_base/include",
    "$hiview_framework/native/unified_collection/collector/inner_include",
    "$hiview_framework/native/unified_collection/graphic_memory/include",
    "$hiview_interfaces/inner_api/unified_collection",
    "$hiview_interfaces/inner_api/unified_collection/resource",
    "$hiview_interfaces/inner_api/unified_collection/utility",
  ]
}

ohos_shared_library("libucollection_graphic") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }
  public_configs = [ ":ucolletciton_graphic_config" ]

  sources = [ "$hiview_framework/native/unified_collection/collector/graphic_memory_collector_entity.cpp" ]

  deps = [ "$hiview_framework/native/unified_collection/graphic_memory:libgraphic_memory" ]

  external_deps = [ "hilog:libhilog" ]

  version_script = "libucollectiongraphic.map"

  innerapi_tags = [ "platformsdk" ]
  part_name = "hiview"
  subsystem_name = "hiviewdfx"
}

ohos_static_library("trace_strategy_for_tdd") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }

  public_configs = [ ":ucolletciton_utility_config" ]

  sources = []

  deps = [
    "$hiview_framework/native/unified_collection:memory_collector_empty_source",
    "$hiview_framework/native/unified_collection:cpu_collector_empty_source",
  ]

  part_name = "hiview"
  subsystem_name = "hiviewdfx"
}
