#!/usr/bin/python
#
# Copyright (c) 2022 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys

print(os.getcwd())

if "DEVTESTDIR" in os.environ:
    homedir = os.environ["DEVTESTDIR"]
    os.chdir(homedir)
    print(os.getcwd())
    cmd = "./start.sh"
    for index in range (1, len(sys.argv)):
        cmd += " " + sys.argv[index]
    print(cmd)
    os.system(cmd)
else:
    print("no DEVTESTDIR!!")