# Copyright (c) 2021 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//base/hiviewdfx/hiview/hiview.gni")
import("//build/ohos.gni")

config("freeze_detector_config") {
  visibility = [ ":*" ]
  include_dirs = [
    "//base/hiviewdfx/hiview/base/include",
    "//base/hiviewdfx/hiview/utility/smart_parser",
    "//base/hiviewdfx/hiview/base/event_store/include",
    "//base/hiviewdfx/hiview/plugins/faultlogger/interfaces/cpp/innerkits/include",
    ".",
  ]
}

ohos_source_set("freeze_detector") {
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }
  branch_protector_ret = "pac_ret"

  cflags_cc = [  "-Os" ]

  part_name = "hiview"
  subsystem_name = "hiviewdfx"
  include_dirs =
      [ "$hiview_framework/native/unified_collection/process/include" ]

  sources = [
    "db_helper.cpp",
    "freeze_common.cpp",
    "freeze_detector_plugin.cpp",
    "resolver.cpp",
    "rule_cluster.cpp",
    "get_ratio_utils.cpp",
    "vendor.cpp",
    "watch_point.cpp",
    "freeze_manager.cpp",
  ]

  configs = [ ":freeze_detector_config" ]

  external_deps = [
    "c_utils:utils",
    "ffrt:libffrt",
    "hilog:libhilog",
    "init:libbegetutil",
    "ipc:ipc_single",
    "libxml2:libxml2",
    "power_manager:powermgr_client",
  ]

  deps = [
    "$hiview_base:hiviewbase",
    "$hiview_interfaces/inner_api/unified_collection/utility:libucollection_utility",
    "$hiview_plugin/faultlogger:libfaultlogger",
    "config:config",
  ]
}

group("unittest") {
  testonly = true
  deps = []
  if (hiview_freeze_collect_enable) {
    deps += [ "test:FreezeManagerTest" ]
  }
}

group("moduletest") {
  testonly = true
  deps = []
}
