/**
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { resStr} from '../../Utils/resString';


import router from '@ohos.router';
import promptAction from '@ohos.promptAction';

const PAGE_URI_GET_SPP_CLIENT_TEST_MANAGER = 'pages/subManualApiTestManager/subSppTestManager/sppClientManager';
const PAGE_URI_GET_SPP_SERVER_TEST_MANAGER = 'pages/subManualApiTestManager/subSppTestManager/sppServerManager';

export function testSppClient(): string {
  router.pushUrl({url: PAGE_URI_GET_SPP_CLIENT_TEST_MANAGER})
  let message = resStr($r('app.string.bluetoothtest_str_tzcg'))
  promptAction.showToast({message: message})
  return message
}

export function testSppServer(): string {
  router.pushUrl({url: PAGE_URI_GET_SPP_SERVER_TEST_MANAGER})
  let message = resStr($r('app.string.bluetoothtest_str_tzcg'))
  promptAction.showToast({message: message})
  return message
}