# Copyright (c) 2024-2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//base/hiviewdfx/hiview/hiview.gni")
import("//build/test.gni")

module_output_path = hiview_module + "/usage_event_report"

config("usage_event_report_test_config") {
  visibility = [ ":*" ]

  include_dirs = [
    ".",
    "$hiview_base/event_report/event/include",
    "$hiview_base/event_report/factory/include",
    "$hiview_base/event_report/include",
    "$hiview_plugin/usage_event_report/cache/include",
    "$hiview_plugin/usage_event_report/event/include",
    "$hiview_plugin/usage_event_report/fold/cache/include",
    "$hiview_plugin/usage_event_report/fold/event/include",
    "$hiview_plugin/usage_event_report/fold/include",
    "$hiview_plugin/usage_event_report/idl/include",
    "$hiview_plugin/usage_event_report/include",
    "$hiview_plugin/usage_event_report/service/factory/include",
  ]

  cflags = [ "-D__UNITTEST__" ]
}

ohos_unittest("UsageEventReportTest") {
  module_out_path = module_output_path
  configs = [ ":usage_event_report_test_config" ]

  sources = [ "usage_event_report_test.cpp" ]

  deps = [
    "$hiview_base:hiviewbase",
    "$hiview_plugin/usage_event_report:usage_event_report",
  ]

  external_deps = [
    "c_utils:utils",
    "ffrt:libffrt",
    "googletest:gtest_main",
    "hilog:libhilog",
    "hisysevent:libhisysevent",
    "ipc:ipc_single",
    "relational_store:native_rdb",
  ]

  defines = []
  if (power_manager_enable) {
    external_deps += [ "power_manager:powermgr_client" ]
    defines += [ "POWER_MANAGER_ENABLE" ]
  }

  if (hiview_usage_fold_stat_enable) {
    defines += [ "USAGE_FOLD_STAT_ENABLE" ]
  }
}

ohos_unittest("UsageEventReportCacheTest") {
  module_out_path = module_output_path
  configs = [ ":usage_event_report_test_config" ]

  sources = [ "usage_event_report_cache_test.cpp" ]

  deps = [
    "$hiview_base:hiviewbase",
    "$hiview_base/event_report:hiview_event_report",
    "$hiview_plugin/usage_event_report:usage_event_report_for_test",
  ]

  external_deps = [
    "c_utils:utils",
    "ffrt:libffrt",
    "googletest:gtest_main",
    "hilog:libhilog",
    "hisysevent:libhisysevent",
    "relational_store:native_rdb",
  ]
}

ohos_unittest("FoldAppUsageTest") {
  module_out_path = module_output_path
  configs = [ ":usage_event_report_test_config" ]

  sources = [ "fold_app_usage_test.cpp" ]

  deps = [
    "$hiview_base:hiviewbase",
    "$hiview_plugin/usage_event_report:usage_event_report_for_test",
  ]

  external_deps = [
    "c_utils:utils",
    "ffrt:libffrt",
    "googletest:gtest_main",
    "hilog:libhilog",
    "hisysevent:libhisysevent",
    "jsoncpp:jsoncpp",
    "relational_store:native_rdb",
  ]
  defines = []
  if (hiview_support_fold_pc_count_duration_enable) {
    defines += [ "FOLD_PC_COUNT_DURATION_ENABLE" ]
  }
  resource_config_file =
      "$hiview_plugin/usage_event_report/test/resource/ohos_test.xml"
}
