/*
 * Copyright (c) CompanyNameMagicTag 2020-2023. All rights reserved.
 * Description: hcc product configuration.
 * Author: CompanyName
 * Create: 2020-05-13
 */

#include "hcc_cfg.h"
#include "hcc_flow_ctrl.h"

static hcc_queue_cfg g_hcc_queue_cfg[] = {
    { HCC_DIR_TX, HCC_QUEUE_INTERNAL,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_OAM,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_RX, HCC_QUEUE_INTERNAL,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_OAM,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_TX, BT_DATA_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_BT,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_RX, BT_DATA_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_BT,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_TX, SLE_DATA_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_SLE,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_RX, SLE_DATA_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_SLE,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_TX, BTC_MSG_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_BTC_MSG,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_RX, BTC_MSG_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_BTC_MSG,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_RX, CTRL_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_CUSTOMIZE,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_TX, CTRL_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_CUSTOMIZE,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_RX, DATA_HI_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_WIFI,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_TX, DATA_HI_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_WIFI,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_POSTMEM,
      .queue_ctrl.fc_enable = HCC_ENABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = 0,
    },
    { HCC_DIR_RX, DATA_LO_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_WIFI,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_PREMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = HCC_DATA_QUEUE_BUF_LEN,
    },
    { HCC_DIR_TX, DATA_LO_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_WIFI,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_PREMEM,
      .queue_ctrl.fc_enable = HCC_ENABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_DEFAULT_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = HCC_DATA_QUEUE_BUF_LEN,
    },
    { HCC_DIR_TX, HCC_TEST_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_TEST,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_PREMEM,
      .queue_ctrl.fc_enable = HCC_ENABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_MAX_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = HCC_DATA_QUEUE_BUF_LEN,
    },
    { HCC_DIR_RX, HCC_TEST_QUEUE,
      .queue_ctrl.service_type = HCC_ACTION_TYPE_TEST,
      .queue_ctrl.transfer_mode = HCC_IPC_TRANS_PREMEM,
      .queue_ctrl.fc_enable = HCC_DISABLE,
      .queue_ctrl.flow_type = HCC_FLOWCTRL_DATA,
      .queue_ctrl.low_waterline = HCC_FLOWCTRL_DEFAULT_LO_WATER_LINE,
      .queue_ctrl.high_waterline = HCC_FLOWCTRL_DEFAULT_HI_WATER_LINE,
      .queue_ctrl.burst_limit = HCC_MAX_QUEUE_TRANSFER_BURST_LIMIT,
      .queue_ctrl.credit_bottom_value = HCC_FLOWCTRL_DEFAULT_CREDIT_BOTTOM_VALUE,
      .queue_ctrl.extend = HCC_DATA_QUEUE_BUF_LEN,
    }
};

hcc_queue_cfg *hcc_get_queue_cfg(uint8_t *arr_len)
{
    size_t len = sizeof(g_hcc_queue_cfg) / sizeof(g_hcc_queue_cfg[0]);
    *arr_len = (uint8_t)len;
    return g_hcc_queue_cfg;
}

bool hcc_check_bt_queue(uint8_t queue_id)
{
    if (queue_id == BT_DATA_QUEUE ||
        queue_id == SLE_DATA_QUEUE ||
        queue_id == BTC_MSG_QUEUE) {
        return TD_TRUE;
    } else {
        return TD_FALSE;
    }
}
