/*
 * Copyright (c) @CompanyNameMagicTag 2021-2021. All rights reserved.
 * Description:  Default memory configurations
 * Author: @CompanyNameTag
 * Create: 2021-03-09
 */
#ifndef __LINKER_FUNCTION_H__
#define __LINKER_FUNCTION_H__

/*==================== ROM   ========================*/

/* platform rom component configuration with keep */
#ifdef USE_WS53_ROM_REPO
#define PLT_ROM_KEEP(sections_patterns) \
    KEEP(SORT(*liblibboundscheck_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_dma_v151_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libsystick_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libsystick_port_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libsyschannel_filter_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libhcc_host_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libtcxo_port_rom.a:)(sections_patterns)) \
    KEEP(SORT(*librtc_unified_port_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libtcxo_rom.a:)(sections_patterns)) \
    KEEP(SORT(*librtc_unified_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libsdio_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_sdio_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libsdio_port_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libipc_porting_acore_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libipc_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_ipc_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_rtc_unified_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_tcxo_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_systick_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libdma_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libdma_port_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libversion_rom.a:)(sections_patterns)) \
    KEEP(SORT(*libws53_flash_patch_rom.a:)(sections_patterns))
#else
#define PLT_ROM_KEEP(sections_patterns) \
    KEEP(SORT(*libipc.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_ipc.a:)(sections_patterns)) \
    KEEP(SORT(*libipc_porting_acore.a:)(sections_patterns)) \
    KEEP(SORT(*libdma.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_dma_v151.a:)(sections_patterns)) \
    KEEP(SORT(*libdma_port.a:)(sections_patterns)) \
    KEEP(SORT(*libtcxo.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_tcxo.a:)(sections_patterns)) \
    KEEP(SORT(*libtcxo_port.a:)(sections_patterns)) \
    KEEP(SORT(*libsystick.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_systick.a:)(sections_patterns)) \
    KEEP(SORT(*libsystick_port.a:)(sections_patterns)) \
    KEEP(SORT(*librtc_unified.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_rtc_unified.a:)(sections_patterns)) \
    KEEP(SORT(*librtc_unified_port.a:)(sections_patterns)) \
    KEEP(SORT(*libws53_flash_patch.a:)(sections_patterns)) \
    KEEP(SORT(*libsyschannel_filter.a:)(sections_patterns)) \
    KEEP(SORT(*libsdio.a:)(sections_patterns)) \
    KEEP(SORT(*libhal_sdio.a:)(sections_patterns)) \
    KEEP(SORT(*libsdio_port.a:)(sections_patterns))
#endif

/* platform rom component configuration */
#define PLT_ROM_NO_KEEP(sections_patterns)

/* wifi rom component configuration with keep */
#define WIFI_ROM_KEEP(sections_patterns)

/* wifi rom component configuration */
#define WIFI_ROM_NO_KEEP(sections_patterns)

/* btc rom component configuration with keep */
#define BTC_ROM_KEEP(sections_patterns)

/* btc rom component configuration */
#define BTC_ROM_NO_KEEP(sections_patterns)

/* bth rom component configuration with keep */
#define BTH_ROM_KEEP(sections_patterns)

/* bth rom component configuration */
#define BTH_ROM_NO_KEEP(sections_patterns)

/*==================== SRAM  ========================*/
/*==================== Flash ========================*/

/* platform flash component configuration */
#define PLT_FLASH(sections_patterns) \
    SORT(*libcsysdeps.a:)(sections_patterns) \
    SORT(*libtargets.a:)(sections_patterns) \
    SORT(*libc.a:)(sections_patterns) \
    SORT(*libgcc.a:)(sections_patterns) \
    SORT(*libm.a:)(sections_patterns) \
    SORT(*libws53_standard.a:)(sections_patterns) \
    SORT(*libbuild_version.a:)(sections_patterns) \
    SORT(*libhcc_host_ram.a:)(sections_patterns) \
    SORT(*libchip_ws53_acore.a:)(sections_patterns) \
    SORT(*libbase.a:)(sections_patterns) \
    SORT(*libinterrupt.a:)(sections_patterns) \
    SORT(*libosal.a:)(sections_patterns) \
    SORT(*liblos_iperf.a:)(sections_patterns) \
    SORT(*libosal_adapt.a:)(sections_patterns) \
    SORT(*libriscv.a:)(sections_patterns) \
    SORT(*libipc.a:)(sections_patterns) \
    SORT(*libhal_ipc.a:)(sections_patterns) \
    SORT(*libipc_porting_acore.a:)(sections_patterns) \
    SORT(*libdma.a:)(sections_patterns) \
    SORT(*libhal_dma_v151.a:)(sections_patterns) \
    SORT(*libdma_port.a:)(sections_patterns) \
    SORT(*libnon_os.a:)(sections_patterns) \
    SORT(*libinit.a:)(sections_patterns) \
    SORT(*libcpup.a:)(sections_patterns) \
    SORT(*libdriverbase.a:)(sections_patterns) \
    SORT(*libcmsis.a:)(sections_patterns) \
    SORT(*liblinux.a:)(sections_patterns) \
    SORT(*libcpu_trace.a:)(sections_patterns) \
    SORT(*libgpio.a:)(sections_patterns) \
    SORT(*libpinctrl.a:)(sections_patterns) \
    SORT(*libpmp.a:)(sections_patterns) \
    SORT(*libsdio.a:)(sections_patterns) \
    SORT(*libsec_rsa.a:)(sections_patterns) \
    SORT(*libdrv_security_unified.a:)(sections_patterns) \
    SORT(*libdrv_timer.a:)(sections_patterns) \
    SORT(*libuart.a:)(sections_patterns) \
    SORT(*libwatchdog.a:)(sections_patterns) \
    SORT(*libhal_cpu_trace.a:)(sections_patterns) \
    SORT(*libhal_gpio_v150.a:)(sections_patterns) \
    SORT(*libhal_pinctrl.a:)(sections_patterns) \
    SORT(*libhal_pmp.a:)(sections_patterns) \
    SORT(*libhal_reboot.a:)(sections_patterns) \
    SORT(*libhal_sdio.a:)(sections_patterns) \
    SORT(*libhal_security_unified.a:)(sections_patterns) \
    SORT(*libhal_timer.a:)(sections_patterns) \
    SORT(*libhal_uart_v151.a:)(sections_patterns) \
    SORT(*libgpio_port.a:)(sections_patterns) \
    SORT(*libsdio_port.a:)(sections_patterns) \
    SORT(*libtimer_port.a:)(sections_patterns) \
    SORT(*libdfx_log.a:)(sections_patterns) \
    SORT(*libwatchdog_port.a:)(sections_patterns) \
    SORT(*libpmp_port.a:)(sections_patterns) \
    SORT(*libuart_port.a:)(sections_patterns) \
    SORT(*libpinctrl_port.a:)(sections_patterns) \
    SORT(*libws53_clocks.a:)(sections_patterns) \
    SORT(*libdfx_port_ws53.a:)(sections_patterns) \
    SORT(*libws53_hcc_cfg.a:)(sections_patterns) \
    SORT(*libalgorithm.a:)(sections_patterns) \
    SORT(*libapp_init.a:)(sections_patterns) \
    SORT(*libat.a:)(sections_patterns) \
    SORT(*libconnectivity.a:)(sections_patterns) \
    SORT(*libcpu_utils.a:)(sections_patterns) \
    SORT(*libreboot.a:)(sections_patterns) \
    SORT(*libdiag_dfx_cmd.a:)(sections_patterns) \
    SORT(*libdfx_diag.a:)(sections_patterns) \
    SORT(*libdfx_panic.a:)(sections_patterns) \
    SORT(*libdfx_preserve.a:)(sections_patterns) \
    SORT(*libdfx_exception.a:)(sections_patterns) \
    SORT(*libhal_uart.a:)(sections_patterns) \
    SORT(*libhal_watchdog.a:)(sections_patterns) \
    SORT(*libsyschannel_dev.a:)(sections_patterns) \
    SORT(*liblibboundscheck_ram.a:)(sections_patterns) \
    SORT(*libdma_flash.a:)(sections_patterns) \
    SORT(*libhal_dma_v151_flash.a:)(sections_patterns) \
    SORT(*libdma_port_flash.a:)(sections_patterns) \
    SORT(*libacore_trng_buffer.a:)(sections_patterns) \
    SORT(*libmips.a:)(sections_patterns) \
    SORT(*libboundscheck_sscanf_s.a:)(sections_patterns)

/* wifi flash component configuration */
#define WIFI_FLASH(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_rx_data_event.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_rx_data_feature.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_rx_data_filter.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_rx_data.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_tx_data.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_tx_encap.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_tx_mpdu_adapt.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*hmac_tx_mpdu_queue.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*frw_hmac.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*frw_thread.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*frw_hcc_adapt.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*frw_hmac_adapt.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*frw_main.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:*frw_util_notifier.c.obj)(sections_patterns) \
    SORT(*libwifi_driver_tcm.a:)(sections_patterns) \
    SORT(*libwifi_pk_txrx.a:*hmac_rx_pk.c.obj)(sections_patterns) \
    SORT(*libwifi_pk_txrx.a:*hmac_tx_pk.c.obj)(sections_patterns) \
    SORT(*libwifi_drv_ws53.a:)(sections_patterns) \
    SORT(*libwifi_frag.a:)(sections_patterns) \
    SORT(*libwifi_auto_adjust_freq.a:)(sections_patterns) \
    SORT(*libwifi_repeater.a:)(sections_patterns) \
    SORT(*libwifi_wapi.a:)(sections_patterns) \
    SORT(*libwifi_tx_amsdu.a:)(sections_patterns) \
    SORT(*libwifi_btcoex.a:)(sections_patterns) \
    SORT(*libwifi_alg_txbf.a:)(sections_patterns) \
    SORT(*libwifi_alg_temp_protect.a:)(sections_patterns) \
    SORT(*libwifi_alg_anti_interference.a:)(sections_patterns) \
    SORT(*libwifi_alg_edca_opt.a:)(sections_patterns) \
    SORT(*libwifi_alg_cca_opt.a:)(sections_patterns) \
    SORT(*libwifi_csa.a:)(sections_patterns) \
    SORT(*libwifi_mbo.a:)(sections_patterns) \
    SORT(*libwifi_bsrp_nfrp.a:)(sections_patterns) \
    SORT(*libwifi_slp.a:)(sections_patterns) \
    SORT(*libwifi_apf.a:)(sections_patterns) \
    SORT(*libwifi_11k.a:)(sections_patterns) \
    SORT(*libwifi_11v.a:)(sections_patterns) \
    SORT(*libwifi_11r.a:)(sections_patterns) \
    SORT(*libwifi_csi.a:)(sections_patterns) \
    SORT(*libwifi_m2u.a:)(sections_patterns) \
    SORT(*libwifi_blacklist.a:)(sections_patterns) \
    SORT(*libwifi_sdp.a:)(sections_patterns) \
    SORT(*libwifi_wps.a:)(sections_patterns) \
    SORT(*libwifi_latency.a:)(sections_patterns) \
    SORT(*libwifi_promisc.a:)(sections_patterns) \
    SORT(*libwifi_uapsd_sta.a:)(sections_patterns) \
    SORT(*libwifi_roam.a:)(sections_patterns) \
    SORT(*libwifi_ant_sel.a:)(sections_patterns) \
    SORT(*libwifi_psd.a:)(sections_patterns) \
    SORT(*libwifi_twt.a:)(sections_patterns) \
    SORT(*libwifi_uapsd_ap.a:)(sections_patterns) \
    SORT(*libwifi_dnb.a:)(sections_patterns) \
    SORT(*libwifi_sr.a:)(sections_patterns) \
    SORT(*libwifi_service.a:)(sections_patterns) \
    SORT(*libwifi_at.a:)(sections_patterns) \
    SORT(*libmbedtls.a:)(sections_patterns) \
    SORT(*liblwip_tcm.a:)(sections_patterns) \
    SORT(*liblwip.a:)(sections_patterns) \
    SORT(*libwpa_supplicant.a:)(sections_patterns)

/* btc flash component configuration */
#define BTC_FLASH(sections_patterns)

/* bth flash component configuration */
#define BTH_FLASH(sections_patterns) \
    SORT(*libbg_common.a:)(sections_patterns) \
    SORT(*libbt_at.a:)(sections_patterns) \
    SORT(*libbt_host.a:)(sections_patterns) \
    SORT(*libbth_sdk.a:)(sections_patterns) \
    SORT(*libbt_app.a:)(sections_patterns) \
    SORT(*libbth_gle.a:)(sections_patterns) \
    SORT(*libsamples.a:)(sections_patterns) \
    SORT(*libtestsuite.a:)(sections_patterns)

#define PLT_SRAM(sections_patterns) \
    SORT(*libinterrupt.a:riscv_himideerv200_plic.c.obj)(sections_patterns) \
    SORT(*libbase.a:los_multipledlinkhead.c.obj)(sections_patterns) \
    SORT(*libbase.a:los_sched.c.obj)(sections_patterns) \
    SORT(*libbase.a:los_sortlink.c.obj)(sections_patterns) \
    SORT(*libchip_ws53_acore.a:interrupt_os_adapter.c.obj)(sections_patterns) \
    SORT(*libchip_ws53_acore.a:interrupt.c.obj)(sections_patterns) \
    SORT(*libchip_ws53_acore.a:clock_recover.c.obj)(sections_patterns) \
    SORT(*libchip_ws53_acore.a:acore_clock_recover.c.obj)(sections_patterns) \
    SORT(*libosal.a:osal_addr.c.obj)(sections_patterns) \
    SORT(*libosal.a:osal_interrupt.c.obj)(sections_patterns) \
    SORT(*libosal.a:osal_spinlock.c.obj)(sections_patterns) \
    SORT(*libosal_adapt.a:osal_adapt_task.c.obj)(sections_patterns) \
    SORT(*libosal_adapt.a:osal_adapt_timer.c.obj)(sections_patterns) \
    SORT(*libws53_standard.a:startup.s.obj)(sections_patterns) \
    SORT(*libriscv.a:dispatch.S.obj)(sections_patterns) \
    SORT(*libriscv.a:task.c.obj)(sections_patterns) \
    SORT(*libriscv.a:cache.c.obj)(sections_patterns) \
    SORT(*libosal.a:osal_wait.c.obj)(sections_patterns) \
    SORT(*libosal.a:osal_mutex.c.obj)(sections_patterns) \
    SORT(*libosal.a:osal_event.c.obj)(sections_patterns) \
    SORT(*libosal.a:osal_atomic.c.obj)(sections_patterns) \
    SORT(*libosal_adapt.a:osal_adapt_atomic.c.obj)(sections_patterns) \
    SORT(*libosal.a:oal_onetrack.c.obj)(sections_patterns) \
    SORT(*libpmp.a:)(sections_patterns) \
    SORT(*libpmp_port.a:)(sections_patterns) \
    SORT(*libpm.a:)(sections_patterns) \
    SORT(*libpm_sleep.a:)(sections_patterns) \
    SORT(*libpm_sleep_porting.a:)(sections_patterns) \
    SORT(*libpm_veto.a:)(sections_patterns) \
    SORT(*libpm_veto_porting.a:)(sections_patterns) \
    SORT(*libpm_dev.a:)(sections_patterns) \
    SORT(*libpm_dev_porting.a:)(sections_patterns) \
    SORT(*libpm_fsm.a:)(sections_patterns) \
    SORT(*libpm_fsm_porting.a:)(sections_patterns) \
    SORT(*libsfc.a:)(sections_patterns) \
    SORT(*libhal_sfc.a:)(sections_patterns) \
    SORT(*libsfc_port.a:)(sections_patterns) \
    SORT(*libsfc_port_ws53.a:)(sections_patterns) \
    SORT(*libws53_flash_recover.a:)(sections_patterns) \
    SORT(*libws53_flash_patch_port.a:)(sections_patterns)


#define HCC_ROM_TEXT \
    SORT(*libhcc_host_ram.a:*hcc_dfx.c.obj)(.text.hcc_dfx_queue_total_pkt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_alloc_cb_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_alloc_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_free_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_unc_alloc_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_mem_free_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_total_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_startsubq_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_stopsubq_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_rx_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_service_exp_rx_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_unc_free_cnt_increase) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_dfx_queue_loss_pkt_increase) \
    SORT(*libhcc_host_ram.a:*hcc_bus.c.obj)(.text.hcc_get_channel_bus) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_send_message) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_bus_call_rx_message) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_bus_tx_proc) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_bus_get_credit) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_get_channel_align_len) \
    SORT(*libhcc_host_ram.a:*hcc_service.c.obj)(.text.hcc_get_serv_list) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_get_serv_info) \
    SORT(*libhcc_host_ram.a:*hcc_flow_ctrl.c.obj)(.text.fc_below_low_waterline) \
    SORT(*libhcc_host_ram.a:)(.text.fc_wait_queue_cond) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_flow_ctrl_sched_check) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_flow_ctrl_process) \
    SORT(*libhcc_host_ram.a:)(.text.fc_above_high_waterline) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_adapt_tx_start_subq) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_flow_ctrl_pre_proc) \
    SORT(*libhcc_host_ram.a:*hcc.c.obj)(.text.hcc_get_head_len) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_sched_transfer) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_check_header_vaild) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_queue_id_2_service_type) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_fuzzy_trans_queue_2_service) \
    SORT(*libhcc_host_ram.a:hcc_channel.c.obj)(*.text*) \
    SORT(*libhcc_host_ram.a:hcc_rom_callback.c.obj)(*.text*) \
    SORT(*libhcc_host_ram.a:hcc_adapt.c.obj)(*.text*) \
    SORT(*libhcc_host_ram.a:hcc_list.c.obj)(*.text*) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_init_unc_buf) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_tx_proc) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_adapt_tx_param_check)

#define HCC_SRAM_TEXT \
    SORT(*libhcc_host_ram.a:*hcc_ipc_host.c.obj)(.text.hcc_ipc_is_busy) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_complete_callback) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_send_msg) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_free_unclist) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_mem_reply_handle) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_get_dma_param_index) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_get_dma_status) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_thread_wait_cond) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_clr_dma_status) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_mem_dma) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_data_transfer) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_queue_set_dma_busy.isra.8) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_thread_rcv_data) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_data_rx_callback) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_data_thread) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_msg_rx_callback) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_send_force_msg.constprop.12) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_handle_complete_msg) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_tx_proc) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_ipc_tx_dma_is_busy) \
    SORT(*libhcc_host_ram.a:*hcc.c.obj)(.text.hcc_thread_wait_queue_cond) \
    SORT(*libhcc_host_ram.a:*hcc.c.obj)(.text.hcc_check_queue_cond) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_tx_queue_proc) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_rx_queue_proc) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_transfer_thread) \
    SORT(*libhcc_host_ram.a:)(.text.hcc_tx_data)


#define LITEOS_SRAM_TEXT \
    SORT(*libosal.a:*osal_string.c.obj)(.text.osal_memcmp) \
    SORT(*libc.a:*memcmp.c.obj)(.text.memcmp) \
    SORT(*libc.a:*memcpy.c.obj)(.text.memcpy) \
    SORT(*libc.a:*memset.c.obj)(.text.memset) \
    SORT(*libc.a:*memalign.c.obj)(.text.memalign) \
    SORT(*libc.a:*cstdlib.c.obj)(.text.malloc) \
    SORT(*libc.a:*cstdlib.c.obj)(.text.free) \
    SORT(*libc.a:*time.c.obj)(.text.clock_gettime) \
    SORT(*libchip_ws53_acore.a:*tick_timer.c.obj)(.text.HalTickEntry) \
    SORT(*libchip_ws53_acore.a:*tick_timer.c.obj)(.text.HalClockStart) \
    SORT(*libchip_ws53_acore.a:*tick_timer.c.obj)(.text.HalDelayUs) \
    SORT(*libchip_ws53_acore.a:*tick_timer.c.obj)(.text.HalClockGetCycles) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_ListDelete) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsPreemptable) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskReSched) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskSuspend) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskAdd2TimerList) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTimerListDelete) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskScan) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_CurTaskIDGet) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsCurTaskNameGet) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskSwitchCheck) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_IdleHandlerHookReg) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsIdleHandler) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsIdleTask) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskProcSignal) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskEntry) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_TaskResume) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsSysTaskSuspend) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskWait) \
    SORT(*libbase.a:*los_task.c.obj)(.text.OsTaskWake) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_TaskYield) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_TaskDelay) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_TaskLock) \
    SORT(*libbase.a:*los_task.c.obj)(.text.LOS_TaskUnlock) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemInfoGet) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsGetRealPtr) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemMergeNode) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemListDelete.isra.7) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemSplitNode) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemAllocWithCheck) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemFreeNode) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.LOS_MemAlloc) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.LOS_MemAllocAlign) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemFree) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.LOS_MemFree) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.LOS_MemRealloc) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.LOS_MemInfoGet) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemAlloc) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemSetMagicNumAndTaskID) \
    SORT(*libbase.a:*los_memory.c.obj)(.text.OsMemListDelete.isra.*) \
    SORT(*libinterrupt.a:*riscv_himideerv200_plic.c.obj)(.rodata.g_plicOps) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_kthread_set_priority) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_kthread_lock) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_kthread_unlock) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_kthread_should_stop) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_yield) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_msleep) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_udelay) \
    SORT(*libosal.a:*osal_task.c.obj)(.text.osal_mdelay) \
    SORT(*libosal.a:*osal_timer.c.obj)(.text.osal_timer_mod) \
    SORT(*libosal.a:*osal_timer.c.obj)(.text.osal_timer_start) \
    SORT(*libosal.a:*osal_timer.c.obj)(.text.osal_timer_destroy) \
    SORT(*libosal.a:*osal_timer.c.obj)(.text.osal_gettimeofday) \
    SORT(*libosal.a:*osal_timer.c.obj)(.text.osal_msecs_to_jiffies) \
    SORT(*libosal.a:*osal_timer.c.obj)(.text.osal_jiffies_to_msecs) \
    SORT(*liblos_iperf.a:*los_iperf.c.obj)(.text.IperfServerPhase2) \
    SORT(*liblos_iperf.a:*los_iperf.c.obj)(.text.IperfClientPhase2)


/* wifi sram component configuration */
#define WIFI_SRAM(sections_patterns) \
    SORT(*libwifi_pk_txrx.a:)(sections_patterns)

/* btc sram component configuration */
#define BTC_SRAM(sections_patterns)

/* bth sram component configuration */
#define BTH_SRAM(sections_patterns)

#ifdef LWIP_TCM_OPTIMIZE
#define LWIP_TCM_SECTION \
    SORT(*liblwip_tcm.a:)(.text.get_socket) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket_unconn) \
    SORT(*liblwip_tcm.a:)(.text.sock_inc_used) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket_unconn_nouse) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket_unconn_locked) \
    SORT(*liblwip_tcm.a:)(.text.done_socket) \
    SORT(*liblwip_tcm.a:)(.text.recvfrom) \
    SORT(*liblwip_tcm.a:)(.text.lwip_recvfrom) \
    SORT(*liblwip_tcm.a:)(.text.lwip_recv_tcp) \
    SORT(*liblwip_tcm.a:)(.text.event_callback) \
    SORT(*liblwip_tcm.a:)(.text.lwip_select) \
    SORT(*liblwip_tcm.a:)(.text.select_check_waiters) \
    SORT(*liblwip_tcm.a:)(.text.netconn_apimsg) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_data) \
    SORT(*liblwip_tcm.a:)(.text.netconn_tcp_recvd_msg) \
    SORT(*liblwip_tcm.a:)(.text.netconn_tcp_recvd) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_data_tcp) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_tcp_pbuf_flags) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_udp_raw_netbuf_flags) \
    KEEP(SORT(*liblwip_tcm.a:)(.text.netconn_recv)) \
    KEEP(SORT(*liblwip_tcm.a:)(.text.netconn_sendto)) \
    SORT(*liblwip_tcm.a:)(.text.netconn_send) \
    SORT(*liblwip_tcm.a:)(.text.netconn_write_partly) \
    SORT(*liblwip_tcm.a:)(.text.netconn_write_vectors_partly) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_send) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_write) \
    SORT(*liblwip_tcm.a:)(.text.netbuf_alloc) \
    SORT(*liblwip_tcm.a:)(.text.netbuf_free) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_thread) \
    KEEP(SORT(*liblwip_tcm.a:)(.text.tcpip_thread_handle_msg)) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_inpkt) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_input) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_callback) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_try_callback) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_send_msg_wait_sem) \
    SORT(*liblwip_tcm.a:)(.text.inet_cksum_pseudo_base) \
    SORT(*liblwip_tcm.a:)(.text.inet_chksum_pseudo) \
    SORT(*liblwip_tcm.a:)(.text.etharp_output_to_arp_index) \
    SORT(*liblwip_tcm.a:)(.text.etharp_output) \
    SORT(*liblwip_tcm.a:)(.text.ip4_addr_isbroadcast_u32) \
    SORT(*liblwip_tcm.a:)(.text.ip_input) \
    SORT(*liblwip_tcm.a:)(.text.ip4_route) \
    SORT(*liblwip_tcm.a:)(.text.ip4_input) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if_opt) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if_src) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if_opt_src) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_alloc) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_add_header_impl) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_add_header) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_remove_header) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_header_impl) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_header) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_free) \
    KEEP(SORT(*liblwip_tcm.a:)(.text.pbuf_alloced_custom)) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_init_alloced_pbuf) \
    SORT(*liblwip_tcm.a:)(.text.udp_input_local_match) \
    SORT(*liblwip_tcm.a:)(.text.udp_input) \
    SORT(*liblwip_tcm.a:)(.text.udp_send_chksum) \
    SORT(*liblwip_tcm.a:)(.text.sendto) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto_chksum) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto_if) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto_if_src) \
    SORT(*liblwip_tcm.a:)(.text.ethernet_input) \
    SORT(*liblwip_tcm.a:)(.text.ethernet_output) \
    SORT(*liblwip_tcm.a:)(.text.sys_mutex_lock) \
    SORT(*liblwip_tcm.a:)(.text.sys_mutex_unlock) \
    SORT(*liblwip_tcm.a:)(.text.sys_sem_signal) \
    SORT(*liblwip_tcm.a:)(.text.sys_arch_sem_wait) \
    SORT(*liblwip_tcm.a:)(.text.sys_mbox_post) \
    SORT(*liblwip_tcm.a:)(.text.sys_mbox_trypost) \
    SORT(*liblwip_tcm.a:)(.text.sys_arch_mbox_fetch_ext) \
    SORT(*liblwip_tcm.a:)(.text.driverif_output) \
    SORT(*liblwip_tcm.a:)(.text.driverif_input) \
    SORT(*liblwip_tcm.a:)(.text.ip4_frag) \
    SORT(*liblwip_tcm.a:)(.text.ip4_reass) \
    SORT(*liblwip_tcm.a:)(.text.ip_addr_cmp) \
    SORT(*liblwip_tcm.a:)(.text.ip_addr_copy_fun) \
    SORT(*liblwip_tcm.a:)(.text.ip_addr_isany) \
    SORT(*liblwip_tcm.a:)(.text.mem_free) \
    SORT(*liblwip_tcm.a:)(.text.mem_malloc) \
    SORT(*liblwip_tcm.a:)(.text.memp_free) \
    SORT(*liblwip_tcm.a:)(.text.memp_malloc) \
    SORT(*liblwip_tcm.a:)(.text.mem_trim) \
    SORT(*liblwip_tcm.a:)(.text.netif_default) \
    SORT(*liblwip_tcm.a:)(.text.netif_find) \
    SORT(*liblwip_tcm.a:)(.text.netif_find_by_ifindex) \
    SORT(*liblwip_tcm.a:)(.text.netif_find_by_ipaddr) \
    SORT(*liblwip_tcm.a:)(.text.netif_find_dst_ipaddr) \
    SORT(*liblwip_tcm.a:)(.text.netif_ipaddr_isbrdcast) \
    SORT(*liblwip_tcm.a:)(.text.netif_loop_output) \
    SORT(*liblwip_tcm.a:)(.text.netif_loop_output_ipv4) \
    SORT(*liblwip_tcm.a:)(.text.raw_remove) \
    SORT(*liblwip_tcm.a:)(.text.raw_send) \
    SORT(*liblwip_tcm.a:)(.text.raw_sendto) \
    SORT(*liblwip_tcm.a:)(.text.tcp_abort) \
    SORT(*liblwip_tcm.a:)(.text.tcp_accept) \
    SORT(*liblwip_tcm.a:)(.text.tcp_active_pcbs) \
    SORT(*liblwip_tcm.a:)(.text.tcp_arg) \
    SORT(*liblwip_tcm.a:)(.text.tcp_backlog_accepted) \
    SORT(*liblwip_tcm.a:)(.text.tcp_backlog_delayed) \
    SORT(*liblwip_tcm.a:)(.text.tcp_listen_with_backlog_and_err) \
    SORT(*liblwip_tcm.a:)(.text.tcp_new_ip_type) \
    SORT(*liblwip_tcm.a:)(.text.tcp_recv) \
    SORT(*liblwip_tcm.a:)(.text.tcp_shutdown) \
    SORT(*liblwip_tcm.a:)(.text.tcp_sndbuf_init) \
    SORT(*liblwip_tcm.a:)(.text.tcp_write) \
    SORT(*liblwip_tcm.a:)(.text.tcp_input) \
    SORT(*liblwip_tcm.a:)(.text.recv_tcp) \
    SORT(*liblwip_tcm.a:)(.text.recv_udp) \
    SORT(*liblwip_tcm.a:)(.text.lwip_recvfrom_udp_raw*) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_copy_partial) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_copy_partial_pbuf) \
    SORT(*liblwip_tcm.a:)(.text.tcp_output) \
    SORT(*liblwip_tcm.a:)(.text.tcp_output_segment) \
    SORT(*liblwip_tcm.a:)(.text.ip_output_if) \
    SORT(*liblwip_tcm.a:)(.text.lwip_sendto) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto_if_src_chksum) \
    SORT(*liblwip_tcm.a:)(.text.ip_output_if_src)
#else
#define LWIP_TCM_SECTION
#endif


#define LITEOS_FLASH_HOT_FUNC_TEXT \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_cb_const) \
    SORT(*liblwip.a:)(.text.__bswap16) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_data) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_header) \
    SORT(*liblwip_tcm.a:)(.text.LOS_IntLock) \
    SORT(*liblwip_tcm.a:)(.text.LOS_IntRestore) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_time_after) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_pk_mode) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_get_ms) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_memory_valid) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_entry_check) \
    SORT(*liblwip.a:)(.text.get_timer_tick) \
    SORT(*libwifi_driver_tcm.a:)(.text.skb_push) \
    SORT(*liblwip_tcm.a:)(.text.sys_arch_protect) \
    SORT(*liblwip_tcm.a:)(.text.sys_arch_unprotect) \
    SORT(*libwifi_drv_ws53.a:)(.text.skb_pull) \
    SORT(*libtargets.a:)(.text.__bswap32) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_set_mac_addr) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_get_netbuf_next) \
    SORT(*libwifi_drv_ws53.a:)(.text.skb_queue_empty) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_pull) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_list_empty) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_user_get_feature_ptr) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_get_device_priv_stru) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_header) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_header_impl) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_is_dhcp_port_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.osal_get_runtime) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_byteorder_host_to_net_uint16) \
    SORT(*libwifi_driver_tcm.a:)(.text.skb_headroom) \
    SORT(*libwifi_drv_ws53.a:)(.text.osal_list_empty) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_res_get_hmac_vap) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_get_data_type_by_ethertype) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_add_header_impl) \
    SORT(*libwifi_drv_ws53.a:)(.text.frw_get_head_len) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_rssi_smooth) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_get_real_rssi) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_round) \
    SORT(*libwifi_drv_ws53.a:)(.text.round_neg) \
    SORT(*libwifi_drv_ws53.a:)(.text.round_pos) \
    SORT(*liblwip_tcm.a:)(.text.ip4_addr_isbroadcast_u32) \
    SORT(*libwifi_driver_tcm.a:)(.text.skb_reset_tail_pointer) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_header_const) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_hdr_get_from_ds) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_get_bss_type) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_get_rx_cb_mac_hdr) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_seqno_lt) \
    SORT(*libwifi_drv_ws53.a:)(.text.osal___list_del) \
    SORT(*libwifi_drv_ws53.a:)(.text.osal___list_add) \
    SORT(*libwifi_drv_ws53.a:)(.text.skb_peek) \
    SORT(*libwifi_drv_ws53.a:)(.text.wlan_wme_tid_to_ac) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_put) \
    SORT(*libwifi_drv_ws53.a:)(.text.skb_tail_pointer) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_get_len) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_push) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_remove_header) \
    SORT(*libwifi_drv_ws53.a:)(.text._skb_queue_head_init) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_add_to_list_tail) \
    SORT(*libwifi_driver_tcm.a:)(.text.__skb_queue_tail) \
    SORT(*libwifi_driver_tcm.a:)(.text._skb_queue_before) \
    SORT(*libwifi_drv_ws53.a:)(.text._skb_insert) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_get_ctrl) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_get_algorithm_main) \
    SORT(*libwifi_drv_ws53.a:)(.text.osal_get_timeofday_us) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_free) \
    SORT(*liblwip_tcm.a:)(.text.LOS_AtomicDecRet) \
    SORT(*liblwip_tcm.a:)(.text.ArchAtomicDecRet) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_add_header) \
    SORT(*libwifi_drv_ws53.a:)(.text.ether_is_multicast) \
    SORT(*liblwip.a:)(.text.set_timer_state) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_get_vap_info) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_vap_get_feature_ptr) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_vap_get_curren_bw_state) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_hdr_get_to_ds) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_ip_hdr_len) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket_unconn_nouse) \
    SORT(*liblwip_tcm.a:)(.text.lwip_wait_mbox_empty_func) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_rx_data_const) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_get_transmit_addr) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_rx_get_da) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_list_head_init) \
    SORT(*libwifi_driver_tcm.a:)(.text.skb_queue_head_init) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_get_appointed_netbuf) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_get_tid_value) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_btcoex_get_user_info) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_get_seq_num) \
    SORT(*liblwip_tcm.a:)(.text.sys_now) \
    SORT(*liblwip.a:)(.text.ArchAtomicRead) \
    SORT(*liblwip_tcm.a:)(.text.lwip_standard_chksum) \
    SORT(*liblwip_tcm.a:)(.text.sys_mutex_unlock) \
    SORT(*liblwip_tcm.a:)(.text.sys_mutex_lock) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_wakeup_dev) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_wakeup_check) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_psm_sta_incr_activity_cnt) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_is_tx_force) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_get_wlan_frame_subtype) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_headroom) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_wait_wakeup) \
    SORT(*libwifi_drv_ws53.a:)(.text.OSAL_INIT_LIST_HEAD) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_atomic_set) \
    SORT(*libwifi_driver_tcm.a:)(.text.osal_list_add_tail) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_cnt_inc) \
    SORT(*libwifi_driver_tcm.a:)(.text.osal_list_del) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_cnt_dec) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_que_handle) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_exec_callback) \
    SORT(*libwifi_drv_ws53.a:)(.text.skb_is_nonlinear) \
    SORT(*libwifi_driver_tcm.a:)(.text.skb_reserve) \
    SORT(*libwifi_drv_ws53.a:)(.text.is_legacy_sta) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_clen) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_alloc) \
    SORT(*liblwip_tcm.a:)(.text.mem_pbuf_check_ram_size_return) \
    SORT(*liblwip_tcm.a:)(.text.LOS_AtomicRead) \
    SORT(*liblwip_tcm.a:)(.text.LOS_AtomicAdd) \
    SORT(*liblwip_tcm.a:)(.text.ArchAtomicAdd) \
    SORT(*liblwip_tcm.a:)(.text.mem_malloc) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_init_alloced_pbuf) \
    SORT(*liblwip_tcm.a:)(.text.LOS_AtomicSet) \
    SORT(*liblwip_tcm.a:)(.text.ArchAtomicSet) \
    SORT(*liblwip_tcm.a:)(.text.mem_free) \
    SORT(*liblwip_tcm.a:)(.text.LOS_AtomicSub) \
    SORT(*liblwip_tcm.a:)(.text.ArchAtomicSub) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_mem_free_etc) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_mem_alloc_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.is_sta) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_payload_const) \
    SORT(*libwifi_auto_adjust_freq.a:)(.text.hmac_auto_freq_pps_count) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_add_timer) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_add_in_order) \
    SORT(*liblwip_tcm.a:)(.text.done_socket) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket_unconn) \
    SORT(*liblwip_tcm.a:)(.text.sock_inc_used) \
    SORT(*liblwip_tcm.a:)(.text.get_socket) \
    SORT(*liblwip_tcm.a:)(.text.event_callback) \
    SORT(*liblwip_tcm.a:)(.text.LOS_ListEmpty) \
    SORT(*liblwip_tcm.a:)(.text.ip_addr_cmp) \
    SORT(*liblwip.a:)(.text.tcp_input_delayed_close) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_host_get_gla_switch_enable) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_is_registered) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_delist) \
    SORT(*libwifi_driver_tcm.a:)(.text._skb_dequeue) \
    SORT(*libwifi_drv_ws53.a:)(.text.skb_unlink) \
    SORT(*liblwip_tcm.a:)(.text.sys_arch_mbox_fetch_ext) \
    SORT(*liblwip_tcm.a:)(.text.sys_arch_mbox_handler_timeouts) \
    SORT(*libwifi_drv_ws53.a:)(.text.osal_get_time_stamp_ts) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_compare_mac_addr) \
    SORT(*libwifi_alg_txbf.a:)(.text.alg_txbf_get_assoc_user_num) \
    SORT(*liblwip.a:)(.text.sys_timeout_set_wake_time) \
    SORT(*liblwip.a:)(.text.sys_timeout_get_wake_time) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_rx_wifi_post_action_function) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_linkloss_clean) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_hal_blinkloss_clean) \
    SORT(*libwifi_alg_cca_opt.a:)(.text.alg_cca_opt_rx_update_rssi) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_high_throughput_option_implemented) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_tailroom) \
    SORT(*libwifi_driver_tcm.a:)(.text.skb_tailroom) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_set_thr) \
    SORT(*libwifi_driver_tcm.a:)(.text.hal_config_rssi_for_loss) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_rf_get_subband_idx_for_loss) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_frame_get_subtype_value) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_rx_process_ect) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_release_rx_prot) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_rx_rate_process_check) \
    SORT(*libwifi_driver_tcm.a:)(.text.osal_get_time_stamp_ms) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_alg_rx_notify) \
    SORT(*libwifi_alg_cca_opt.a:)(.text.alg_cca_opt_rx_data_process) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_rx_process) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_record_rx_rssi_info) \
    SORT(*libwifi_alg_txbf.a:)(.text.alg_txbf_rx_data_process) \
    SORT(*libwifi_alg_txbf.a:)(.text.alg_txbf_get_rate_from_rssi) \
    SORT(*libwifi_alg_txbf.a:)(.text.alg_txbf_report_set_pow_rate) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_rx_header_len) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_vap_bw_fsm_verify) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_get_buf_num) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_peek) \
    SORT(*libwifi_frag.a:)(.text.hmac_defrag_start) \
    SORT(*libwifi_frag.a:)(.text.hmac_frag_get_user_info) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_rx_get_sa) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_11i_ether_type_filter_etc) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_eth_type_trans) \
    SORT(*libwifi_driver_tcm.a:)(.text.host_print_rx_timestamp) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netif_rx_ni) \
    SORT(*libwifi_driver_tcm.a:)(.text.hwal_netbuf_2_pbuf) \
    SORT(*libwifi_driver_tcm.a:)(.text.hwal_skb_convert_2_pbuf) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_rx_transmit_ap) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_get_bssid) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_get_address2) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_get_user_by_addr_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_find_user_by_macaddr_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_is_grp_addr) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_ba_update_rx_bitmap) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_ba_clear_rx_bitmap) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_lower_rate_process) \
    SORT(*libwifi_btcoex.a:)(.text.mac_btcoex_check_valid_sta) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_rx_seqno_lt) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_ba_addto_rx_bitmap) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_free) \
    SORT(*libwifi_drv_ws53.a:)(.text.frw_init_timer) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_create_timer) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_create_timer_inner) \
    SORT(*liblwip_tcm.a:)(.text.memp_free) \
    SORT(*liblwip_tcm.a:)(.text.do_memp_free_pool) \
    SORT(*liblwip_tcm.a:)(.text.memp_malloc) \
    SORT(*liblwip_tcm.a:)(.text.do_memp_malloc_pool) \
    SORT(*liblwip_tcm.a:)(.text.sys_mbox_trypost) \
    SORT(*libwifi_driver_tcm.a:)(.text.hcc_service_init_hdr) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_ref) \
    SORT(*liblwip_tcm.a:)(.text.LOS_AtomicInc) \
    SORT(*liblwip_tcm.a:)(.text.ArchAtomicInc) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_unshare) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_reserve_header) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_arp_fail_delba_process) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_arp_fail_delba_process_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.wlan_wme_ac_to_tid) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_filter_security) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_rsnaactivated) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_low_half_byte) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_high_half_byte) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_qap_edca_table_mandatory) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_trim) \
    SORT(*libwifi_driver_tcm.a:)(.text._skb_trim) \
    SORT(*libwifi_driver_tcm.a:)(.text.skb_set_tail_pointer) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_set_cb_header_len) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_set_frame_ctrl) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_hdr_set_frame_control) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_hdr_set_from_ds) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_hdr_set_to_ds) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_station_id) \
    SORT(*libwifi_frag.a:)(.text.hmac_frag_start) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_tx_enable_in_roaming) \
    SORT(*libwifi_uapsd_ap.a:)(.text.hmac_uapsd_enqueue_proc) \
    SORT(*libwifi_uapsd_ap.a:)(.text.hmac_uapsd_tx_need_enqueue) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_process_tid_queue) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_need_enqueue_tid) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_arp_offload_tx_hookfn) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_arp_offload_process_tx_frame) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_get_is_data_frame) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_get_wlan_frame_type) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_hmac_update_data_type_al_tx) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_hmac_mac_head_exchange) \
    SORT(*libwifi_driver_tcm.a:)(.text.host_print_tx_timestamp) \
    SORT(*libwifi_driver_tcm.a:)(.text.wlan_tos_to_tid) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_mib_get_CfgAmpduTxAtive) \
    SORT(*libwifi_tx_amsdu.a:)(.text.mac_mib_get_CfgAmsduTxAtive) \
    SORT(*libwifi_tx_amsdu.a:)(.text.mac_mib_get_AmsduAggregateAtive) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_is_icmp_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_user_xht_support) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_set_snap) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_send_msg_na) \
    SORT(*liblwip.a:)(.text.get_lowpowper_mod) \
    SORT(*liblwip.a:)(.text.sys_timeout_waiting_long) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_tcp_pbuf_flags) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_data_tcp) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_data) \
    SORT(*liblwip_tcm.a:)(.text.netconn_err) \
    SORT(*liblwip_tcm.a:)(.text.tcp_update_rcv_ann_wnd) \
    SORT(*liblwip.a:)(.text.tcp_output) \
    SORT(*libwifi_hal_tcm.a:)(.text.hal_reg_rw_by_msg) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_wifi_pm_get_host_allow_sleep) \
    SORT(*libwifi_csa.a:)(.text.hmac_csa_get_vap_info) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_round_up) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_frw_check_param) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_asyn_host_post_msg) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_host_post_msg_async) \
    SORT(*liblwip_tcm.a:)(.text.ethernet_output) \
    SORT(*liblwip_tcm.a:)(.text.driverif_output) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if_opt) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if_opt_src) \
    SORT(*liblwip_tcm.a:)(.text.etharp_output) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_set_netbuf_next) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_opt_tx_process) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_mac_frame_check) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_tx_vip_frame) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_tx_vip_frame_ect) \
    SORT(*liblwip.a:)(.text.tcp_output_segment_busy) \
    SORT(*liblwip_tcm.a:)(.text.etharp_output_to_arp_index) \
    SORT(*liblwip.a:)(.text.tcp_output_segment) \
    SORT(*liblwip_tcm.a:)(.text.ip_chksum_pseudo_partial) \
    SORT(*liblwip_tcm.a:)(.text.inet_chksum_pseudo_partial) \
    SORT(*liblwip_tcm.a:)(.text.inet_cksum_pseudo_partial_base) \
    SORT(*liblwip.a:)(.text.tcp_create_segment) \
    SORT(*liblwip.a:)(.text.tcp_update_sack_fields_for_new_seg) \
    SORT(*liblwip_tcm.a:)(.text.tcp_seg_free) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_inc_triffic_num) \
    SORT(*liblwip.a:)(.text.tcp_pbuf_prealloc) \
    SORT(*liblwip_tcm.a:)(.text.lwip_chksum_copy) \
    SORT(*liblwip.a:)(.text.tcp_seg_add_chksum) \
    SORT(*liblwip.a:)(.text.tcp_free_acked_segments) \
    SORT(*liblwip.a:)(.text.get_sleep_time) \
    SORT(*liblwip_tcm.a:)(.text.tcp_fast_tmr_tick) \
    SORT(*liblwip_tcm.a:)(.text.tcp_slow_tmr_tick) \
    SORT(*liblwip_tcm.a:)(.text.tcp_set_timer_tick_by_driver_status) \
    SORT(*liblwip_tcm.a:)(.text.ip_reass_tmr_tick) \
    SORT(*liblwip_tcm.a:)(.text.etharp_tmr_tick) \
    SORT(*liblwip.a:)(.text.dhcp_fine_tmr_tick) \
    SORT(*liblwip.a:)(.text.dhcp_coarse_tmr_tick) \
    SORT(*liblwip.a:)(.text.dhcp_netif_coarse_tmr_tick) \
    SORT(*liblwip.a:)(.text.igmp_tmr_tick) \
    SORT(*liblwip.a:)(.text.dns_tmr_tick) \
    SORT(*liblwip.a:)(.text.nd6_tmr_tick) \
    SORT(*liblwip.a:)(.text.ip6_reass_tmr_tick) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_get_user_priv_stru) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_get_dev_info) \
    SORT(*libwifi_drv_ws53.a:)(.text.get_current_linkloss_cnt) \
    SORT(*liblwip_tcm.a:)(.text.driverif_input) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_input) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_inpkt) \
    SORT(*liblwip_tcm.a:)(.text.ethernet_input_list) \
    SORT(*liblwip_tcm.a:)(.text.ethernet_input) \
    SORT(*liblwip_tcm.a:)(.text.etharp_update_arp_entry) \
    SORT(*liblwip_tcm.a:)(.text.etharp_find_entry) \
    SORT(*liblwip_tcm.a:)(.text.etharp_ip_input) \
    SORT(*liblwip_tcm.a:)(.text.ip4_input) \
    SORT(*liblwip_tcm.a:)(.text.inet_chksum) \
    SORT(*liblwip_tcm.a:)(.text.ip_addr_isany) \
    SORT(*liblwip_tcm.a:)(.text.netconn_apimsg) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_send_msg_wait_sem) \
    SORT(*liblwip_tcm.a:)(.text.ip_addr_copy_fun) \
    SORT(*liblwip_tcm.a:)(.text.lwip_sock_unlock) \
    SORT(*liblwip_tcm.a:)(.text.recvfrom) \
    SORT(*liblwip_tcm.a:)(.text.lwip_sock_lock) \
    SORT(*liblwip_tcm.a:)(.text.lwip_recvfrom_udp_raw) \
    SORT(*liblwip_tcm.a:)(.text.netconn_recv_udp_raw_netbuf_flags) \
    SORT(*liblwip_tcm.a:)(.text.ip4_input_accept) \
    SORT(*liblwip_tcm.a:)(.text.raw_input) \
    SORT(*liblwip_tcm.a:)(.text.udp_input) \
    SORT(*liblwip_tcm.a:)(.text.udp_input_local_match) \
    SORT(*liblwip_tcm.a:)(.text.recv_udp) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_copy_partial) \
    SORT(*liblwip_tcm.a:)(.text.netbuf_delete) \
    SORT(*liblwip_tcm.a:)(.text.ip_route_pcb) \
    SORT(*liblwip_tcm.a:)(.text.ip4_route) \
    SORT(*liblwip_tcm.a:)(.text.send) \
    SORT(*liblwip_tcm.a:)(.text.sendto) \
    SORT(*liblwip_tcm.a:)(.text.netbuf_alloc) \
    SORT(*liblwip_tcm.a:)(.text.netconn_send) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_send) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto_chksum) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto_if_chksum) \
    SORT(*liblwip_tcm.a:)(.text.udp_sendto_if_src_chksum) \
    SORT(*liblwip_tcm.a:)(.text.ip4_output_if_src) \
    SORT(*liblwip_tcm.a:)(.text.netbuf_free) \
    SORT(*liblwip.a:)(.text.err_to_errno) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_timeout_proc_event_etc) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_timeout_proc) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_timeout_proc_run) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_timeout_proc_restart_timer) \
    SORT(*liblwip.a:)(.text.tcp_input) \
    SORT(*liblwip.a:)(.text.tcp_parseopt) \
    SORT(*liblwip.a:)(.text.tcp_process) \
    SORT(*liblwip.a:)(.text.tcp_receive) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_is_err_msg) \
    SORT(*liblwip_tcm.a:)(.text.recv_tcp) \
    SORT(*liblwip.a:)(.text.tcp_update_sack_for_received_ooseq_segs) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_split_64k) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_user_get_tid_by_num) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_schedule_get_mpdu_num_left) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_queue_mpdu) \
    SORT(*libwifi_csa.a:)(.text.hmac_sta_csa_fsm_get_current_state) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_tid_lock_bh) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_tid_unlock_bh) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_alg_tx_schedule_timer_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_sch_timer_restart_handle) \
    SORT(*libwifi_csa.a:)(.text.hmac_sta_csa_fsm_is_waiting) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_mode_param_check) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_find_ie_etc) \
    SORT(*liblwip.a:)(.text.tcp_route) \
    SORT(*liblwip.a:)(.text.tcp_get_sack_block_count_for_send) \
    SORT(*liblwip.a:)(.text.tcp_build_sack_option) \
    SORT(*liblwip.a:)(.text.tcp_send_empty_ack) \
    SORT(*liblwip.a:)(.text.tcp_output_alloc_header) \
    SORT(*liblwip.a:)(.text.tcp_output_alloc_header_common) \
    SORT(*liblwip.a:)(.text.tcp_output_fill_options) \
    SORT(*liblwip.a:)(.text.tcp_output_control_segment) \
    SORT(*liblwip_tcm.a:)(.text.ip_chksum_pseudo) \
    SORT(*liblwip_tcm.a:)(.text.inet_chksum_pseudo) \
    SORT(*liblwip_tcm.a:)(.text.inet_cksum_pseudo_base) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_beacon_period) \
    SORT(*libwifi_driver_tcm.a:)(.text._dev_alloc_skb) \
    SORT(*libwifi_driver_tcm.a:)(.text.dev_kfree_skb) \
    SORT(*libwifi_driver_tcm.a:)(.text.kfree_skb) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_tid_update_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_update_txtid_dlist) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_get_tid_priv_stru) \
    SORT(*libwifi_hal_tcm.a:)(.text.hal_reg_read) \
    SORT(*libwifi_hal_tcm.a:)(.text.hal_reg_write) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_realloc) \
    SORT(*liblwip_tcm.a:)(.text.mem_trim) \
    SORT(*liblwip_tcm.a:)(.text.sent_tcp) \
    SORT(*liblwip_tcm.a:)(.text.sys_sem_new) \
    SORT(*liblwip_tcm.a:)(.text.sys_sem_free) \
    SORT(*liblwip_tcm.a:)(.text.sys_sem_signal) \
    SORT(*liblwip_tcm.a:)(.text.sys_arch_sem_wait) \
    SORT(*liblwip_tcm.a:)(.text.tcpip_thread_handle_msg) \
    SORT(*liblwip.a:)(.text.tcpip_timeouts_mbox_fetch) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tid_tx_enqueue_wait_condition) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_netbuf_rx_data) \
    SORT(*libwifi_tx_amsdu.a:)(.text.oal_netbuf_reserve) \
    SORT(*libwifi_frag.a:)(.text.oal_netbuf_copy_queue_mapping) \
    SORT(*libwifi_frag.a:)(.text.skb_copy_queue_mapping) \
    SORT(*liblwip_tcm.a:)(.text.tcp_set_timer_tick_by_persist) \
    SORT(*liblwip_tcm.a:)(.text.tcp_set_timer_tick_by_keepalive) \
    SORT(*liblwip_tcm.a:)(.text.tcp_set_timer_tick_by_tcp_state) \
    SORT(*liblwip_tcm.a:)(.text.poll_tcp_needed) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tid_tx_queue_enqueue) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_tid_buffer_len_increase) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_tid_tx_enqueue_update) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_dequeue_first_mpdu) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_tid_buffer_len_decrease) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_tid_tx_dequeue_update) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_wdg_timeout) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_sleep_cmd) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_sleep_check) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_app_allow_sleep) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sleep_check_debug_cnt_incr) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_feed_wdg) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_timeout_fn_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_timeout_get_param) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_device_calc_up_vap_num_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_check_up_vap_ps_enable) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_memcmp) \
    SORT(*libwifi_drv_ws53.a:)(.text.get_current_linkloss_int_threshold) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_is_dbac_running) \
    SORT(*liblwip.a:)(.text.check_timeout) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_pm_queue_empty_check) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_psm_sta_is_activity_cnt_zero) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_psm_sta_reset_activity_cnt) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_alg_rf_online_cali_ctx) \
    SORT(*liblwip_tcm.a:)(.text.lwip_recv_tcp) \
    SORT(*liblwip_tcm.a:)(.text.lwip_recv_tcp_from) \
    SORT(*liblwip_tcm.a:)(.text.netconn_tcp_recvd) \
    SORT(*liblwip_tcm.a:)(.text.netconn_tcp_recvd_msg) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_recv) \
    SORT(*liblwip_tcm.a:)(.text.tcp_recved) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_he_option_implemented) \
    SORT(*libwifi_drv_ws53.a:)(.text.get_current_linkloss_threshold) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_get_wlan_dev_state) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_device_find_all_up_vap) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_bit_get_num_four_byte) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_bit_find_first_bit_four_byte) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_get_hal_vap) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_get_hal_vap) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_get_vap_internal) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_make_word16) \
    SORT(*liblwip_tcm.a:)(.text.netconn_write_partly) \
    SORT(*liblwip_tcm.a:)(.text.netconn_write_vectors_partly) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_write) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_writemore) \
    SORT(*liblwip.a:)(.text.tcp_write) \
    SORT(*liblwip.a:)(.text.tcp_write_checks) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_set_bf_rate) \
    SORT(*libwifi_alg_txbf.a:)(.text.hmac_bfee_report_pow_adjust_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_tpc_update_bfee_report_pow) \
    SORT(*libwifi_drv_ws53.a:)(.text.hal_set_tpc_bf_pow) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_set_tpc_bf_pow) \
    SORT(*libwifi_fe.a:)(.text.fe_tpc_rate_pow_get_rate_tpc_code) \
    SORT(*libwifi_fe.a:)(.text.fe_tpc_rate_pow_get_rate_idx) \
    SORT(*libwifi_fe.a:)(.text.fe_tpc_rate_pow_get_pow_idx_offset) \
    SORT(*libwifi_fe.a:)(.text.fe_tpc_get_rate_pow_table_2g) \
    SORT(*libwifi_alg_txbf.a:)(.text.alg_txbf_print_gla_info) \
    SORT(*libwifi_fe.a:)(.text.cali_get_dbb_shadow_bounds) \
    SORT(*libwifi_drv_ws53.a:)(.text.get_abs) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_schedule_process) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_refresh_tx_bitmap) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_alg_tx_schedule_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_tx_tid_sch) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_wmm_sch) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_sch_bcast_txtid) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_target_user) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_is_vap_paused) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_is_pause_tx_bitmap) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_update_sch_result) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_update_sch_result_in_certain_circumstances) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_user_get_ps_mode) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tx_schedule_tid) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tid_tx_queue_remove) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_tid_tx_queue_fetch) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_alg_user_info_update_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_update_target_user) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_mgmt_event_adapt) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_cut_process_mgmt_ctrl_event) \
    SORT(*libwifi_csa.a:)(.text.hmac_csa_sta_rx_mgmt) \
    SORT(*libwifi_csa.a:)(.text.hmac_csa_sta_rx_beacon_probe_rsp) \
    SORT(*libwifi_csa.a:)(.text.hmac_chan_update_csw_info) \
    SORT(*libwifi_csa.a:)(.text.mac_mib_get_spectrum_management_implemented) \
    SORT(*libwifi_csa.a:)(.text.hmac_ie_proc_csa_bw_ie) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_scan_check_bss_type) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_report_mgmt_frame) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_is_mgmt_report_enable) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_process_mgmt_ctrl) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_mgmt_ctrl_classify) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_mgmt_update_user_rssi) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_process_mgmt) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_rx_mgmt_notify) \
    SORT(*libwifi_alg_cca_opt.a:)(.text.alg_cca_opt_rx_mgmt_process) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_rx_mgmt_process) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_opt_rx_mgmt_process) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_opt_get_vap_num) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_para_opt) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_txop_opt) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_update_txop) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_stop_txop_opt) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_opt_sta) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_get_address3) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_sta_up_beacon_mgmt) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_multi_bssid_implement) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_linkloss_channel_clean) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ie_get_chan_num_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_get_band_by_channel_num) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_is_channel_num_valid_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_get_channel_idx_from_num_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_is_channel_idx_valid_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_get_channel_idx_rc_info_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_rx_beacon_check) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_rx_beacon_check_change) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_update_slottime) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_mgmt_obss_scan_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_mgmt_need_obss_scan) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_2040_bss_coexistence_management_support) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_get_peer_obss_scan_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_update_ht_params) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_proc_ht_opern_ie_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_user_get_ht_hdl_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_user_set_ht_hdl_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_set_peer_obss_scan_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_update_vht_params) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_vht_option_implemented) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_update_he_oper_params) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_process_erp_ie) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_update_protection_mode) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_protection_autoprot_is_enabled_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_vap_get_user_protection_mode_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_set_protection_mode) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_rx_beacon_check_bw) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_vap_bw_fsm_beacon_avail) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_check_ap_usr_opern_bandwidth) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_vap_get_cap_bw) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_forty_mhz_operation_implemented) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_edca_is_changed) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_find_vendor_ie_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_is_wmm_ie_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_filter_mgmt_comm_state) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_11w_rx_filter) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_ctype_to_cipher_suite) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_sta_mgmt) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_rx_filter_mgmt_scan_state) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_tbtt_event_sta) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_get_nv_disable_linkloss) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_up_misc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_tbtt_prior_linkloss_handler) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_linkloss_update_mode) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_hal_get_btstatus_bton) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_btcoex_get_bt_run) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_linkloss_update_threshold) \
    SORT(*libwifi_drv_ws53.a:)(.text.mac_mib_get_powermanagementmode) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_linkloss_incr) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_linkloss_ignor) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_linkloss_send_probe_req) \
    SORT(*libwifi_drv_ws53.a:)(.text.get_current_linkloss_send_probereq_threshold) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_is_linkloss) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_linkloss_occupied_process) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_anti_intf_tbtt_handler) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_tbtt_isr) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_send_all_fake_queue) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_send_fake_queue) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_stop_timer) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_set_agc_unlock) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_alloc_hcc_cfg_data) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_free_hcc_cfg_data) \
    SORT(*libwifi_fe.a:)(.text.cali_get_upc_idx_range) \
    SORT(*libwifi_fe.a:)(.text.cali_get_pwr_lvl_by_ppa_idx) \
    SORT(*libwifi_fe.a:)(.text.online_cali_trans_to_next_state) \
    SORT(*libwifi_fe.a:)(.text.online_rf_cali_fsm_trans_to_state) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_fsm_trans_to_state) \
    SORT(*libwifi_fe.a:)(.text.online_cali_mask_is_enable) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_txpow_ctrl) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_gp_get_ppa_lut_lock_state) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_set_dyn_unlock_th_reg) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_negtive_det_alg_off_set_min_thr) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_set_agc_unlock_min_th) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_alloc_hcc_buf) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_rx_wifi_cfg_function) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_hmac_rcv_cfg) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_adapt_convert) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_host_rcv_msg_callback) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_get_thread_que) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_find_msg_node) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_fsm_event_dispatch) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_destroy_timer) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_destroy_timer_inner) \
    SORT(*libwifi_fe.a:)(.text.online_cali_next_state_delay_timeout_handler) \
    SORT(*libwifi_fe.a:)(.text.hal_set_dyn_tx_power_cali_dyn_tx_power_cali) \
    SORT(*libwifi_fe.a:)(.text.online_rf_cali_handle_event) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_pow_event) \
    SORT(*libwifi_fe.a:)(.text.online_cali_go_to_next_state_after_delay) \
    SORT(*liblwip.a:)(.text.timeout_handler) \
    SORT(*liblwip.a:)(.text.lowpower_cycle_tmr) \
    SORT(*libwifi_drv_ws53.a:)(.text.osal_dlist_delete_entry) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_host_rcv_msg_async) \
    SORT(*libwifi_fe.a:)(.text.online_cali_state_is_in_pwr) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_sch_timer_handle) \
    SORT(*libwifi_fe.a:)(.text.online_cali_is_dsss) \
    SORT(*libwifi_fe.a:)(.text.fe_custom_get_chip_max_power) \
    SORT(*libwifi_fe.a:)(.text.online_cali_calc_gain_code) \
    SORT(*libwifi_fe.a:)(.text.online_cali_pow_right_shift_floor) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_gp_set_ppa_lut_lock_state) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_phy_set_single_ppa_lut) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_send_msg_to_device) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_send_cfg_to_device) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_send_msg_adapt) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_send_msg_adapt_by_hcc) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_adapt_init) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_tx_wifi_cfg_by_hcc) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_free_hcc_buf) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_dyn_unlock_start_timer_handler) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_dyn_unlock_off_timer_handler) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_is_all_vap_mode_sta) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_adjust_and_set_thr) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_get_device_bw_mode) \
    SORT(*libwifi_fe.a:)(.text.fe_calc_20log) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_thread_wait_cond) \
    SORT(*libwifi_fe.a:)(.text.online_set_cali_id) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_phy_config_online_pow) \
    SORT(*libwifi_fe.a:)(.text.hal_set_tx_power_accum_delay_power_accum_delay) \
    SORT(*libwifi_fe.a:)(.text.hal_set_cali_new_add_reg_cfg_fb_pwr_calc_prd) \
    SORT(*libwifi_fe.a:)(.text.online_cali_device_rf_get_rf_idx) \
    SORT(*libwifi_fe.a:)(.text.online_cali_iq_is_need_start) \
    SORT(*libwifi_fe.a:)(.text.online_cali_search_dbb_shadow_index) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_remove_frame_from_reorder_q) \
    SORT(*liblwip_tcm.a:)(.text.tcp_slowtmr) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_get_rssi_bk_val) \
    SORT(*libwifi_fe.a:)(.text.online_cali_send_intvl) \
    SORT(*libwifi_fe.a:)(.text.online_cali_pow_tx_notify) \
    SORT(*libwifi_fe.a:)(.text.online_cali_is_need_flush_pdet_en) \
    SORT(*libwifi_fe.a:)(.text.online_cali_init_per_frame_timer) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_complete_dyn_process) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_pow_handler) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_pow_pre_check) \
    SORT(*libwifi_fe.a:)(.text.online_cali_init_flush_pow_code) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_pow_cali_param) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_target_tx_power) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_pwr_dist_table) \
    SORT(*libwifi_fe.a:)(.text.cali_get_pow_cal_gain_2g_table) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_cali_pwr_valid) \
    SORT(*libwifi_fe.a:)(.text.online_cali_pow_comp_entrance) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_pdet_check) \
    SORT(*libwifi_fe.a:)(.text.online_cali_flush_pow) \
    SORT(*libwifi_fe.a:)(.text.online_cali_record_union_by_tx_complete) \
    SORT(*libwifi_fe.a:)(.text.online_cali_check_pwr_not_need_calc) \
    SORT(*libwifi_fe.a:)(.text.online_cali_flush_get_pdet_para) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_pow_get_praw) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_pow_calc_praw) \
    SORT(*libwifi_fe.a:)(.text.online_cali_flush_dyn_cali_pwr) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_curve_pow) \
    SORT(*libwifi_fe.a:)(.text.fe_custom_get_power_curve) \
    SORT(*libwifi_fe.a:)(.text.fe_custom_get_curve_factor) \
    SORT(*libwifi_fe.a:)(.text.fe_custom_check_curve) \
    SORT(*libwifi_fe.a:)(.text.fe_custom_calc_curve_pow) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_pow_comp) \
    SORT(*libwifi_fe.a:)(.text.online_cali_temp_comp) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_rf_he_er_su_comp) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_adjust_pwr) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_adjust_pwr_extend) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_dyn_upc_unit_range) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_curr_upc_code) \
    SORT(*libwifi_fe.a:)(.text.online_cali_same_channel_index) \
    SORT(*libwifi_fe.a:)(.text.cali_wait_ppa_lut_free) \
    SORT(*libwifi_fe.a:)(.text.hal_set_rf_ppa_code_lut0_cfg_rf_ppa_code_lut1) \
    SORT(*libwifi_fe.a:)(.text.online_cali_pow_complete_handler) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_cus_dyn_cali_intvl) \
    SORT(*libwifi_fe.a:)(.text.online_cali_pow_cali_set_dscr_intvl) \
    SORT(*libwifi_fe.a:)(.text.online_cali_intvl_timeout_handler) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_atomic_read) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_copy_rsp) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_host_post_sync) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_host_post_sync_msg) \
    SORT(*libwifi_drv_ws53.a:)(.text.frw_msg_init) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_check_hcc_deadlock) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_send_cfg_to_device_sync) \
    SORT(*libwifi_fe.a:)(.text.online_cali_idle_state_exit) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_pow_state_entry) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_pow_state_exit) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_phy_recover_online_pow) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_iq_state_entry) \
    SORT(*libwifi_fe.a:)(.text.online_cali_rx_iq_state_entry) \
    SORT(*libwifi_fe.a:)(.text.online_cali_idle_state_entry) \
    SORT(*libwifi_fe.a:)(.text.online_cali_init_adjust_dbb_scaling) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_cfg_dbb_scale_shadow) \
    SORT(*libwifi_fe.a:)(.text.hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_2) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.hmac_get_pri_custom) \
    SORT(*libwifi_fe.a:)(.text.online_cali_dyn_adjust_upc_dbb) \
    SORT(*libwifi_fe.a:)(.text.online_cali_get_digital_scaling_reg) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_get_dbb_scale_shadow) \
    SORT(*libwifi_fe.a:)(.text.hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_2) \
    SORT(*libwifi_fe.a:)(.text.online_cali_calc_upc_adj) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_pwr_invalid_process) \
    SORT(*libwifi_fe.a:)(.text.online_cali_set_curr_upc_code) \
    SORT(*libwifi_fe.a:)(.text.online_cali_cfg_single_upc_reg) \
    SORT(*libwifi_fe.a:)(.text.online_cali_set_phy_upc_code) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_get_duty_cyc_ratio) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intfmode_get_statemode) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_scan_get_duty_cyc_ratio) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_stat_timer_log) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_schedule_get_user_tid_info) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_timer_hander) \
    SORT(*liblwip_tcm.a:)(.text.etharp_tmr) \
    SORT(*liblwip_tcm.a:)(.text.etharp_gratuitous_retransmit) \
    SORT(*liblwip_tcm.a:)(.text.tcp_fasttmr) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_tbtt_event_handler) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_util_notifier_notify) \
    SORT(*libwifi_csa.a:)(.text.hmac_csa_sta_tbtt_event) \
    SORT(*libwifi_csa.a:)(.text.hmac_csa_ap_tbtt_event) \
    SORT(*libwifi_csa.a:)(.text.hmac_csa_ap_get_vap_info) \
    SORT(*libwifi_drv_ws53.a:)(.text.is_ap) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_pm_sta_wakeup_ipc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_align_tbtt_timer) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_restart_timer_inner) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_restart_inner) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_cur_temp_get) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.hal_read_max_temperature) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_read_max_temperature) \
    SORT(*liblwip.a:)(.text.nd6_tmr) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_duty_cyc_smth) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_rx_seqno_leq) \
    SORT(*libwifi_drv_ws53.a:)(.text.hal_pm_vote2platform) \
    SORT(*libwifi_hal_tcm.a:)(.text.hh503_pm_vote2platform) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_rssi_stat_timer_handler) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_neg_det_of_tx_time) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_refresh_vap_stat_info) \
    SORT(*libwifi_drv_ws53.a:)(.text.is_p2p_dev) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_refresh_user_stat_info) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_get_user_ar_info) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_probe_direct_confirm) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_set_reg_val) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_set_rssi_th_reg) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_set_non_dir_rssi) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_clean_dmac_info) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.hmac_anti_intf_get_tx_comp_info) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_btcoex_statistics) \
    SORT(*libwifi_hal_tcm.a:)(.text.hal_gp_get_btcoex_abort_time) \
    SORT(*libwifi_drv_ws53.a:)(.text.hal_set_sync_err_counter_clear) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_set_sync_err_counter_clear) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_get_notify_if) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_bcn_no_frm_event_hander) \
    SORT(*libwifi_fe.a:)(.text.online_set_rf_cali_tx_pow_accum_wait_para) \
    SORT(*libwifi_fe.a:)(.text.online_cali_update_tpc_lut) \
    SORT(*libwifi_fe.a:)(.text.online_cali_calc_one_level_upc_code_lut) \
    SORT(*libwifi_fe.a:)(.text.cali_get_base_ppa_idx) \
    SORT(*libwifi_fe.a:)(.text.online_cali_calc_gain_by_code) \
    SORT(*libwifi_fe.a:)(.text.online_cali_pow_div_round) \
    SORT(*libwifi_fe.a:)(.text.online_cali_cfg_one_level_upc_reg) \
    SORT(*libwifi_fe.a:)(.text.cali_write_one_level_upc_reg) \
    SORT(*libwifi_fe.a:)(.text.hal_set_rf_ppa_code_lut0_cfg_rf_ppa_code_lut0) \
    SORT(*libwifi_fe.a:)(.text.hal_set_rf_ppa_code_lut1_cfg_rf_ppa_code_lut2) \
    SORT(*libwifi_fe.a:)(.text.hal_set_rf_ppa_code_lut1_cfg_rf_ppa_code_lut3) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_wait_ack_check) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_cmd_send) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_ipc_cmd_send) \
    SORT(*libwifi_hal_tcm.a:)(.text.hal_pm_set_host_pm_state) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_scan_channel_statistics_complete) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_anti_intf_get_tx_time) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_tx_time_notify_process) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_scan_ch_complete_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_scan_chn_cb) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_scan_result_debug) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_coch_identify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_coch_tx_time_duty_cyc) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_coch_intf_state) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_coch_intf_type_identify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_coch_intf_type_change_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_chan_result_info) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_stat_get_duty_cyc_ratio) \
    SORT(*libwifi_drv_ws53.a:)(.text.hal_get_sync_error_cnt) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_get_sync_error_cnt) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_get_intf_stat_info) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_fsm_post_event) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_intf_event) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_event_proc) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_idy_adjch_intf) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_adjch_intf_type_idy) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_is_adjintf_certify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_is_adjintf_strong) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_is_adjintf_no) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_cfg_intf_det_cca_chk_noise_notify) \
    SORT(*libwifi_alg_cca_opt.a:)(.text.alg_cca_opt_rx_chk_noise) \
    SORT(*libwifi_alg_cca_opt.a:)(.text.alg_cca_get_cca_opt) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_state_trans) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_intf_type_change_notify) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_update_intf_mode) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_update_duty_cycle) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_adjust_cycle) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_adjch_mode_check) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_scan_calcu_channel_ratio) \
    SORT(*liblwip.a:)(.text.igmp_lookfor_group) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_buffer_rx_frame) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_rx_free_netbuf_list_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_reorder_rx_data) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_seqno_bound_chk) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_timer_handler) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_adjch_stat_handler) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_prepare_adjch_param) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_get_vap) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_prepare_adjch_param_resume) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_set_cca_stat) \
    SORT(*libwifi_drv_ws53.a:)(.text.alg_intf_det_start_det_msg) \
    SORT(*libwifi_drv_ws53.a:)(.text.hal_enable_sync_error_counter) \
    SORT(*libwifi_hal_ws53.a:)(.text.hh503_enable_sync_error_counter) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_alg_cfg_intf_det_edca_notify) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_det_handler) \
    SORT(*libwifi_alg_edca_opt.a:)(.text.alg_edca_det_probe_stat_update) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_is_nd_etc) \
    SORT(*libwifi_fe.a:)(.text.fe_hal_phy_get_single_ppa_lut) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_get_arp_type_by_arphdr) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_set_weak_intf_rssi_th) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_restart_all_timer) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_wakeup_wait_ack) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_wakeup_done_callback) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_vap_linkloss_cnt_update) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_sleep_wait_ack) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_allow_sleep_callback) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_sleep_stage_proc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_sta_pm_stop_wdg) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_timer_stop_all_timer) \
    SORT(*liblwip.a:)(.text.sys_msleep) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_try_get_at) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_skip_const) \
    SORT(*liblwip.a:)(.text.dhcp_coarse_tmr) \
    SORT(*liblwip.a:)(.text.dhcp_netif_coarse_tmr) \
    SORT(*liblwip.a:)(.text.dhcp_idx_to_mac) \
    SORT(*liblwip.a:)(.text.dhcp_client_coarse_tmr) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_set_wlan_priority) \
    SORT(*liblwip_tcm.a:)(.text.tryget_socket_unconn_locked) \
    SORT(*liblwip_tcm.a:)(.text.sock_inc_used_locked) \
    SORT(*libwifi_fe.a:)(.text.online_cali_per_frame_timeout_handler) \
    SORT(*liblwip_tcm.a:)(.text.tcp_arg) \
    SORT(*liblwip_tcm.a:)(.text.tcp_recv) \
    SORT(*liblwip_tcm.a:)(.text.tcp_sent) \
    SORT(*liblwip_tcm.a:)(.text.tcp_poll) \
    SORT(*liblwip_tcm.a:)(.text.tcp_err) \
    SORT(*liblwip_tcm.a:)(.text.tcp_eff_send_mss_netif) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_det_duty_cyc_smth) \
    SORT(*libwifi_hal_ws53.a:)(.text.hal_set_btcoex_hw_priority_en) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_data_clear) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_clone) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_copy) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_copy_partial_pbuf) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_get_frame_from_reorder_q) \
    SORT(*libwifi_driver_tcm.a:)(.text.mac_get_is_qos_data) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_protect_tx_vip_frame) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_protect_frame) \
    SORT(*liblwip_tcm.a:)(.text.tcp_backlog_accepted) \
    SORT(*liblwip_tcm.a:)(.text.netconn_mark_mbox_invalid) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_close_internal) \
    SORT(*liblwip_tcm.a:)(.text.tcp_accept) \
    SORT(*liblwip_tcm.a:)(.text.tcp_remove_listener) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_fsm_post_event) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_safe_event) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_duty_cyc_get) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_stat_record) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_print_gla_info) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_get_will_state) \
    SORT(*liblwip_tcm.a:)(.text.setup_tcp) \
    SORT(*liblwip_tcm.a:)(.text.setsockopt) \
    SORT(*liblwip_tcm.a:)(.text.lwip_setsockopt_impl) \
    SORT(*liblwip.a:)(.text.tcp_timer_needed) \
    SORT(*liblwip_tcm.a:)(.text.lwip_select_inc_sockets_used_set) \
    SORT(*libwifi_drv_ws53.a:)(.text.wal_get_cmd_one_arg) \
    SORT(*liblwip_tcm.a:)(.text.lwip_selscan) \
    SORT(*liblwip.a:)(.text.ip6_input) \
    SORT(*liblwip_tcm.a:)(.text.pbuf_add_header_force) \
    SORT(*liblwip_tcm.a:)(.text.raw_input6) \
    SORT(*liblwip.a:)(.text.icmp6_input) \
    SORT(*liblwip_tcm.a:)(.text.ip6_chksum_pseudo) \
    SORT(*liblwip.a:)(.text.nd6_input) \
    SORT(*liblwip.a:)(.text.nd6_get_router) \
    SORT(*liblwip.a:)(.text.tcp_parseopt_sack_permitted) \
    SORT(*liblwip.a:)(.text.tcp_enqueue_flags) \
    SORT(*liblwip.a:)(.text.tcp_build_wnd_scale_option) \
    SORT(*liblwip.a:)(.text.tcp_build_sack_permitted_option) \
    SORT(*liblwip_tcm.a:)(.text.closesocket) \
    SORT(*liblwip_tcm.a:)(.text.lwip_socket_drop_registered_memberships) \
    SORT(*liblwip_tcm.a:)(.text.netconn_prepare_delete) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_delconn) \
    SORT(*liblwip_tcm.a:)(.text.tcp_close) \
    SORT(*liblwip_tcm.a:)(.text.tcp_close_shutdown) \
    SORT(*liblwip_tcm.a:)(.text.tcp_remove) \
    SORT(*liblwip_tcm.a:)(.text.free_socket) \
    SORT(*liblwip_tcm.a:)(.text.free_socket_locked) \
    SORT(*liblwip_tcm.a:)(.text.free_socket_free_elements) \
    SORT(*liblwip_tcm.a:)(.text.netconn_delete) \
    SORT(*liblwip_tcm.a:)(.text.netconn_free) \
    SORT(*liblwip_tcm.a:)(.text.netconn_drain) \
    SORT(*liblwip_tcm.a:)(.text.sys_mbox_free) \
    SORT(*liblwip_tcm.a:)(.text.lwip_sockopt_check_optlen_conn_pcb) \
    SORT(*liblwip_tcm.a:)(.text.sockaddr_to_ipaddr_port) \
    SORT(*liblwip.a:)(.text.lwip_rand_safe) \
    SORT(*liblwip_tcm.a:)(.text.poll_tcp) \
    SORT(*liblwip_tcm.a:)(.text.tcp_fr_segs_free) \
    SORT(*libwifi_fe.a:)(.text.hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_0) \
    SORT(*liblwip_tcm.a:)(.text.etharp_input) \
    SORT(*liblwip_tcm.a:)(.text.etharp_raw) \
    SORT(*libwifi_fe.a:)(.text.online_cali_send_msg) \
    SORT(*libwifi_fe.a:)(.text.online_iq_cali_complete) \
    SORT(*libwifi_fe.a:)(.text.online_iq_set_cali_status) \
    SORT(*libwifi_btcoex.a:)(.text.hmac_btcoex_wlan_priority_timeout_callback) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_calc_tx_time_diff) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_calc_goodput_diff) \
    SORT(*libwifi_alg_anti_interference.a:)(.text.alg_anti_intf_next_probe_proc) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_get_past_net_device_by_index) \
    SORT(*libwifi_drv_ws53.a:)(.text.oal_atoi) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_send_msg) \
    SORT(*libwifi_driver_tcm.a:)(.text.hmac_is_dhcp6_etc) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_netbuf_is_icmp6_etc) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_ba_send_reorder_timeout) \
    SORT(*libwifi_drv_ws53.a:)(.text.wal_util_get_vap_id) \
    SORT(*liblwip.a:)(.text.tcp_listen_input) \
    SORT(*liblwip_tcm.a:)(.text.tcp_alloc) \
    SORT(*liblwip_tcm.a:)(.text.tcp_next_iss) \
    SORT(*liblwip.a:)(.text.tcp_pcb_reset_sack_seq) \
    SORT(*liblwip.a:)(.text.tcp_sndbuf_init) \
    SORT(*liblwip.a:)(.text.tcp_enqueue_flags_sack) \
    SORT(*liblwip_tcm.a:)(.text.etharp_query) \
    SORT(*liblwip_tcm.a:)(.text.etharp_request) \
    SORT(*liblwip_tcm.a:)(.text.etharp_request_dst) \
    SORT(*liblwip.a:)(.text.dhcp_arp_reply) \
    SORT(*liblwip.a:)(.text.tcp_rexmit) \
    SORT(*liblwip_tcm.a:)(.text.accept_function) \
    SORT(*liblwip_tcm.a:)(.text.netconn_alloc) \
    SORT(*liblwip_tcm.a:)(.text.sys_mbox_new_ext) \
    SORT(*liblwip_tcm.a:)(.text.tcp_backlog_delayed) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_accepted) \
    SORT(*liblwip_tcm.a:)(.text.alloc_socket) \
    SORT(*liblwip_tcm.a:)(.text.netconn_getaddr) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_getaddr) \
    SORT(*liblwip_tcm.a:)(.text.tcp_listen_closed) \
    SORT(*liblwip_tcm.a:)(.text.tcp_listen_pcb_remove) \
    SORT(*liblwip_tcm.a:)(.text.tcp_free_listen) \
    SORT(*liblwip_tcm.a:)(.text.lwip_getoptval) \
    SORT(*liblwip_tcm.a:)(.text.lwip_sock_make_addr) \
    SORT(*libwifi_fe.a:)(.text.online_cali_read_upc_reg) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut0_cfg_rf_ppa_code_lut0) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut0_cfg_rf_ppa_code_lut1) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut1_cfg_rf_ppa_code_lut2) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut1_cfg_rf_ppa_code_lut3) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut2_cfg_rf_ppa_code_lut4) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut2_cfg_rf_ppa_code_lut5) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut3_cfg_rf_ppa_code_lut6) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut3_cfg_rf_ppa_code_lut7) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut4_cfg_rf_ppa_code_lut8) \
    SORT(*libwifi_fe.a:)(.text.hal_get_rf_ppa_code_lut4_cfg_rf_ppa_code_lut9) \
    SORT(*liblwip_tcm.a:)(.text.inet_pton) \
    SORT(*liblwip_tcm.a:)(.text.ip4addr_aton) \
    SORT(*liblwip_tcm.a:)(.text.socket) \
    SORT(*liblwip_tcm.a:)(.text.netconn_new_with_proto_and_callback) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_newconn) \
    SORT(*liblwip_tcm.a:)(.text.pcb_new) \
    SORT(*liblwip_tcm.a:)(.text.tcp_new_ip_type) \
    SORT(*liblwip_tcm.a:)(.text.lwip_sockopt_to_ipopt) \
    SORT(*liblwip_tcm.a:)(.text.bind) \
    SORT(*liblwip_tcm.a:)(.text.netconn_bind) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_bind) \
    SORT(*liblwip_tcm.a:)(.text.netif_find_by_ipaddr) \
    SORT(*liblwip_tcm.a:)(.text.netif_find_by_ip4addr) \
    SORT(*liblwip_tcm.a:)(.text.tcp_bind) \
    SORT(*liblwip_tcm.a:)(.text.netif_ipaddr_isbrdcast) \
    SORT(*liblwip_tcm.a:)(.text.tcp_new_port) \
    SORT(*liblwip_tcm.a:)(.text.tcp_generate_port_candidate) \
    SORT(*liblwip_tcm.a:)(.text.connect) \
    SORT(*liblwip_tcm.a:)(.text.netconn_connect) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_connect) \
    SORT(*liblwip_tcm.a:)(.text.tcp_connect) \
    SORT(*liblwip.a:)(.text.tcp_connect_update_sack) \
    SORT(*liblwip.a:)(.text.tcp_rexmit_rto_prepare) \
    SORT(*liblwip.a:)(.text.tcp_rexmit_rto_commit) \
    SORT(*liblwip_tcm.a:)(.text.lwip_netconn_do_connected) \
    SORT(*libwifi_fe.a:)(.text.hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_0) \
    SORT(*libwifi_fe.a:)(.text.online_cali_adjust_dbb_scaling) \
    SORT(*liblwip_tcm.a:)(.text.udp_connect) \
    SORT(*libwifi_fe.a:)(.text.online_cali_init_tx_iq_timer) \
    SORT(*libwifi_fe.a:)(.text.online_cali_tx_iq_event) \
    SORT(*libwifi_fe.a:)(.text.online_cali_init_rx_iq_timer) \
    SORT(*libwifi_fe.a:)(.text.online_cali_rx_iq_event) \
    SORT(*liblwip_tcm.a:)(.text.select) \
    SORT(*liblwip_tcm.a:)(.text.lwip_select_inc_sockets_used) \
    SORT(*liblwip_tcm.a:)(.text.lwip_link_select_cb) \
    SORT(*liblwip_tcm.a:)(.text.lwip_unlink_select_cb) \
    SORT(*liblwip_tcm.a:)(.text.lwip_select_dec_sockets_used) \
    SORT(*liblwip_tcm.a:)(.text.udp_remove) \
    SORT(*libwifi_drv_ws53.a:)(.text.uapi_wifi_ccpriv) \
    SORT(*libwifi_drv_ws53.a:)(.text.wifi_ccpriv_check_param) \
    SORT(*libwifi_driver_tcm.a:)(.text.oal_get_netdev_by_name) \
    SORT(*libwifi_drv_ws53.a:)(.text.wal_ccpriv_process_cmd) \
    SORT(*libwifi_drv_ws53.a:)(.text.wal_ccpriv_parse_cmd) \
    SORT(*libwifi_drv_ws53.a:)(.text.uapi_ccpriv_set_thruput_test) \
    SORT(*libwifi_drv_ws53.a:)(.text.wal_sync_post2hmac_no_rsp) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_sync_host_post_msg) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_host_post_msg_sync) \
    SORT(*libwifi_driver_tcm.a:)(.text.frw_msg_check_frw_deadlock) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_config_set_thruput_test) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_set_thruput_test) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_thruput_dfx_process) \
    SORT(*liblwip_tcm.a:)(.text.udp_new_ip_type) \
    SORT(*liblwip_tcm.a:)(.text.udp_new) \
    SORT(*liblwip_tcm.a:)(.text.udp_recv) \
    SORT(*liblwip_tcm.a:)(.text.udp_bind) \
    SORT(*liblwip_tcm.a:)(.text.udp_new_port) \
    SORT(*liblwip_tcm.a:)(.text.udp_generate_port_candidate) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_init_event) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_fsm_trans_to_state) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_init_exit) \
    SORT(*libwifi_alg_temp_protect.a:)(.text.alg_temp_protect_safe_entry) \
    SORT(*liblwip_tcm.a:)(.text.select_check_waiters) \
    SORT(*liblwip_tcm.a:)(.text.recv) \
    SORT(*libwifi_fe.a:)(.text.hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_1) \
    SORT(*libwifi_drv_ws53.a:)(.text.wal_scan_result_clean_timeout_fn) \
    SORT(*libwifi_drv_ws53.a:)(.text.wal_async_post2hmac_no_rsp) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_scan_clean_result) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_scan_clean_expire_scanned_bss) \
    SORT(*libwifi_drv_ws53.a:)(.text.hmac_is_connected_ap_bssid) \
    SORT(*libwifi_drv_ws53.a:)(.text.is_legacy_vap)

#endif
