/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file
 * @kit AbilityKit
 */

import { OverlayModuleInfo } from 'bundleManager.OverlayModuleInfo';

export class OverlayModuleInfoInner implements OverlayModuleInfo {
    public readonly bundleName: string = '';
    public readonly moduleName: string = '';
    public readonly targetModuleName: string = '';
    public readonly priority: int;
    public readonly state: int;

    constructor() { }
    constructor(bundleName: string,
        moduleName: string,
        targetModuleName: string,
        priority: int,
        state: int) {
            this.bundleName = bundleName;
            this.moduleName = moduleName;
            this.targetModuleName = targetModuleName;
            this.priority = priority;
            this.state = state;
  }
}
