# Copyright (c) 2022 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

group("fuzztest") {
  testonly = true
  deps = []

  deps += [
    # deps file
    "advancedmeasureformat_fuzzer:AdvancedMeasureFormatFuzzTest",
    "breakiterator_fuzzer:BreakIteratorFuzzTest",
    "calendar_fuzzer:CalendarFuzzTest",
    "character_fuzzer:CharacterFuzzTest",
    "collator_fuzzer:CollatorFuzzTest",
    "datetimefilter_fuzzer:DateTimeFilterFuzzTest",
    "datetimeformat_fuzzer:DateTimeFormatFuzzTest",
    "datetimerule_fuzzer:DateTimeRuleFuzzTest",
    "displaynames_fuzzer:DisplayNamesFuzzTest",
    "entityrecongnizer_fuzzer:EntityRecongnizerFuzzTest",
    "holidaymanager_fuzzer:HolidayManagerFuzzTest",
    "indexutil_fuzzer:IndexUtilFuzzTest",
    "intldatetimeformat_fuzzer:IntlDateTimeFormatFuzzTest",
    "intlpluralrules_fuzzer:IntlPluralRulesFuzzTest",
    "iso8601datetimeformat_fuzzer:ISO8601DateTimeFormatFuzzTest",
    "localecompare_fuzzer:LocaleCompareFuzzTest",
    "localeconfig_fuzzer:LocaleConfigFuzzTest",
    "localehelper_fuzzer:LocaleHelperFuzzTest",
    "localeinfo_fuzzer:LocaleInfoFuzzTest",
    "lunarcalendar_fuzzer:LunarCalendarFuzzTest",
    "measuredata_fuzzer:MeasureDataFuzzTest",
    "normalizer_fuzzer:NormalizerFuzzTest",
    "numberformat_fuzzer:NumberFormatFuzzTest",
    "phonenumberformat_fuzzer:PhoneNumberFormatFuzzTest",
    "phonenumbermatched_fuzzer:PhoneNumberMatchedFuzzTest",
    "pluralrules_fuzzer:PluralRulesFuzzTest",
    "preferredlanguage_fuzzer:PreferredLanguageFuzzTest",
    "regexrule_fuzzer:RegexRuleFuzzTest",
    "relativetimeformat_fuzzer:RelativeTimeFormatFuzzTest",
    "rulesengine_fuzzer:RulesEngineFuzzTest",
    "simpledatetimeformat_fuzzer:SimpleDateTimeFormatFuzzTest",
    "simplenumberformat_fuzzer:SimpleNumberFormatFuzzTest",
    "serviceclient_fuzzer:ServiceClientFuzzTest",
    "styleddatetimeformat_fuzzer:StyledDateTimeFormatFuzzTest",
    "stylednumberformat_fuzzer:StyledNumberFormatFuzzTest",
    "symboldatetimeformat_fuzzer:SymbolDateTimeFormatFuzzTest",
    "symbolnumberformat_fuzzer:SymbolNumberFormatFuzzTest",
    "systemlocalemanager_fuzzer:SystemLocaleManagerFuzzTest",
    "taboo_fuzzer:TabooFuzzTest",
    "timezone_fuzzer:TimeZoneFuzzTest",
    "utils_fuzzer:UtilsFuzzTest",
  ]
}
