/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef RELIABILITY_PROCESS_KILL_REASON_H
#define RELIABILITY_PROCESS_KILL_REASON_H

#include <string>

namespace OHOS {
namespace HiviewDFX {
namespace ProcessKillReason {
// note: It is recommended to ensure that new values follow the range divisions
//      in the table(e.g., App Exit in 1~1000), maintain consistency in code or documentation.
// +-----------+--------------------------+
// | number    | explain                  |
// +-----------+--------------------------+
// | 1~1000    | App Exit                 |
// | 1000~2000 | User Behavior            |
// | 2000~3000 | Crash Exit               |
// | 3000~4000 | System Exit              |
// | 4000~5000 | Kernel Level Termination |
// +-----------+--------------------------+
enum KillEventId {
    // app exit: 1 ~ 1000
    REASON_APP_EXIT_MIN = 1,
    REASON_KILL_APPLICATION_BY_BUNDLE_NAME = REASON_APP_EXIT_MIN,
    REASON_ON_REMOTE_DIED,
    REASON_RESTART,
    REASON_APP_EXIT,
    REASON_KILL_APPLICATION_SELF,
    REASON_KILL_PROCESS_WITH_ACCOUNT,
    REASON_KILL_APPLICATION,
    REASON_KILL_CGROUP,

    // user exit: 1000 ~ 2000
    REASON_USER_EXIT_MIN = 1000,
    REASON_USER_REQUEST = REASON_USER_EXIT_MIN,
    REASON_CLEAR_SESSION,
    REASON_UNINSTALL_APP,
    REASON_UPGRADE_APP,
    REASON_USER_LOGOUT,
    REASON_USER_STOP,
    REASON_PERMISSION_UPDATE,
    REASON_AA_FORCE_STOP,

    // crash: 2000 ~ 3000
    REASON_CRASH_EXIT_MIN = 2000,
    REASON_THREAD_BLOCK_6S = REASON_CRASH_EXIT_MIN,
    REASON_APP_INPUT_BLOCK,
    REASON_LIFECYCLE_TIMEOUT,
    REASON_JS_ERROR,
    REASON_CPP_CRASH,
    REASON_CES_REGISTER_EXCEED_LIMIT,
    REASON_RESOURCE_LEAK_PSS_SOFT_KILL,
    REASON_RESOURCE_LEAK_PSS_KILL,
    REASON_RESOURCE_LEAK_ION_LEAK,
    REASON_RESOURCE_LEAK_ASHMEM_LEAK,
    REASON_RESOURCE_LEAK_GPU_RS_LEAK,
    REASON_RESOURCE_LEAK_GPU_LEAK,
    REASON_RESOURCE_LEAK_VMA_LEAK,
    REASON_RESOURCE_LEAK_FD_LEAK,
    REASON_RESOURCE_LEAK_THREAD_LEAK,
    REASON_FD_EXCEEDS_LIMIT,
    REASON_APP_HIGH_POWER_NOTIFY_KILL,
    REASON_HIGH_POWER_CONSUMPTION_KILL,
    REASON_ILLEGAL_AUDIO_RENDERER_BY_SUSPEND,
    REASON_ILLEGAL_AUDIO_CAPTURER_BY_SUSPEND,
    REASON_IO_MANAGE_CONTROL,
    REASON_BUSINESS_THREAD_BLOCK_6S,
    REASON_BUSINESS_INPUT_BLOCK,
    REASON_MALICIOUS_CONTINUOUSTASK_ACTIVE,
    REASON_RS_TRANSACTION_DATA_OVERLIMIT,

    // sys exit: 3000 ~ 4000
    REASON_SYS_EXIT_MIN = 3000,
    REASON_CONTINUOUSLY_WAKEUP_ABNORMAL = REASON_SYS_EXIT_MIN,
    REASON_BACKGROUND_FREEZE_ABNORMAL,
    REASON_GNSS_WORK_TIME_ABNORMAL,
    REASON_BLUETOOTH_WORK_TIME_ABNORMAL,
    REASON_RUNNING_LOCK_ABNORMAL,
    REASON_KERNEL_WAKELOCK_ABNORMAL,
    REASON_POWER_SAVE_CLEAN_EXTREME_POWER_SAVE_CLEAN,
    REASON_MODULE_POWER_CONSUMPTION_ABNORMAL,
    REASON_POWER_ABNORMAL,
    REASON_MEMORY_PRESSURE,
    REASON_STABILITY_CHECK_KILL,
    REASON_APP_LIMIT_KILL,
    REASON_SWAP_FULL,
    REASON_SYSTEM_CAMERA_QUICK_KILL,
    REASON_OTHER_CAMERA_QUICK_KILL,
    REASON_ALIVE_APP_COUNT_KILL,
    REASON_LOW_FREE_KILL,
    REASON_ZSWAPD_PRESSURE,
    REASON_BIG_MEMORY_KILL,
    REASON_GPU_LEAK_KILL,
    REASON_MEMORY_LIMIT_KILL,
    REASON_PC_BIG_MEMORY_KILL,
    REASON_GPU_TEXTURE_MEM_LEAK_KILL,
    REASON_ANCO_START_QUICK_KILL,
    REASON_BG_DEPDED_MINI_SYS_KILL,
    REASON_FORE_UNDEPD_MINI_SYS_KILL,
    REASON_TEMPERATURE_CONTROL,
    REASON_CPU_EXT_HIGHLOAD,
    REASON_SCREEN_OFF_CLEAN,
    REASON_SLEEP_CLEAN,
    REASON_INACTIVE_CLEAN,
    REASON_STANDBY_FAILED_CONTINUOUSLY_WAKEUP_ABNORMAL,
    REASON_SWITCH_TO_PENGLAI_MODE,
    REASON_HEAVY_LOAD_MUTEX_KILL,
    REASON_TRANSIENT_TASK_TIMEOUT,
    REASON_RESOURCE_OVERLIMIT,
    REASON_RESOURCE_LEAK_STANDBY_CLEAN,
    REASON_SYSFREEZE_KILL_PEER_BINDER,
    REASON_TOO_MANY_READY_THREADS,
    REASON_JS_HEAP_SLEEP_CLEAN_KILL,
    REASON_HARDWARE_DECODING_RESOURCES_LIMIT,
    REASON_APPRECOVERY_NOTIFYAPP_OVER_LIMIT,
    REASON_EXTREME_POWER_SAVE_CLEAN,
    REASON_RS_VULKAN_ERROR,
    REASON_NOT_ATTACHED_TO_STATUS_BAR,
    REASON_ACCOUNT_COLD_SWITCH_KILL,
    REASON_GPU_MEMORY_READ_ERR,
    REASON_DMA_MEMORY_READ_ERR,
    REASON_MSDP_BOTTOM_N_QUICK_KILL,
    REASON_LOW_MEMORY_ANCO_CACHED_KILL,
    REASON_MINI_SYS_ANCO_SYS_PROC_KILL,
    REASON_POWER_SAVE_CLEAN,
    REASON_VRS_KILL_PROCESS,
    REASON_APPSPAWN_STOP,
    REASON_INACTIVE_PROC_KILL,

    // kernel: 4000 ~ 5000
    REASON_KERNEL_EXIT_MIN = 4000,
    REASON_OOM_KILLER = REASON_KERNEL_EXIT_MIN,
    REASON_CPA_KILLER,
    REASON_LOW_MEMORY_KILLER,
    REASON_CPU_HIGHLOAD_KILLER,
    REASON_RSS_THRESHOLD_KILLER,
    REASON_ASHMEM_THRESHOLD_KILLER,
    REASON_GPU_THRESHOLD_KILLER,
    REASON_DMA_THRESHOLD_KILLER,
    REASON_THREAD_THRESHOLD_KILLER,
    REASON_KERNEL_ZONE_LOW,
    REASON_APP_SANDBOX_UNINSTALL,
    REASON_STORAGE_CARD_UNINSTALL,
    REASON_MAX = REASON_STORAGE_CARD_UNINSTALL,
};

std::string GetKillReason(int killId);

std::string GetAppExitReason(int killId);

} // end of namespace ProcessKillReason
} // end of namespace HiviewDFX
} // end of namespace OHOS
#endif // RELIABILITY_PROCESS_KILL_REASON_H
