/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { ApplicationInfo } from 'bundleManager.ApplicationInfo';
import { ApplicationInfoInner } from 'bundleManager.ApplicationInfoInner';
import { ElementName } from 'bundleManager.ElementName';
import { ElementNameInner } from './ElementNameInner';
import { LauncherAbilityInfo } from 'bundleManager.LauncherAbilityInfo';

export class LauncherAbilityInfoInner implements LauncherAbilityInfo {
  readonly applicationInfo: ApplicationInfo = new ApplicationInfoInner;
  readonly elementName: ElementName = new ElementNameInner;
  readonly labelId: long;
  readonly iconId: long;
  readonly userId: int;
  readonly installTime: long;

  constructor() { }
  constructor(applicationInfo: ApplicationInfo,
    elementName: ElementName,
    labelId: long,
    iconId: long,
    userId: int,
    installTime: long) {
      this.applicationInfo = applicationInfo;
      this.elementName = elementName;
      this.labelId = labelId;
      this.iconId = iconId;
      this.userId = userId;
      this.installTime = installTime;
  }
}