/*
 * Copyright (c) 2023-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_BUNDLE_APPEXECFWK_CORE_IPC_INTERFACE_CODE_H
#define OHOS_BUNDLE_APPEXECFWK_CORE_IPC_INTERFACE_CODE_H

#include <stdint.h>

namespace OHOS {
namespace AppExecFwk {

/* SAID: 401 */
enum class BundleMgrInterfaceCode : uint32_t {
    GET_APPLICATION_INFO = 0,
    GET_APPLICATION_INFOS = 1,
    GET_BUNDLE_INFO = 2,
    GET_BUNDLE_PACK_INFO = 3,
    GET_BUNDLE_INFOS = 4,
    GET_UID_BY_BUNDLE_NAME = 5,
    GET_APPID_BY_BUNDLE_NAME = 6,
    GET_BUNDLE_NAME_FOR_UID = 7,
    GET_BUNDLES_FOR_UID = 8,
    GET_NAME_FOR_UID = 9,
    GET_BUNDLE_GIDS = 10,
    GET_BUNDLE_GIDS_BY_UID = 11,
    GET_APP_TYPE = 12,
    CHECK_IS_SYSTEM_APP_BY_UID = 13,
    GET_BUNDLE_INFOS_BY_METADATA = 14,
    QUERY_ABILITY_INFO = 15,
    QUERY_ABILITY_INFOS = 16,
    QUERY_ABILITY_INFO_BY_URI = 17,
    QUERY_ABILITY_INFOS_BY_URI = 18,
    QUERY_KEEPALIVE_BUNDLE_INFOS = 19,
    GET_ABILITY_LABEL = 20,
    GET_ABILITY_LABEL_WITH_MODULE_NAME = 21,
    GET_BUNDLE_ARCHIVE_INFO = 22,
    GET_HAP_MODULE_INFO = 23,
    GET_LAUNCH_WANT_FOR_BUNDLE = 24,
    GET_PERMISSION_DEF = 25,
    CLEAN_BUNDLE_CACHE_FILES = 26,
    CLEAN_BUNDLE_DATA_FILES = 27,
    REGISTER_BUNDLE_STATUS_CALLBACK = 28,
    CLEAR_BUNDLE_STATUS_CALLBACK = 29,
    UNREGISTER_BUNDLE_STATUS_CALLBACK = 30,
    DUMP_INFOS = 31,
    IS_APPLICATION_ENABLED = 32,
    SET_APPLICATION_ENABLED = 33,
    IS_ABILITY_ENABLED = 34,
    SET_ABILITY_ENABLED = 35,
    GET_ABILITY_INFO = 36,
    GET_ABILITY_INFO_WITH_MODULE_NAME = 37,
    GET_ALL_FORMS_INFO = 38,
    GET_FORMS_INFO_BY_APP = 39,
    GET_FORMS_INFO_BY_MODULE = 40,
    GET_SHORTCUT_INFO = 41,
    GET_ALL_COMMON_EVENT_INFO = 42,
    GET_BUNDLE_INSTALLER = 43,
    QUERY_ABILITY_INFO_MUTI_PARAM = 44,
    QUERY_ABILITY_INFOS_MUTI_PARAM = 45,
    QUERY_ALL_ABILITY_INFOS = 46,
    GET_APPLICATION_INFO_WITH_INT_FLAGS = 47,
    GET_APPLICATION_INFOS_WITH_INT_FLAGS = 48,
    GET_BUNDLE_INFO_WITH_INT_FLAGS = 49,
    GET_BUNDLE_PACK_INFO_WITH_INT_FLAGS = 50,
    GET_BUNDLE_INFOS_WITH_INT_FLAGS = 51,
    GET_BUNDLE_ARCHIVE_INFO_WITH_INT_FLAGS = 52,
    GET_BUNDLE_USER_MGR = 53,
    GET_DISTRIBUTE_BUNDLE_INFO = 54,
    QUERY_ABILITY_INFO_BY_URI_FOR_USERID = 55,
    GET_APPLICATION_PRIVILEGE_LEVEL = 56,
    QUERY_EXTENSION_INFO_WITHOUT_TYPE = 57,
    QUERY_EXTENSION_INFO = 58,
    QUERY_EXTENSION_INFO_BY_TYPE = 59,
    VERIFY_CALLING_PERMISSION = 60,
    QUERY_EXTENSION_ABILITY_INFO_BY_URI = 61,
    IS_MODULE_REMOVABLE = 62,
    SET_MODULE_REMOVABLE = 63,
    QUERY_ABILITY_INFO_WITH_CALLBACK = 64,
    UPGRADE_ATOMIC_SERVICE = 65,
    IS_MODULE_NEED_UPDATE = 66,
    SET_MODULE_NEED_UPDATE = 67,
    GET_HAP_MODULE_INFO_WITH_USERID = 68,
    IMPLICIT_QUERY_INFO_BY_PRIORITY = 69,
    IMPLICIT_QUERY_INFOS = 70,
    GET_ALL_DEPENDENT_MODULE_NAMES = 71,
    GET_SANDBOX_APP_BUNDLE_INFO = 72,
    QUERY_CALLING_BUNDLE_NAME = 73,
    GET_DEFAULT_APP_PROXY = 74,
    GET_BUNDLE_STATS = 75,
    CHECK_ABILITY_ENABLE_INSTALL = 76,
    GET_SANDBOX_APP_ABILITY_INFO = 77,
    GET_SANDBOX_APP_EXTENSION_INFOS = 78,
    GET_SANDBOX_MODULE_INFO = 79,
    GET_MEDIA_DATA = 80,
    GET_QUICK_FIX_MANAGER_PROXY = 81,
    GET_STRING_BY_ID = 82,
    GET_ICON_BY_ID = 83,
    GET_UDID_BY_NETWORK_ID = 84,
    GET_APP_CONTROL_PROXY = 85,
    SET_DEBUG_MODE = 86,
    QUERY_ABILITY_INFOS_V9 = 87,
    QUERY_EXTENSION_INFO_WITHOUT_TYPE_V9 = 88,
    QUERY_EXTENSION_INFO_V9 = 89,
    GET_APPLICATION_INFOS_WITH_INT_FLAGS_V9 = 90,
    GET_APPLICATION_INFO_WITH_INT_FLAGS_V9 = 91,
    GET_BUNDLE_ARCHIVE_INFO_WITH_INT_FLAGS_V9 = 92,
    GET_BUNDLE_INFO_WITH_INT_FLAGS_V9 = 93,
    GET_BUNDLE_INFOS_WITH_INT_FLAGS_V9 = 94,
    GET_SHORTCUT_INFO_V9 = 95,
    REGISTER_BUNDLE_EVENT_CALLBACK = 96,
    UNREGISTER_BUNDLE_EVENT_CALLBACK = 97,
    GET_BUNDLE_INFO_FOR_SELF = 98,
    VERIFY_SYSTEM_API = 99,
    GET_OVERLAY_MANAGER_PROXY = 100,
    SILENT_INSTALL = 101,
    PROCESS_PRELOAD = 102,
    GET_APP_PROVISION_INFO = 103,
    GET_PROVISION_METADATA = 104,
    GET_BASE_SHARED_BUNDLE_INFOS = 105,
    GET_ALL_SHARED_BUNDLE_INFO = 106,
    GET_SHARED_BUNDLE_INFO = 107,
    GET_SHARED_BUNDLE_INFO_BY_SELF = 108,
    GET_SHARED_DEPENDENCIES = 109,
    GET_DEPENDENT_BUNDLE_INFO = 110,
    GET_UID_BY_DEBUG_BUNDLE_NAME = 111,
    QUERY_LAUNCHER_ABILITY_INFO = 112,
    GET_SPECIFIED_DISTRIBUTED_TYPE = 113,
    GET_ADDITIONAL_INFO = 114,
    GET_PROXY_DATA_INFOS = 115,
    GET_ALL_PROXY_DATA_INFOS = 116,
    SET_EXT_NAME_OR_MIME_TO_APP = 117,
    DEL_EXT_NAME_OR_MIME_TO_APP = 118,
    QUERY_DATA_GROUP_INFOS = 119,
    GET_PREFERENCE_DIR_BY_GROUP_ID = 120,
    QUERY_APPGALLERY_BUNDLE_NAME = 121,
    RESET_AOT_COMPILE_STATUS = 122,
    QUERY_EXTENSION_ABILITY_INFO_WITH_TYPE_NAME = 123,
    GET_JSON_PROFILE = 124,
    GET_BUNDLE_RESOURCE_PROXY = 125,
    GET_VERIFY_MANAGER = 126,
    GET_RECOVERABLE_APPLICATION_INFO = 127,
    GET_UNINSTALLED_BUNDLE_INFO = 128,
    SET_ADDITIONAL_INFO = 129,
    QUERY_EXTENSION_ABILITY_INFO_ONLY_WITH_TYPE_NAME = 130,
    COMPILE_PROCESSAOT = 131,
    COMPILE_RESET = 132,
    CREATE_BUNDLE_DATA_DIR = 133,
    GET_ALL_BUNDLE_STATS = 134,
    CAN_OPEN_LINK = 135,
    GET_ODID = 136,
    GET_EXTEND_RESOURCE_MANAGER = 137,
    GET_ALL_BUNDLE_INFO_BY_DEVELOPER_ID = 138,
    GET_DEVELOPER_IDS = 139,
    SWITCH_UNINSTALL_STATE = 140,
    QUERY_ABILITY_INFO_BY_CONTINUE_TYPE = 141,
    COPY_AP = 142,
    BATCH_QUERY_ABILITY_INFOS = 143,
    BATCH_GET_BUNDLE_INFO = 144,
    GET_PREINSTALLED_APPLICATION_INFO = 145,
    AUTO_CLEAN_CACHE_BY_SIZE = 146,
    GET_CLONE_ABILITY_INFO = 147,
    GET_CLONE_BUNDLE_INFO = 148,
    GET_CLONE_APP_INDEXES = 149,
    GET_NAME_AND_APPINDEX_FOR_UID = 150,
    QUERY_CLONE_EXTENSION_ABILITY_INFO_WITH_APP_INDEX = 151,
    GET_SIGNATURE_INFO = 152,
    SET_CLONE_APPLICATION_ENABLED = 153,
    IS_CLONE_APPLICATION_ENABLED = 154,
    SET_CLONE_ABILITY_ENABLED = 155,
    IS_CLONE_ABILITY_ENABLED = 156,
    GET_ODID_BY_BUNDLENAME = 157,
    ADD_DESKTOP_SHORTCUT_INFO = 158,
    DELETE_DESKTOP_SHORTCUT_INFO = 159,
    GET_ALL_DESKTOP_SHORTCUT_INFO = 160,
    GET_BUNDLE_INFOS_FOR_CONTINUATION = 161,
    GET_CONTINUE_BUNDLE_NAMES = 162,
    GET_LAUNCH_WANT = 163,
    UPDATE_APP_ENCRYPTED_KEY_STATUS = 164,
    IS_BUNDLE_INSTALLED = 165,
    GET_COMPATIBLED_DEVICE_TYPE_NATIVE = 166,
    GET_COMPATIBLED_DEVICE_TYPE = 167,
    GET_BUNDLE_NAME_BY_APP_ID_OR_APP_IDENTIFIER = 168,
    GET_DIR_BY_BUNDLENAME_AND_APPINDEX = 169,
    GET_ALL_BUNDLE_DIRS = 170,
    GET_ALL_BUNDLE_CACHE = 171,
    CLEAN_ALL_BUNDLE_CACHE = 172,
    GET_SIMPLE_APP_INFO_FOR_UID = 173,
    CREATE_BUNDLE_DATA_DIR_WITH_EL = 174,
    GET_SIGNATURE_INFO_BY_UID = 175,
    SET_APP_DISTRIBUTION_TYPES = 176,
    MIGRATE_DATA = 177,
    GET_CLONE_BUNDLE_INFO_EXT = 178,
    GET_LAUNCHER_ABILITY_INFO_SYNC = 179,
    GET_BUNDLE_MGR_EXT_PROXY = 180,
    GET_ALL_PLUGIN_INFO = 181,
    GET_PLUGIN_INFOS_FOR_SELF = 182,
    GET_PLUGIN_ABILITY_INFO = 183,
    GET_PLUGIN_HAP_MODULE_INFO = 184,
    REGISTER_PLUGIN_EVENT_CALLBACK = 185,
    UNREGISTER_PLUGIN_EVENT_CALLBACK = 186,
    GET_ADDITIONAL_INFO_FOR_ALL_USER = 187,
	GET_ABILITY_INFOS = 188,
    GET_SANDBOX_DATA_DIR = 189,
    SET_SHORTCUT_VISIBLE = 190,
    GET_ALL_SHORTCUT_INFO_FOR_SELF = 191,
    GREAT_OR_EQUAL_API_TARGET_VERSION  = 192,
    BATCH_GET_SPECIFIED_DISTRIBUTED_TYPE = 193,
    GET_APPIDENTIFIER_AND_APPINDEX = 194,
    BATCH_GET_ADDITIONAL_INFO = 195,
    BATCH_GET_BUNDLE_STATS = 196,
    GET_SHORTCUT_INFO_BY_APPINDEX = 197,
    GET_PLUGIN_INFO = 198,
    RESET_ALL_AOT = 199,
    GET_TEST_RUNNER = 200,
    CLEAN_BUNDLE_CACHE_FILES_FOR_SELF = 201,
    IS_DEBUGGABLE_APPLICATION = 202,
    GET_ALL_BUNDLE_NAMES = 203,
    GET_ABILITY_RESOURCE_INFO = 204,
    SWITCH_UNINSTALL_STATE_BY_USER_ID = 205,
    SET_ABILITY_FILE_TYPES_FOR_SELF = 206,
    GET_PLUGIN_BUNDLE_PATH_FOR_SELF = 207,
    RECOVER_BACKUP_BUNDLE_DATA = 208,
    REMOVE_BACKUP_BUNDLE_DATA = 209,
    CREATE_NEW_BUNDLE_DIR = 210,
    GET_BUNDLE_INSTALL_STATUS = 211,
    GET_ALL_JSON_PROFILE = 212,
    GET_BUNDLE_INFO_FOR_EXCEPTION = 213,
    BATCH_GET_COMPATIBLED_DEVICE_TYPE = 214,
    GET_ALL_APP_PROVISION_INFO = 215,
    ADD_DYNAMIC_SHORTCUT_INFOS = 216,
    DELETE_DYNAMIC_SHORTCUT_INFOS = 217,
    GET_ASSET_GROUPS_INFOS_BY_UID = 218,
    SET_SHORTCUTS_ENABLED = 219,
    GET_PLUGIN_EXTENSION_INFO = 220,
    AUTO_CLEAN_CACHE_BY_INODE = 221,
    GET_ALL_APP_INSTALL_EXTENSION_INFO = 222,
    IS_APPLICATION_DISABLE_FORBIDDEN = 223,
    SET_APPLICATION_DISABLE_FORBIDDEN = 224,
    GET_BUNDLE_INODE_COUNT = 225,
    GET_SHORTCUT_INFO_BY_ABILITY = 226,
    GET_ODID_RESET_COUNT = 227,
    GET_APPLICATION_LABEL = 228,
    GET_INSTALLED_BUNDLE_LIST = 229,
    SET_BUNDLE_FIRST_LAUNCH = 230,
    GET_ALL_NEW_PREINSTALLED_APPLICATION_INFOS = 231,
    GET_API_TARGET_VERSION_BY_UID = 232,
    GET_SKILL_MANAGER_PROXY = 233,
    GET_TOP_N_LARGEST_ITEMS_IN_APP_DATA_DIR = 234,
    GET_ALTERNATE_ICONS = 235,
    QUERY_EXTENSION_ABILITY_INFO_BY_URI_OPTIMAL = 236,
    GET_LOCAL_PLUGIN_INSTALLER = 237,
    GET_MAIN_AND_CLONE_BUNDLE_INFO = 238,
    GET_ALL_LOCAL_PLUGIN_INFO_FOR_SELF = 239,
    AUTO_CLEAN_PARTIAL_CACHE = 240,
    QUERY_SANDBOX_CLONE_ABILITY_INFO = 241,
    GET_CLI_SANDBOX_APP_INDEXES = 242,
    GET_STRING_BY_ID_LIST = 243,
    GET_APP_CLONE_PREFERENCE = 244,
    SET_APP_CLONE_PREFERENCE = 245,
};

/* SAID: 401-85 Interface No.85 subservice also provides the following interfaces */
enum class AppControlManagerInterfaceCode : uint8_t {
    ADD_APP_INSTALL_CONTROL_RULE = 0,
    DELETE_APP_INSTALL_CONTROL_RULE = 1,
    CLEAN_APP_INSTALL_CONTROL_RULE = 2,
    GET_APP_INSTALL_CONTROL_RULE = 3,
    ADD_APP_RUNNING_CONTROL_RULE = 4,
    DELETE_APP_RUNNING_CONTROL_RULE = 5,
    CLEAN_APP_RUNNING_CONTROL_RULE = 6,
    GET_APP_RUNNING_CONTROL_RULE = 7,
    GET_APP_RUNNING_CONTROL_RULE_RESULT = 8,
    SET_DISPOSED_STATUS = 9,
    DELETE_DISPOSED_STATUS = 10,
    GET_DISPOSED_STATUS = 11,
    CONFIRM_APP_JUMP_CONTROL_RULE = 12,
    ADD_APP_JUMP_CONTROL_RULE = 13,
    DELETE_APP_JUMP_CONTROL_RULE = 14,
    DELETE_APP_JUMP_CONTROL_RULE_BY_CALLER = 15,
    DELETE_APP_JUMP_CONTROL_RULE_BY_TARGET = 16,
    GET_APP_JUMP_CONTROL_RULE = 17,
    SET_DISPOSED_RULE = 18,
    GET_DISPOSED_RULE = 19,
    GET_ABILITY_RUNNING_CONTROL_RULE = 20,
    GET_DISPOSED_RULE_FOR_CLONE_APP = 21,
    SET_DISPOSED_RULE_FOR_CLONE_APP = 22,
    DELETE_DISPOSED_RULE_FOR_CLONE_APP = 23,
    SET_UNINSTALL_DISPOSED_RULE = 24,
    GET_UNINSTALL_DISPOSED_RULE = 25,
    DELETE_UNINSTALL_DISPOSED_RULE = 26,
    SET_DISPOSED_RULES = 27,
    DELETE_DISPOSED_RULES = 28,
    GET_DISPOSED_RULES = 29,
    GET_ALL_DISPOSED_RULES_BY_SETTER = 30,
};

/* SAID: 401-96 Interface No.96 subservice also provides the following interfaces */
enum class BundleEventCallbackInterfaceCode : uint8_t {
    ON_RECEIVE_EVENT = 0,
};

/* SAID: 401-43 Interface No.43 subservice also provides the following interfaces */
enum class BundleInstallerInterfaceCode : uint8_t {
    INSTALL = 0,
    INSTALL_MULTIPLE_HAPS = 1,
    UNINSTALL = 2,
    UNINSTALL_MODULE = 3,
    UNINSTALL_BY_UNINSTALL_PARAM = 4,
    RECOVER = 5,
    INSTALL_SANDBOX_APP = 6,
    UNINSTALL_SANDBOX_APP = 7,
    CREATE_STREAM_INSTALLER = 8,
    DESTORY_STREAM_INSTALLER = 9,
    UNINSTALL_AND_RECOVER = 10,
    INSTALL_CLONE_APP = 11,
    UNINSTALL_CLONE_APP = 12,
    INSTALL_EXISTED = 13,
    INSTALL_PLUGIN_APP = 14,
    UNINSTALL_PLUGIN_APP = 15,
    ADD_ENTERPRISE_RESIGN_CERT = 16,
    DELETE_ENTERPRISE_RE_SIGNATURE_CERT = 17,
    GET_ENTERPRISE_RE_SIGNATURE_CERT = 18,
    UNINSTALL_NEW_PREINSTALLED_APPS = 19,
    CREATE_CLI_SANDBOX_APP = 20,
    DESTROY_CLI_SANDBOX_APP = 21,
};

/* SAID: 401-28 Interface No.28 subservice also provides the following interfaces */
enum class BundleStatusCallbackInterfaceCode : uint8_t {
    ON_BUNDLE_STATE_CHANGED = 0,
};

/* SAID: 401-43 Interface No.43 subservice also provides the following interfaces */
enum class BundleStreamInstallerInterfaceCode : uint8_t {
    CREATE_STREAM = 0,
    STREAM_INSTALL = 1,
    CREATE_SHARED_BUNDLE_STREAM = 2,
    CREATE_SIGNATURE_FILE_STREAM = 3,
    CREATE_PGO_FILE_STREAM = 4,
    CREATE_EXT_PROFILE_FILE_STREAM = 5
};

enum class LocalPluginStreamInstallerInterfaceCode : uint8_t {
    CREATE_PLUGIN_FILE_STREAM = 0,
    COMMIT_LOCAL_PLUGIN_INSTALL = 1,
};

enum class LocalPluginInstallerInterfaceCode : uint8_t {
    UNINSTALL = 0,
    CREATE_LOCAL_PLUGIN_STREAM_INSTALLER = 1,
    DESTROY_LOCAL_PLUGIN_STREAM_INSTALLER = 2,
    INTERNAL_UNINSTALL = 3,
};

/* SAID: 401-26 Interface No.26 subservice also provides the following interfaces */
enum class CleanCacheCallbackInterfaceCode : uint8_t {
    ON_CLEAN_CACHE_CALLBACK = 0,
};

/* SAID: 401-234 Interface No.234 subservice also provides the following interfaces */
enum class GetLargestItemsCallbackInterfaceCode : uint8_t {
    ON_GET_LARGEST_ITEMS_CALLBACK = 0,
};

/* SAID: 401-27 Interface No.26 subservice also provides the following interfaces */
enum class ProcessCacheCallbackInterfaceCode : uint8_t {
    GET_ALL_BUNDLE_CACHE = 0,
    CLEAN_ALL_BUNDLE_CACHE = 1,
};

/* SAID: 401-43 Interface No.43 subservice also provides the following interfaces */
enum class StatusReceiverInterfaceCode : uint8_t {
    ON_STATUS_NOTIFY = 0,
    ON_FINISHED = 1,
};

/* SAID: 401-74 Interface No.74 subservice also provides the following interfaces */
enum class DefaultAppInterfaceCode : uint8_t {
    IS_DEFAULT_APPLICATION = 0,
    GET_DEFAULT_APPLICATION = 1,
    SET_DEFAULT_APPLICATION = 2,
    RESET_DEFAULT_APPLICATION = 3,
    SET_DEFAULT_APPLICATION_FOR_APP_CLONE = 4,
    SET_DEFAULT_APPLICATION_FOR_CUSTOM = 5,
};

/* SAID: 401-100 Interface No.100 subservice also provides the following interfaces */
enum class OverlayManagerInterfaceCode : uint8_t {
    GET_ALL_OVERLAY_MODULE_INFO = 0,
    GET_OVERLAY_MODULE_INFO_BY_NAME = 1,
    GET_OVERLAY_MODULE_INFO = 2,
    GET_TARGET_OVERLAY_MODULE_INFOS = 3,
    GET_OVERLAY_MODULE_INFO_BY_BUNDLE_NAME = 4,
    GET_OVERLAY_BUNDLE_INFO_FOR_TARGET = 5,
    GET_OVERLAY_MODULE_INFO_FOR_TARGET = 6,
    SET_OVERLAY_ENABLED = 7,
    SET_OVERLAY_ENABLED_FOR_SELF = 8,
};

/* SAID: 401-81 Interface No.81 subservice also provides the following interfaces */
enum class QuickFixManagerInterfaceCode : uint8_t {
    DEPLOY_QUICK_FIX = 0,
    SWITCH_QUICK_FIX = 1,
    DELETE_QUICK_FIX = 2,
    CREATE_FD = 3
};

/* SAID: 401-81 Interface No.81 subservice also provides the following interfaces */
enum class QuickFixStatusCallbackInterfaceCode : uint8_t {
    ON_PATCH_DEPLOYED = 1,
    ON_PATCH_SWITCHED = 2,
    ON_PATCH_DELETED = 3
};

/* SAID: 401-53 Interface No.53 subservice also provides the following interfaces */
enum class BundleUserMgrInterfaceCode : uint8_t {
    CREATE_USER = 0,
    REMOVE_USER = 1,
};

/* SAID: 401-125 Interface No.125 subservice also provides the following interfaces */
enum class BundleResourceInterfaceCode : uint8_t {
    GET_BUNDLE_RESOURCE_INFO = 0,
    GET_LAUNCHER_ABILITY_RESOURCE_INFO = 1,
    GET_ALL_BUNDLE_RESOURCE_INFO = 2,
    GET_ALL_LAUNCHER_ABILITY_RESOURCE_INFO = 3,
    ADD_RESOURCE_INFO_BY_BUNDLE_NAME = 4,
    ADD_RESOURCE_INFO_BY_ABILITY = 5,
    DELETE_RESOURCE_INFO = 6,
    GET_EXTENSION_ABILITY_RESOURCE_INFO = 7,
    GET_ALL_UNINSTALL_BUNDLE_RESOURCE_INFO = 8,
    GET_LAUNCHER_ABILITY_RESOURCE_INFO_LIST = 9,
};

/* SAID: 401-233 Interface No.233 subservice also provides the following interfaces */
enum class SkillManagerInterfaceCode : uint8_t {
    GET_SKILL_INFO_FOR_SELF = 0,
    GET_SKILL_INFOS_FOR_SELF = 1,
    GET_SKILL_INFO = 2,
    GET_SKILL_INFOS = 3,
    GET_ALL_SKILL_INFOS = 4,
};

/* SAID: 401-127 Interface No.127 subservice also provides the following interfaces */
enum class ExtendResourceManagerInterfaceCode : uint8_t {
    ADD_EXT_RESOURCE = 0,
    REMOVE_EXT_RESOURCE = 1,
    GET_EXT_RESOURCE = 2,
    ENABLE_DYNAMIC_ICON = 3,
    DISABLE_DYNAMIC_ICON = 4,
    GET_DYNAMIC_ICON = 5,
    CREATE_FD = 6,
    GET_ALL_DYNAMIC_ICON_INFO = 7,
    GET_DYNAMIC_ICON_INFO = 8,
    SET_ALTERNATE_ICON = 9,
};

} // namespace AppExecFwk
} // namespace OHOS
#endif // OHOS_BUNDLE_APPEXECFWK_CORE_IPC_INTERFACE_CODE_H
