# Copyright (c) 2021-2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/test.gni")
import("../../../../../appexecfwk.gni")
module_output_path = "bundle_framework/bundle_framework"

ohos_systemtest("BmsInstallHapSoTest") {
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    debug = false
  }
  module_out_path = module_output_path

  sources = [ "bms_install_hap_so_test.cpp" ]
  cflags = []
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }
  deps = [
    "${base_path}:appexecfwk_base",
    "${bundle_framework_path}/test/sceneProject/systemtest/bundle_hsp/hsp_A:hsp_A",
    "${bundle_framework_path}/test/sceneProject/systemtest/bundle_hsp/hsp_A/feature1:hspASystemtestFeature1",
    "${bundle_framework_path}/test/sceneProject/systemtest/bundle_hsp/hsp_A/feature2:hspASystemtestFeature2",
    "${bundle_framework_path}/test/sceneProject/systemtest/bundle_hsp/hsp_A/feature3:hspASystemtestFeature3",
    "${bundle_framework_path}/test/sceneProject/systemtest/bundle_hsp/hsp_A/feature4:hspASystemtestFeature4",
    "${bundle_framework_path}/test/sceneProject/systemtest/ohos_test:copy_ohos_test",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso1:hapNotIncludeso1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso2:hapNotIncludeso2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso3:hapNotIncludeso3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso4:hapNotIncludeso4",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso5:hapNotIncludeso5",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso5/feature1:hapNotIncludesoFeature1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso5/feature2:hapNotIncludesoFeature2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso5/feature3:hapNotIncludesoFeature3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso6:hapNotIncludeso6",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso6/feature4:hapNotIncludesoFeature4",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso6/feature5:hapNotIncludesoFeature5",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapNotIncludeso6/feature6:hapNotIncludesoFeature6",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso1:hapSectionContainso1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso1/feature1:hapSectionContainsoFeature1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso1/feature2:hapSectionContainsoFeature2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso1/feature3:hapSectionContainsoFeature3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso2:hapSectionContainso2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso2/feature4:hapSectionContainsoFeature4",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso2/feature5:hapSectionContainsoFeature5",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapNoSo/hapSectionContainso2/feature6:hapSectionContainsoFeature6",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso1:hapIncludeso1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso2:hapIncludeso2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso3:hapIncludeso3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso4:hapIncludeso4",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5:hapIncludeso5",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature1:hapIncludeso5Feature1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature2:hapIncludeso5Feature2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature3:hapIncludeso5Feature3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature4:hapIncludeso5Feature4",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature5:hapIncludeso5Feature5",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature6:hapIncludeso5Feature6",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature7:hapIncludeso5Feature7",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/feature8:hapIncludeso5Feature8",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso5/hapnoso1:hapnoso1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso6:hapIncludeso6",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso6/feature1:hapIncludeso6Feature1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso6/feature2:hapIncludeso6Feature2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso6/feature3:hapIncludeso6Feature3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso6/hapnoso2:hapnoso2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso7:hapIncludeso7",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso7/feature1:hapIncludeso7Feature1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso7/hapnoso3:hapnoso3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso8:hapIncludeso8",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso8/feature1:hapIncludeso8Feature1",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso8/feature2:hapIncludeso8Feature2",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso8/feature3:hapIncludeso8Feature3",
    "${bundle_framework_path}/test/sceneProject/systemtest/testHapSo/hapIncludeso8/hapnoso4:hapnoso4",
    "${common_path}:libappexecfwk_common",
    "${core_path}:appexecfwk_core",
    "${services_path}/test/moduletest/utils:tool_common",
  ]

  defines = [ "APP_LOG_TAG = \"BundleMgrTool\"" ]

  external_deps = [
    "ability_base:want",
    "c_utils:utils",
    "common_event_service:cesfwk_innerkits",
    "googletest:gtest_main",
    "hilog:libhilog",
    "init:libbegetutil",
    "ipc:ipc_core",
    "samgr:samgr_proxy",
  ]
}

ohos_systemtest("BmsInstallSystemTest") {
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    debug = false
  }
  module_out_path = module_output_path

  sources = [ "bms_install_system_test.cpp" ]
  cflags = []
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }
  deps = [
    "${base_path}:appexecfwk_base",
    "${bundle_framework_path}/test/sceneProject/systemtest/ohos_test:copy_ohos_test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stSystemBundle/bmsSystemBundle1:bmsSystemBundle1",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle1:stbmsThirdBundle1",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle10:stbmsThirdBundle10",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle12:stbmsThirdBundle12",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle13:stbmsThirdBundle13",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle17:stbmsThirdBundle17",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle2:stbmsThirdBundle2",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle24:stbmsThirdBundle24",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle25:stbmsThirdBundle25",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle26:stbmsThirdBundle26",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle28:stbmsThirdBundle28",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle3:stbmsThirdBundle3",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle4:stbmsThirdBundle4",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle41:stbmsThirdBundle41",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle42:stbmsThirdBundle42",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle43:stbmsThirdBundle43",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle44:stbmsThirdBundle44",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle45:stbmsThirdBundle45",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle5:stbmsThirdBundle5",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle6:stbmsThirdBundle6",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle7:stbmsThirdBundle7",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle8:stbmsThirdBundle8",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle9:stbmsThirdBundle9",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundles1:stbmsThirdBundles1",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e21Test:e21Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e23Test:e23Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e3Test:e3Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e4Test:e4Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e5Test:e5Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e6Test:e6Test",
    "${common_path}:libappexecfwk_common",
    "${core_path}:appexecfwk_core",
    "${services_path}/test/moduletest/utils:tool_common",
  ]

  defines = [ "APP_LOG_TAG = \"BundleMgrTool\"" ]

  external_deps = [
    "ability_base:want",
    "common_event_service:cesfwk_innerkits",
    "googletest:gtest_main",
    "hilog:libhilog",
    "ipc:ipc_core",
    "samgr:samgr_proxy",
  ]
}

ohos_systemtest("BmsInstallExtensionSystemTest") {
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    debug = false
  }
  module_out_path = module_output_path

  sources = [ "bms_install_extension_system_test.cpp" ]
  cflags = []
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }
  deps = [
    "${base_path}:appexecfwk_base",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/oneExtensionDir/version1/entry:version1_oneExtension_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/oneExtensionDir/version1/entry_ex2:version1_oneExtension2_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/oneExtensionDir/version1/feature:version1_oneExtension_feature_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/oneExtensionDir/version2/entry:version2_oneExtension_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/oneExtensionDir/version2/entry_ex2:version2_oneExtension2_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/oneExtensionDir/version2/feature:version2_oneExtension_feature_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/twoExtensionDir/version1/entry:version1_twoExtension_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/twoExtensionDir/version1/feature:version1_twoExtension_feature_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/twoExtensionDir/version2/entry:version2_twoExtension_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/twoExtensionDir/version2/feature:version2_twoExtension_feature_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/withoutExtensionDir/version1/entry:version1_withoutExtension_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/withoutExtensionDir/version1/feature:version1_withoutExtension_feature_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/withoutExtensionDir/version1_form/entry:version1_withoutExtension_entry_form_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/withoutExtensionDir/version2/entry:version2_withoutExtension_entry_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/withoutExtensionDir/version2/feature:version2_withoutExtension_feature_hap",
    "${bundle_framework_path}/test/sceneProject/systemtest/extensionDirTest/withoutExtensionDir/version2_form/entry:version2_withoutExtension_entry_form_hap",
    "${common_path}:libappexecfwk_common",
    "${core_path}:appexecfwk_core",
    "${services_path}/test/moduletest/utils:tool_common",
  ]

  defines = [ "APP_LOG_TAG = \"BundleMgrTool\"" ]

  external_deps = [
    "ability_base:want",
    "common_event_service:cesfwk_innerkits",
    "googletest:gtest_main",
    "hilog:libhilog",
    "ipc:ipc_core",
    "samgr:samgr_proxy",
  ]
}

ohos_systemtest("BmsInstallGroupTest") {
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    debug = false
  }
  module_out_path = module_output_path

  sources = [ "bms_install_group_test.cpp" ]
  cflags = []
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }
  deps = [
    "${base_path}:appexecfwk_base",
    "${bundle_framework_path}/test/sceneProject/systemtest/ohos_test:copy_ohos_test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stSystemBundle/bmsSystemBundle1:bmsSystemBundle1",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle1:stbmsThirdBundle1",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle10:stbmsThirdBundle10",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle12:stbmsThirdBundle12",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle13:stbmsThirdBundle13",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle17:stbmsThirdBundle17",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle2:stbmsThirdBundle2",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle24:stbmsThirdBundle24",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle25:stbmsThirdBundle25",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle26:stbmsThirdBundle26",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle28:stbmsThirdBundle28",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle3:stbmsThirdBundle3",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle4:stbmsThirdBundle4",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle41:stbmsThirdBundle41",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle42:stbmsThirdBundle42",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle43:stbmsThirdBundle43",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle44:stbmsThirdBundle44",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle45:stbmsThirdBundle45",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle5:stbmsThirdBundle5",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle6:stbmsThirdBundle6",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle7:stbmsThirdBundle7",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle8:stbmsThirdBundle8",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundle9:stbmsThirdBundle9",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/bmsThirdBundles1:stbmsThirdBundles1",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e21Test:e21Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e23Test:e23Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e3Test:e3Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e4Test:e4Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e5Test:e5Test",
    "${bundle_framework_path}/test/sceneProject/systemtest/stThirdBundle/e6Test:e6Test",
    "${common_path}:libappexecfwk_common",
    "${core_path}:appexecfwk_core",
    "${services_path}/test/moduletest/utils:tool_common",
  ]

  defines = [ "APP_LOG_TAG = \"BundleMgrTool\"" ]

  external_deps = [
    "ability_base:want",
    "common_event_service:cesfwk_innerkits",
    "googletest:gtest_main",
    "hilog:libhilog",
    "ipc:ipc_core",
    "samgr:samgr_proxy",
  ]
}

group("systemtest") {
  testonly = true

  deps = [
    ":BmsInstallExtensionSystemTest",
    ":BmsInstallGroupTest",
    ":BmsInstallHapSoTest",
    ":BmsInstallSystemTest",
  ]
}
