#!/bin/bash
set -e
product_out_dir="$1"
build_ws63_sdk_open="$2"
# XTS overlay isolation (mirrors hi3861 sdk_liteos/hm_build.sh): turn the
# GN-forwarded env vars (XTS_OVERLAY_ARG / HCTEST_RODATA_OPT_ARG) into the
# link-script preprocessor defines consumed by build_linker.cmake.
# XTS_OVERLAY_ENABLE gates the OVERLAY block + .bss EXCLUDE_FILE in linker.prelds;
# HCTEST_NEW_RUNNER gates the .xts_init KEEP blocks (active when either overlay
# or rodata_opt is on, since the shared hctest.c RunAllXtsTests + .xts_init
# mechanism needs them in both cases). Exported so the python3 build.py / cmake
# subprocess inherits them.
if [ "$XTS_OVERLAY_ARG" = "true" ]; then
    export XTS_OVERLAY_ENABLE=true
fi
if [ "$XTS_OVERLAY_ARG" = "true" ] || [ "$HCTEST_RODATA_OPT_ARG" = "true" ]; then
    export HCTEST_NEW_RUNNER=true
fi
# prebuild #
CROOT=$(pwd)

OUTPUT_SRC_DIR=$CROOT/output/ws63/fwpkg
OUTPUT_DST_DIR=$1

OHOS_LIBS_DIR=$CROOT/interim_binary/ws63/libs/ohos/ws63-liteos-app
OHOS_LIBS_XTS_DIR=$CROOT/interim_binary/ws63/libs/ohos/ws63-liteos-xts
OHOS_XTS_MINIMAL=false
export OHOS_XTS_MINIMAL=false
if [[ "$product_out_dir" == *xts_minimal* ]]; then
    OHOS_XTS_MINIMAL=true
    export OHOS_XTS_MINIMAL=true
fi

rm $OHOS_LIBS_DIR -rf
rm $OHOS_LIBS_XTS_DIR -rf

mkdir -p $OHOS_LIBS_DIR
mkdir -p $OHOS_LIBS_XTS_DIR

find $OUTPUT_DST_DIR/libs/ -name '*.a' -exec cp "{}" $OHOS_LIBS_XTS_DIR  \;
find $OUTPUT_DST_DIR/libs/ -name '*.a' -exec cp "{}" $OHOS_LIBS_DIR  \;
# Copy source-switch marker file (generated by OHOS GN write_file) to interim for SDK cmake dual-gate
cp $OUTPUT_DST_DIR/mbedtls_ohos_switch.marker $OHOS_LIBS_XTS_DIR/ 2>/dev/null || true
cp $OUTPUT_DST_DIR/mbedtls_ohos_switch.marker $OHOS_LIBS_DIR/ 2>/dev/null || true

# Sanity check: every lib required by the SDK cmake COMPONENT_LIST (libs_url/ws63/cmake/ohos.cmake)
# must have been copied; a missing lib here means the GN side did not finish archiving it
# (dependency race) and the cmake link would fail with "No rule to make target".
if [[ "$product_out_dir" == *xts_minimal* ]]; then
    REQUIRED_LIBS="begetutil bootstrap devattest_sdk devattest_core hal_file_static hal_sys_param hal_sysparam hal_token_static hal_update_static hilog_lite_static hilog_static hiview_lite_static hievent_lite_static init_log init_utils inithook samgr samgr_adapter samgr_source cjson_static ble_lite sle_lite wifiservice native_file udidcomm param_client_lite hota"
elif [[ "$product_out_dir" == *xts* ]]; then
    REQUIRED_LIBS="begetutil bootstrap devattest_sdk devattest_core hal_file_static hal_sys_param hal_sysparam hal_token_static hal_update_static hichainsdk hilog_lite_static hilog_static hiview_lite_static hievent_lite_static huks_3.0_sdk init_log init_utils inithook samgr samgr_adapter samgr_source cjson_static blackbox_lite hidumper_mini ble_lite sle_lite wifiservice broadcast native_file udidcomm param_client_lite hota"
else
    REQUIRED_LIBS="begetutil bootstrap hal_file_static hal_sys_param hal_sysparam hal_update_static hichainsdk hilog_lite_static hilog_static hiview_lite_static hievent_lite_static huks_3.0_sdk init_log init_utils inithook samgr samgr_adapter samgr_source cjson_static blackbox_lite hidumper_mini ble_lite sle_lite wifiservice broadcast native_file udidcomm param_client_lite hota hal_iothardware ws63_demo"
fi
MISSING_LIBS=""
for lib in $REQUIRED_LIBS; do
    if [ ! -f "$OHOS_LIBS_XTS_DIR/lib${lib}.a" ]; then
        MISSING_LIBS="$MISSING_LIBS lib${lib}.a"
    fi
done
if [ -n "$MISSING_LIBS" ]; then
    echo "[ERROR] hm_build.sh: missing OHOS libs in $OHOS_LIBS_XTS_DIR:$MISSING_LIBS"
    echo "[ERROR] GN archiving ran concurrently with the SDK copy step (dependency race)."
    echo "[ERROR] Re-run the build; if it reproduces, check run_sdk_build deps in device/soc/hisilicon/ws63v100/sdk/BUILD.gn."
    exit 1
fi


# build #
echo "build ws63 sdk = $build_ws63_sdk_open"
if [ "$build_ws63_sdk_open" = "true" ]; then
    export build_ws63_sdk_open=true
    echo "export build_ws63_sdk_open=true "
fi

if [[ "$product_out_dir" == *xts* ]]; then
    python3 build.py -c ws63-liteos-xts
else
    python3 build.py -c ws63-liteos-app
fi

if [ "$build_ws63_sdk_open" = "true" ]; then
echo "build ws63 sdk"
target_file="sdk.tar.gz"
cd ../../../../../
rm -rf sdk_temp
mkdir -p sdk_temp

echo "copy drivers to $sdk_temp"
cp -rf drivers applications  base  vendor .gn build.py  commonlibrary  device  ide  kernel   test   third_party arkcompiler  build  build.sh  developtools   domains  foundation  interface  napi_generator  productdefine  sdk_temp

find sdk_temp -name ".git" -type d -exec rm -rf {} \; || true
find sdk_temp/device/soc/hisilicon/ws63v100/src/open_source/mbedtls -type f -name "*.c" -delete
find sdk_temp/device/soc/hisilicon/ws63v100/src/open_source/lwip -type f -name "*.c" -delete
find sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS -type f -name "*.c" -delete
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/arch/riscv/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/compat/cmsis/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/compat/linux/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/drivers/base/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/drivers/interrupt/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/fs/compat/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/fs/vfs/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/base/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/extended/console/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/extended/cpup/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/init/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/libc/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/liteos_libc/arch/riscv32/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/liteos_libc/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/targets/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/libm/CMakeLists.txt

tar --warning=no-file-changed -zcvf $target_file sdk_temp
fi

#
# after build #
if [ ! -d $OUTPUT_DST_DIR ]; then
   mkdir $OUTPUT_DST_DIR
fi
cp $OUTPUT_SRC_DIR/* $OUTPUT_DST_DIR/ -rf
