/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
rawdata OHOS.Media.MediaMonitor.AudioDumpBuffer;
sequenceable OHOS.Media.MediaMonitor.EventBean;
sequenceable MediaMonitorInfo..OHOS.Media.MediaMonitor.MonitorDeviceInfo;
sequenceable MediaMonitorInfo..OHOS.Media.MediaMonitor.MonitorDmDeviceInfo;
interface OHOS.Media.MediaMonitor.IMediaMonitor {
    [oneway] void WriteLogMsg([in] EventBean bean);
    int GetAudioRouteMsg([out] Map<int, MonitorDeviceInfo> preferredDevices);
    int WriteAudioBuffer([in] String fileName, [in] AudioDumpBuffer buffer);
    int SetMediaParameters([in] String dumpType, [in] String dumpEnable);
    int GetPcmDumpStatus([out] int dumpEnable);
    int ErasePreferredDeviceByType([in] int preferredType);
    int GetAudioExcludedDevicesMsg([out] Map<int, List<MonitorDeviceInfo>> excludedDevices);
    int GetCollaborativeDeviceState([out] Map<String, unsigned int> addressToCollaborativeEnabledMap);
    int GetAudioAppSessionMsg([out] Map<int, boolean> avSessionMap);
    int GetAudioAppBackTaskMsg([out] Map<int, boolean> backTaskMap);
    int GetDistributedDeviceInfo([out] List<String> deviceInfos);
    int GetDistributedSceneInfo([out] String sceneInfo);
    int GetDmDeviceInfo([out] List<MonitorDmDeviceInfo> dmDeviceInfos);
    int GetUnifiedFaultCodeRecords([out] List<String> faultRecords);
}
