/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H
#define FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H

#include "appexecfwk_errors.h"

namespace OHOS {
namespace AppExecFwk {
enum class ScanMode : uint8_t {
    SUB_FILE_ALL = 0,
    SUB_FILE_DIR,
    SUB_FILE_FILE,
};

enum class ResultMode : uint8_t {
    ABSOLUTE_PATH = 0,
    RELATIVE_PATH,
};

enum class BundleDirScene : int32_t {
    SET_DIR_APL = 0,
    EXTRACT_HNP_FILES = 1,
    SET_FILE_CON_FORCE = 2,
    EXTRACT_DRIVER_SO_FILES = 3,
    SET_ARK_STARTUP_CACHE_APL = 4,
    PEND_SIGN_AOT = 5,
    EXTRACT_FILES = 6,
    VERIFY_CODE_SIGNATURE = 7,
    CLEAN_BUNDLE_DATA_DIR = 8,

    // CreateBundleDir scenes
    BUNDLE_CODE_DIR = 101,
    MODULE_DIR = 102,
    SO_DIR = 103,
    EXTEND_RESOURCE_DIR = 104,
    EXTEND_PROFILE_DIR = 105,
    PLUGIN_DIR = 106,
    QUICKFIX_PATCH_DIR = 107,
    VERIFY_DIR = 108,
    BASE_SKILL_DIR = 109,

    // Mkdir scenes
    EL1_ARK_PROFILE_DIR = 201,
    ASAN_LOG_DIR = 202,
    EL1_ARK_STARTUP_CACHE_DIR = 203,
    SHADER_CACHE_DIR = 204,  // deprecated: no longer used
    CLOUD_SHADER_DIR = 205,  // deprecated: no longer used
    CLOUD_SHADER_COMMON_DIR = 206,  // deprecated: no longer used
    SERVICE_BMS_GALLERY_DOWNLOAD_DIR = 207,
    SCREEN_LOCK_FILE_BASE_DIR = 208,
    SCREEN_LOCK_FILE_DATA_BASE_DIR = 209,
    SERVICE_BMS_ENTERPRISE_CERT_DIR = 210,
    EL1_SHADER_CACHE_DIR = 211,  // deprecated: no longer used
    EL1_SYSTEM_OPTIMIZE_SHADER_CACHE_DIR = 212,
    EL1_SYSTEM_OPTIMIZE_DIR = 213,
    SERVICE_BMS_DIR = 214,
    SERVICE_BMS_SECURITY_STREAM_INSTALL_DIR = 215,
    SCREEN_LOCK_FILE_DATA_GROUP_DIR = 216,
    BACK_UP_DIR = 217,
    APP_EL2_LOG_DIR = 218,
    SERVICE_HMDFS_CLOUD_DATA_DIR = 219,
    EL2_SHARE_FILES_DIR = 220,
    PGO_DIR = 221,

    // MoveFile scenes
    MOVE_HAP_TO_INSTALL_DIR = 301,
    MOVE_HAP_TO_TEMP_DIR = 302,
    MOVE_DRIVER_FILE = 303,
    MOVE_EXTEND_RESOURCE_FILE = 304,
    MOVE_EXTEND_RESOURCE_FILE_TO_TEMP_DIR = 305,
    MOVE_HSP_TO_INSTALL_DIR = 306,
    MOVE_ABC_FILE = 307,

    // CopyFile scenes
    COPY_PGO_FILE = 401,
    COPY_HAP_TO_INSTALL_PATH = 402,
    COPY_EXTEND_RESOURCE_FILE = 403,
    COPY_EXTEND_PROFILE_FILE = 404,
    COPY_HAP_TO_TEMP_PATH = 405,
    COPY_AP_FILE = 406,
    COPY_SERVICE_HSP = 407,
    COPY_PLUGIN_HSP = 408,
    COPY_HQF_FILE = 409,
    COPY_SHARED_HSP = 410,
    COPY_SKILL_HSP = 411,
    COPY_ABC_FILE = 412,

    // RemoveDir scenes
    REMOVE_BUNDLE_CODE_DIR = 501,
    REMOVE_AOT_ARK_CACHE_DIR = 503,
    REMOVE_BUNDLE_HNP_DIR = 504,
    REMOVE_BMS_BUNDLE_LIB_DIR = 505,
    REMOVE_BMS_BUNDLE_TEMP_DIR = 506,
    REMOVE_SCREEN_LOCK_DATA_DIR = 507,
    REMOVE_AOT_ARK_PROFILE_DIR = 508,
    REMOVE_PRELOAD_APP_DIR = 509,
    REMOVE_MODULE_DIR = 510,

    REMOVE_ASAN_LOG_DIR = 511,
    REMOVE_BUNDLE_LIB_DIR = 512,
    REMOVE_ARK_START_UP_CACHE_DIR = 513,
    REMOVE_LOCAL_SHADER_CACHE_DIR = 514,  // deprecated: no longer used
    REMOVE_SHARE_FILE_DIR = 515,
    REMOVE_CLOUD_SHADER_CACHE_DIR = 516,
    REMOVE_BUNDLE_PLUGIN_DIR = 517,
    REMOVE_GALLERY_DOWNLOAD_DIR = 518,
    REMOVE_ENTERPRISE_CERT_DIR = 519,
    REMOVE_SYSTEM_OPTIMIZE_DIR = 520,

    REMOVE_ARK_AP_FILE = 521,
    REMOVE_LOCAL_ARK_CACHE_DIR = 522,
    REMOVE_LOCAL_ARK_PROFILE_DIR = 523,
    REMOVE_SYSTEM_SERVICE_DIR = 524,
    REMOVE_EXTEND_RESOURCE_FILE = 525,
    REMOVE_QUICK_FIX_FILE = 526,
    REMOVE_QUICK_FIX_DIR = 527,
    REMOVE_SECURITY_QUICK_FIX_DIR = 528,
    REMOVE_SANDBOX_DATA_DIR = 529,
    REMOVE_SKILL_MODULE_DIR = 530,

    REMOVE_SKILL_BUNDLE_DIR = 531,
    REMOVE_VERIFY_FILE = 532,
    REMOVE_NPAPI_PLUGIN_DIR = 533,
    REMOVE_SANDBOX_DIR = 534,

    // ChangeFileStat scenes
    CHANGE_BMS_FILE_STAT = 601,
    // MoveHapToCodeDir scenes
    MOVE_HAP_TO_CODE_DIR = 701,
    // CopyDir scenes
    COPY_PLUGIN_DIR = 801,
    // GetDiskUsageFromPath scenes
    GET_BUNDLE_CACHE_DISK_USAGE = 901,
    // GetBundleCachePath scenes
    GET_BUNDLE_CACHE_PATH = 1001,
    // ScanDir scenes
    SCAN_DIR = 1101,
    // GetFileStat scenes
    GET_BMS_FILE_STAT = 1201,
    GET_USER_DATA_FILE_STAT = 1202,
    GET_DATA_BASE_FILE_STAT = 1203,
    // ClearDir scenes
    CLEAR_ARK_PROFILE_DIR = 1301,
    CLEAR_ARK_CACHE_DIR = 1302,
    // RestoreconPath scenes
    RESTORECON_ARK_WEB_LIB_PATH = 1401,
    // CopyFiles scenes
    COPY_QUICK_FIX_FILES = 1501,
    // MoveFiles scenes
    MOVE_SO_TO_REAL_PATH = 1601,
    // ObtainQuickFixFileDir scenes
    OBTAIN_QUICK_FIX_FILE_DIR = 1701,
    // HashSoFile scenes
    HASH_SO_FILE = 1801,
    // CleanBundleDirs scenes
    CLEAN_SHADER_CACHE_DIR = 1901,
    CLEAN_ARK_STARTUP_CACHE_DIR = 1902,
    CLEAN_EL1_CACHE_DIR = 1903,
};

const std::unordered_map<int32_t, int32_t> CODE_SIGNATURE_ERR_MAP = {
    {1, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_CS_SUCCESS_END},
    {-0x101, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FILE_PATH_INVALID},
    {-0x200, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_PARAM_INVALID},
    {-0x205, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_NO_OWNER_ID},
    {-0x214, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_OPENSSL_BIO},
    {-0x212, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_OPENSSL_PKCS7},
    {-0x301, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FSVREITY_NOT_SUPPORTED},
    {-0x302, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FSVERITY_NOT_ENABLED},
    {-0x303, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_OWNER_ID},
    {-0x305, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_ERR_PROFILE},
    {-0x306, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_ENABLE_TIMEOUT},
    {-0x622, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_EXTENSION_OFFSET},
    {-0x623, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_PAGE_INFO_EXTENSION},
    {-0x624, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_EXTENSION_SIGN_SIZE},

};
}  // namespace AppExecFwk
}  // namespace OHOS
#endif  // FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H
