/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package OHOS.testserver;
import Types;

sequenceable SessionToken..OHOS.testserver.SessionToken;
sequenceable CommonEventData..OHOS.EventFwk.CommonEventData;
interface OHOS.testserver.ITestServerInterface {
    void CreateSession([in] SessionToken sessionToken);
    void SetPasteData([in] String text, [out] int setResult);
    void ChangeWindowMode([in] int windowId, [in] unsigned int mode);
    void TerminateWindow([in] int windowId);
    void MinimizeWindow([in] int windowId);
    void PublishCommonEvent([in] CommonEventData event, [out] boolean re);
    void FrequencyLock();
    void SpDaemonProcess([in] int daemonCommand, [in] String extraInfo);
    void CollectProcessMemory([in] int pid, [out] ProcessMemoryInfo processMemoryInfo);
    void CollectProcessCpu([in] int pid, [in] boolean isNeedUpdate, [out] ProcessCpuInfo processCpuInfo);
    void GetValueFromDataShare([in] String url, [in] String key, [out] String value);
    void SetTime([in] long timeMs, [out] int setTimeResult);
    void SetTimezone([in] String timezoneId, [out] int setTimezoneResult);
    void GetPasteData([out] String pasteText, [out] int getResult);
    void ClearPasteData([out] int clearResult);
    void HideKeyboard([out] int hideResult);
    void GetUserIdByDisplayId([in] int displayId, [out] int userId);
    void GetUserCounts([out] int counts);
    void InstallFont([in] String fontPath, [out] int installResult);
    void UninstallFont([in] String fontName, [out] int uninstallResult);
    void SetViewMode([in] String mode, [out] int setResult);
    void GetViewMode([out] String mode, [out] int getResult);
    void EnableLocationMock([out] int enableResult);
    void DisableLocationMock([out] int disableResult);
    void SetMockedLocations([in] TestServerLocation[] locations, [in] int timeInterval, [out] int setResult);
}
