# Copyright (C) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("//build/ohos_var.gni")
import("//build/config/components/idl_tool/idl.gni")

FUSION_CONN = "//foundation/communication/fusion_connectivity/"

# 使用idl_gen_interface生成模板文件、输入的参数名在deps中会使用
idl_gen_interface("partner_device_agent") {
  # 开发者定义的.idl名，须与gn文件在同一路径下
  sources = [
   "IPartnerDeviceAgent.idl",
  ]
  sources_common = [ "IFusionConnectivityTypes.idl" ]
  sources_callback = []
  part_name = "fusion_connectivity"
  subsystem_name = "communication"
  # 根据idl文件中对自定义对象的使用，编译为so时需要增加自定义对应使用的cpp的编译，默认为空
  sources_cpp = [
    "src/partner_device_address.cpp",
  ]
  # 根据idl文件中对自定义对象的使用，需要引入的头文件目录，默认为空
  sub_include = [
    "include",
    "../services/common/include",
    "../interfaces/inner_api"
  ]
  configs = []
  sequenceable_ext_deps = [ 
    "c_utils:utils",
    "ipc:ipc_single"
  ]

  # 编译so时增加sanitize
  # CFI
  # branch_protector_ret = "pac_ret"  # Enable PAC CFI
  sanitize = {
      cfi = true                            # Enable/disable control flow integrity detection
      boundary_sanitize = true               # Enable boundary san detection
      cfi_cross_dso = true                   # Cross-SO CFI Checks
      integer_overflow = true                # Enable integer overflow detection
      ubsan = true                           # Enable some Ubsan options
      cfi_vcall_icall_only = true            # CFI optimization, limiting the detection scope
      debug = false
  }
  # 开启hitrace，值是hitrace_meter.h文件中定义的uint64_t类型标识,需要填入常量的变量名

  # 开启hilog，Domain ID 使用16进制的整数
  log_domainid = "0xD000100"
  # 开启hilog，字符串类型tag名、一般为子系统名称
  log_tag = "partner_device_agent"
}

config("partner_agent_extension_interface_config") { 
  include_dirs = [ 
    "${target_gen_dir}", 
    "$FUSION_CONN/partner_agent/idl", 
  ] 
} 

idl_gen_interface("partner_agent_extension_interface") { 
  sources = [ "$FUSION_CONN/partner_agent/idl/IPartnerAgentExtension.idl" ] 
  sources_common = [ 
    "$FUSION_CONN/partner_agent/idl/IFusionConnectivityTypes.idl", 
  ] 
  log_domainid = "0xD000100" 
  log_tag = "PartnerAgentExtension" 
  subsystem_name = "communication" 
  part_name = "fusion_connectivity" 
  configs = [ 
    ":partner_agent_extension_interface_config", 
  ] 
  sequenceable_ext_deps = [  
    "c_utils:utils", 
    "ipc:ipc_single" 
  ] 
} 


config("partner_agent_extension_ipc_public_config") { 
  visibility = [ ":*" ] 


  include_dirs = [ "${target_gen_dir}" ] 
} 


ohos_source_set("partner_agent_extension_proxy") {

  branch_protector_ret = "pac_ret"

  sanitize = { 
    integer_overflow = true 
    ubsan = true 
    boundary_sanitize = true 
    cfi = true 
    cfi_cross_dso = true 
    debug = false 
  } 
  public_configs = [ ":partner_agent_extension_ipc_public_config" ] 
  output_values = get_target_outputs(":partner_agent_extension_interface") 
  sources = filter_include(output_values, [ "*_proxy.cpp" ]) 
  defines = [ 
    "LOG_DOMAIN = 0xD000100", 
  ] 
  include_dirs = [ 
    "$FUSION_CONN/partner_agent/idl/include", 
  ] 
  deps = [ 
    ":partner_agent_extension_interface", 
    "$FUSION_CONN/partner_agent/idl:libpartner_device_agent_proxy", 
    "$FUSION_CONN/partner_agent/idl:libpartner_device_agent_stub", 
  ] 
  external_deps = [ 
    "ability_base:configuration", 
    "ability_base:want", 
    "c_utils:utils", 
    "hilog:libhilog", 
    "ipc:ipc_core", 
  ] 
  subsystem_name = "communication" 
  part_name = "fusion_connectivity" 
} 


ohos_source_set("partner_agent_extension_stub") {

  branch_protector_ret = "pac_ret"

  sanitize = { 
    integer_overflow = true 
    ubsan = true 
    boundary_sanitize = true 
    cfi = true 
    cfi_cross_dso = true 
    debug = false 
  } 
  public_configs = [ ":partner_agent_extension_ipc_public_config" ] 
  output_values = get_target_outputs(":partner_agent_extension_interface") 
  sources = filter_include(output_values, [ "*_stub.cpp" ]) 
  include_dirs = [ 
    "$FUSION_CONN/partner_agent/idl/include", 
  ] 
  deps = [ 
    ":partner_agent_extension_interface", 
    "$FUSION_CONN/partner_agent/idl:libpartner_device_agent_proxy", 
    "$FUSION_CONN/partner_agent/idl:libpartner_device_agent_stub", 
  ] 
  external_deps = [ 
    "ability_base:configuration", 
    "ability_base:want", 
    "bundle_framework:appexecfwk_base", 
    "c_utils:utils", 
    "hilog:libhilog", 
    "ipc:ipc_core", 
  ] 
  defines = [ 
    "LOG_DOMAIN = 0xD000100", 
  ] 
  subsystem_name = "communication" 
  part_name = "fusion_connectivity" 
} 


ohos_shared_library("partner_agent_extension_ipc") { 
  sanitize = { 
    integer_overflow = true 
    ubsan = true 
    boundary_sanitize = true 
    cfi = true 
    cfi_cross_dso = true 
    debug = false 
  } 
  branch_protector_ret = "pac_ret" 

  cflags_cc = [
    "-Os",
    "-fno-rtti",
    "-fno-exceptions",
    "-fdata-sections",
    "-ffunction-sections",
    "-fno-unwind-tables",
    "-fno-asynchronous-unwind-tables",
    "-flto",
  ]

  include_dirs = [ 
    "$FUSION_CONN/partner_agent/idl/include", 
  ]


  sources = [] 


  configs = [] 
  public_configs = [ ":partner_agent_extension_ipc_public_config" ]


  deps = [ 
    ":partner_agent_extension_proxy", 
    ":partner_agent_extension_stub", 
    "$FUSION_CONN/partner_agent/idl:libpartner_device_agent_proxy", 
    "$FUSION_CONN/partner_agent/idl:libpartner_device_agent_stub", 
  ] 


  external_deps = [ 
    "ability_base:want", 
    "ability_base:zuri", 
    "bundle_framework:appexecfwk_base", 
    "c_utils:utils", 
    "hilog:libhilog", 
    "ipc:ipc_core", 
  ] 
  defines = [ 
    "LOG_DOMAIN = 0xD000100", 
  ] 
  subsystem_name = "communication" 
  part_name = "fusion_connectivity" 
}