/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import ISysEventCallback;

sequenceable OHOS.HiviewDFX.SysEventRule;
sequenceable OHOS.HiviewDFX.SysEventQueryRule;
sequenceable OHOS.HiviewDFX.QueryArgument;
interface OHOS.HiviewDFX.IQuerySysEventCallback;

interface OHOS.HiviewDFX.ISysEventService {
    void AddListener([in] SysEventRule[] rules, [in] ISysEventCallback cb);
    void RemoveListener([in] ISysEventCallback cb);
    void Query([in] QueryArgument queryArgument, [in] SysEventQueryRule[] rules, [in] IQuerySysEventCallback cb);
    long AddSubscriber([in] SysEventQueryRule[] rules);
    void RemoveSubscriber();
    long Export([in] QueryArgument queryArgument, [in] SysEventQueryRule[] rules);
}
