# id|path|prefix|machine|version
ws63_riscv32_fp|device/soc/hisilicon/ws63v100/sdk/tools/bin/compiler/riscv/cc_riscv32_musl_100/cc_riscv32_musl_fp/bin|riscv32-linux-musl-|riscv32-linux-musl|gcc-7.3.0
ws63_riscv32|device/soc/hisilicon/ws63v100/sdk/tools/bin/compiler/riscv/cc_riscv32_musl_100/cc_riscv32_musl/bin|riscv32-linux-musl-|riscv32-linux-musl|gcc-7.3.0
