/**
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { resStr} from '../../../Utils/resString';


import { testItemFromRouterOrPlaceholder} from '../../../Utils/common'
import ConfigData from '../../../Utils/ConfigData';
import LogUtil from '../../../Utils/LogUtil';
import bluetooth from '@ohos.bluetooth';
import BluetoothModel, { BluetoothDevice} from '../../../MainAbility/model/BluetoothModel';
import BluetoothDeviceController from '../../../MainAbility/controller/BluetoothDeviceController';
import { PageTitle} from '../../../Component/pageTitle';
import { ContentTable} from '../../../Component/contentTable';
import { initSppClientApiData} from '../../../MainAbility/model/testDataModels'
import { TestImageDisplay} from '../../../Component/testImageDisplay';
import { TestData} from '../../../MainAbility/model/testData'

let MODEL = "bluetoothModel:"

/**
 * SPPClient Test Page Of Bluetooth test
 */

@Entry
@Component
struct SppClient {
  @State message: string = "";
  @StorageLink('dataReadMessage') dataReadMessage: string = "";
  @State btConnectionState: number = 0;
  @State profileType: number = 0;
  @State connectionStateInfo: string = "";
  private uuid: string = "00001101-0000-1000-8000-00805f9b34fb";
  private clientNumber: number = - 1;
  @State deviceId: string = "08:FB:EA:1B:3C:63";//08:FB:EA:1B:3C:63
  @State writeClientData: string = '11';
  private TAG_PAGE = ConfigData.TAG + 'Paired_Device ';
  @StorageLink('bluetoothIsOn') btEnable: boolean = false;
  @State currentClick: number = - 1;
  @StorageLink('pairedDeviceInfo') pairingDevice: BluetoothDevice = new BluetoothDevice;
  @StorageLink('btDeviceController') controller: BluetoothDeviceController = new BluetoothDeviceController;
  @State pairPinCode: string = '';
  private testItem: TestData = testItemFromRouterOrPlaceholder();
  pairDialog: CustomDialogController = new CustomDialogController({
    builder: PairDialog({
      deviceName: this.pairingDevice.deviceName,
      pinCode: this.pairPinCode,
      action: (accept: boolean) => {
        this.confirmPairing(accept);
      }
    }),
    alignment: DialogAlignment.Bottom,
    autoCancel: true
  });

  aboutToAppear(){
    this.btEnable = BluetoothModel.isStateOn();
    AppStorage.setOrCreate('bluetoothIsOn', this.btEnable);
    AppStorage.setOrCreate('inputDeviceId', this.deviceId);
    AppStorage.setOrCreate('inputUuid', this.uuid);
    AppStorage.setOrCreate("writeClientData", this.writeClientData);
  }

  build(){
    Row(){
      Column(){
        Column(){
          Stack({alignContent: Alignment.TopStart}){
            TestImageDisplay({testItem: this.testItem})
            PageTitle({testItem: this.testItem})
              .accessibilityLevel('yes')
              .id('pages_subManualApiTest_subSppTest_sppClientTest__pt_0')
          }

          Stack()
            .height(ConfigData.VP_0_5)
            .backgroundColor($r('app.color.black'));
          Row(){
            Text($r('app.string.bluetoothtest_text_mbsbm'))
              .fontSize(ConfigData.VP_17)
              .width(ConfigData.VP_70);
            TextInput({text: this.deviceId, placeholder: $r('app.string.bluetoothtest_str_qsrmdz')})
              .accessibilityLevel('yes')
              .id('pages_subManualApiTest_subSppTest_sppClientTest__ti_0')
              .fontSize(ConfigData.VP_15)
              .onChange((str) => {
                this.deviceId = str;
                AppStorage.setOrCreate('inputDeviceId', str)
              })
              .width(ConfigData.WH_80_100)
              .borderRadius(ConfigData.HEIGHT_1_VP)
          }
          .backgroundColor($r("app.color.moon"))
          .padding(ConfigData.VP_5)
          .justifyContent(FlexAlign.Start)
          .alignItems(VerticalAlign.Center)

          Row(){
            Text($r('app.string.bluetoothtest_text_mbsbu'))
              .fontSize(ConfigData.VP_17)
              .width(ConfigData.VP_70);
            TextInput({text: this.uuid, placeholder: $r('app.string.bluetoothtest_str_qsru')})
              .accessibilityLevel('yes')
              .id('pages_subManualApiTest_subSppTest_sppClientTest__ti_1')
              .fontSize(ConfigData.VP_15)
              .onChange((str) => {
                this.uuid = str;
                AppStorage.setOrCreate('inputUuid', str)
              })
              .width(ConfigData.WH_80_100)
              .borderRadius(ConfigData.HEIGHT_1_VP)
          }
          .backgroundColor($r("app.color.spring"))
          .padding(ConfigData.VP_5)
          .justifyContent(FlexAlign.Start)
          .alignItems(VerticalAlign.Center)

          Row(){
            Text($r('app.string.bluetoothtest_text_xrmbsbsj'))
              .fontSize(ConfigData.VP_17)
              .width(ConfigData.VP_95);
            TextInput({text: this.writeClientData, placeholder: $r('app.string.bluetoothtest_str_qsrxrdsj')})
              .accessibilityLevel('yes')
              .id('pages_subManualApiTest_subSppTest_sppClientTest__ti_2')
              .fontSize(ConfigData.VP_15)
              .onChange((str) => {
                this.writeClientData = str;
                AppStorage.setOrCreate("writeClientData", str);
              })
              .width(ConfigData.WH_80_100)
              .borderRadius(ConfigData.HEIGHT_1_VP)
          }
          .backgroundColor($r("app.color.moon"))
          .padding(ConfigData.VP_5)
          .justifyContent(FlexAlign.Start)
          .alignItems(VerticalAlign.Center)

          Row(){
            Text($r('app.string.bluetoothtest_text_dqdsjw'))
              .fontSize(ConfigData.VP_17)
            Text(this.dataReadMessage)
              .fontSize(ConfigData.VP_15)
              .width(ConfigData.WH_80_100)
              .borderRadius(ConfigData.HEIGHT_1_VP)
          }
          .padding(ConfigData.VP_5)
          .justifyContent(FlexAlign.Start)
          .alignItems(VerticalAlign.Center)

          Column(){
            Text(resStr($r('app.string.label_api_result_space')) + this.message)
              .fontSize(ConfigData.VP_17)
              .padding(ConfigData.VP_10)
              .textAlign(TextAlign.Center)
          }
          .backgroundColor($r("app.color.moon"))
          .visibility(Visibility.Visible);
          Column(){
            Scroll(){
              ContentTable({apiItems: initSppClientApiData()})//子层调用
            }
            .accessibilityLevel('yes')
            .id('pages_subManualApiTest_subSppTest_sppClientTest__sc_0')
            .width(ConfigData.WH_100_100)
            .align(Alignment.TopStart)
            .layoutWeight(1)
            .margin({top: $r('sys.float.ohos_id_card_margin_middle')})
            .height(ConfigData.WH_100_100)
          }
          .height(ConfigData.PCT_75)
        }
      }
      .width(ConfigData.WH_100_100)
    }
    .backgroundColor($r("sys.color.ohos_id_color_sub_background"))
    .height(ConfigData.WH_100_100)
    .alignItems(VerticalAlign.Top)
  }

  sppClientClose(){
    LogUtil.info(MODEL + 'sppCloseClientSocket clientNumber: ' + JSON.stringify(this.clientNumber))
    bluetooth.sppCloseClientSocket(this.clientNumber);
    this.message = resStr($r('app.string.bluetoothtest_str_gbcgc')) + this.clientNumber;
  }

  /**
   * 获取的clientNumber用作客户端后续读/写操作socket的id
   * @param number
   */
  acceptClientSocket(number: number){
    LogUtil.info('spp clientSocket socketID: ' + number);
    // 获取的clientNumber用作服务端后续读/写操作socket的id。
    this.clientNumber = number;
  }

  dataRead(dataBuffer: ArrayBuffer){
    const data = new Uint8Array(dataBuffer);
    LogUtil.info('spp bluetooth read is: ' + data);
    if ( data != null ){
      this.dataReadMessage = resStr($r('app.string.bluetoothtest_str_dqcg_2')) + JSON.stringify(data);
    } else {
      this.dataReadMessage = resStr($r('app.string.bluetoothtest_str_dqsb'));
    }
  }

  /**
   * 字符串转arrayBuffer
   * @param {*} str 需要转换的字符串
   * @returns 返回 arrayBuffer
   */
  strToArrayBuffer(str: string){
    let array = new Uint8Array(str.length);
    for(let i = 0 ; i<str.length ; i++ ){
      array[ i ] = str.charCodeAt(i);
    }
    return array.buffer
  }

  /**
   * Pair device
   * @param device
   */
  pairDevice(deviceId: string){
    this.controller.pair(this.deviceId, (pinCode: string) => {
      LogUtil.info(this.TAG_PAGE + 'pairDevice success callback : pinCode = ' + pinCode);
      // show pair pin dialog
      this.pairPinCode = pinCode
      this.pairingDevice.deviceId = this.deviceId;
      this.pairingDevice.deviceName = this.deviceId;
      this.pairDialog.open();
    }, () => {
      LogUtil.info(this.TAG_PAGE + 'pairDevice error callback');
      this.showPairFailedDialog()
    })
  }

  /**
   * Confirm pairing
   */
  confirmPairing(accept: boolean){
    LogUtil.info(this.TAG_PAGE + 'confirmPairing : pairingDevice + ' + JSON.stringify(this.pairingDevice));
    this.controller.confirmPairing(this.pairingDevice.deviceId, accept);
  }

  /**
   * Show pair failed dialog
   */
  showPairFailedDialog(){
    this.showPairingFailedDialog()
  }

  /**
   * Show connect Failed Dialog
   */
  private showConnectFailedDialog(){
    showDialog(
      $r("app.string.bluetooth_connect_failed"),
      $r("app.string.bluetooth_connect_failed_msg"),
      $r("app.string.bluetooth_know_button")
    );
  }

  /**
   * Show pairing failed title Dialog
   */
  private showPairingFailedDialog(){
    showDialog(
      $r("app.string.pairing_failed_title"),
      $r("app.string.pairing_failed_message"),
      $r("app.string.bluetooth_know_button")
    );
  }
}

/**
 * Pair dialog
 */
@CustomDialog
struct PairDialog {
  private deviceName: string = 'defaultDeviceName';
  private pinCode: string = 'defaultPinCode';
  dialogController: CustomDialogController;
  action!: (accept: boolean) => void;

  aboutToAppear(): void {
    LogUtil.log(ConfigData.TAG + `bluetooth PairDialog aboutToAppear pinCode = ${ this.pinCode }`)
  }

  build(){
    Column(){
      Text($r('app.string.bluetooth_pairing_request'))
        .fontSize(ConfigData.FP_22)
        .height(ConfigData.VP_60)
        .width(ConfigData.WH_100_100)
        .padding({
          left: ConfigData.VP_24,
          top: ConfigData.VP_14,
          bottom: ConfigData.VP_14
        })
      Column(){
        if ( this.pinCode ){
          Text($r('app.string.bluetooth_pairing_intelligent_device_hit', this.deviceName, this.deviceName))
            .fontSize(ConfigData.FP_16)
            .width(ConfigData.WH_100_100)
            .margin({
              top: ConfigData.VP_14,
              bottom: ConfigData.VP_14
            })

          Text(`${ this.pinCode }`)
            .fontSize(ConfigData.FP_32)
            .fontWeight(FontWeight.Bolder)
            .width(ConfigData.WH_100_100)
            .textAlign(TextAlign.Center)
            .margin({
              top: ConfigData.VP_24,
              bottom: ConfigData.VP_24
            })

        } else {
          Text($r('app.string.bluetooth_pairing_media_device_hit'))
            .fontSize(ConfigData.FP_16)
            .width(ConfigData.WH_100_100)
            .margin({
              bottom: ConfigData.VP_2
            })

          Text(this.deviceName)
            .fontSize(ConfigData.FP_16)
            .width(ConfigData.WH_100_100)
            .fontWeight(FontWeight.Bold)
        }

        // button
        Flex({justifyContent: FlexAlign.Center, alignItems: ItemAlign.Center}){

          Button(){
            Text($r('app.string.cancel'))
              .fontSize(ConfigData.FP_16)
              .fontColor(Color.Blue)
          }
          .accessibilityLevel('yes')
          .id('pages_subManualApiTest_subSppTest_sppClientTest__btn_0')
          .backgroundColor($r("app.color.white_bg_color"))
          .width(ConfigData.VP_160)
          .height(ConfigData.VP_40)
          .flexGrow(1)
          .onClick(() => {
            this.dialogController.close();
            this.action(false);
          })

          Divider()
          .height(ConfigData.VP_24)
          .strokeWidth(ConfigData.VP_0_5)
          .vertical(true)
          .color(($r("app.color.color_E3E3E3_grey")))

          Button(){
            Text($r('app.string.bluetooth_pair_button'))
              .fontSize(ConfigData.FP_16)
              .fontColor(Color.Blue)
          }
          .accessibilityLevel('yes')
          .id('pages_subManualApiTest_subSppTest_sppClientTest__btn_1')
          .backgroundColor($r("app.color.white_bg_color"))
          .width(ConfigData.VP_160)
          .height(ConfigData.VP_40)
          .flexGrow(1)
          .onClick(() => {
            this.dialogController.close();
            this.action(true);
          })
        }
        .width(ConfigData.WH_100_100)
        .height(ConfigData.VP_60);
      }
      .width(ConfigData.WH_100_100)
      .padding({
        left: ConfigData.VP_24,
        right: ConfigData.VP_24
      })
    }
    .padding({
      left: ConfigData.VP_24,
      right: ConfigData.VP_24
    })
    .width(ConfigData.WH_100_100);
  }
}
/**
 * Pair mode prompt
 * @param dialogTitle Dialog title
 * @param dialogMessage Dialog message
 * @param buttonValue Dialog buttonValue
 */
function showDialog(dialogTitle: string | Resource, dialogMessage: string | Resource, buttonValue: string | Resource){
  AlertDialog.show({
    title: dialogTitle,
    message: dialogMessage,
    confirm: {
      value: buttonValue,
      action: () => {
        LogUtil.info('Button-clicking callback')
      }
    },
    cancel: () => {
      LogUtil.info('Closed callbacks')
    },
    alignment: DialogAlignment.Bottom
  })
}
