/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { DrawableDescriptor } from '@ohos.arkui.drawableDescriptor';
import { LauncherAbilityResourceInfo } from 'bundleManager.LauncherAbilityResourceInfo';

export class LauncherAbilityResourceInfoInner implements LauncherAbilityResourceInfo {
    readonly bundleName: string = '';
    readonly moduleName: string = '';
    readonly abilityName: string = '';
    readonly icon: string = '';
    readonly label: string = '';
    readonly drawableDescriptor: DrawableDescriptor | null = null;
    readonly appIndex: int;

    constructor() { }
    constructor(bundleName: string,
        moduleName: string,
        abilityName: string,
        icon: string,
        label: string,
        drawableDescriptor: DrawableDescriptor,
        appIndex: int) {
            this.bundleName = bundleName;
            this.moduleName = moduleName;
            this.abilityName = abilityName;
            this.icon = icon;
            this.label = label;
            this.drawableDescriptor = drawableDescriptor;
            this.appIndex = appIndex;
    }
}
