/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef JLOG_ID_H
#define JLOG_ID_H

namespace OHOS {
namespace HiviewDFX {
enum JlogId {
    JLID_JANK_FRAME_SKIP = 0,
    JLID_START_ABILITY = 1,
    JLID_ABILITY_ONFOREGROUND = 2,
    JLID_APP_FOREGROUND = 3,
    JLID_ABILITY_ONACTIVE = 4,
    JLID_LID_WAKEUP_END = 5,
    JLID_LCD_POWER_OFF = 6,
    JLID_AAFWK_TERMINATE_ABILITY = 7,
    JLID_APP_BACKGROUND = 8,
    JLID_ABILITY_ONBACKGROUND = 9,
    JLID_APP_TERMINATE = 10,
    JLID_APP_ATTACH = 11,
    JLID_RS_COMPOSITION_TIMEOUT = 12,
    JLID_LID_WAKEUP_START = 13,
    JLID_SCREENON_EVENT = 14,
    JLID_LCD_POWER_ON = 15,
    JLID_LCD_BACKLIGHT_ON = 16,
    JLID_INPUT_POWER_DOWN = 20,
    JLID_LCD_BACKLIGHT_OFF = 23,
    JLID_POWER_STATE = 25,
    JLID_GRAPHIC_INTERACTION_RESPONSE_LATENCY = 26,
    JLID_GRAPHIC_INTERACTION_COMPLETED_LATENCY = 27,
    JLID_AAFWK_DRAWN_COMPLETED = 28,
    JLID_INIT_STARTUP_TIME = 29,
    JLID_AAFWK_APP_STARTUP_TYPE = 30,
    JLID_AAFWK_PROCESS_START = 31,
    JLID_WINDOWMANAGER_START_WINDOW = 32,
    JLID_GRAPHIC_FIRST_FRAME_DRAWN = 33,
    JLID_ACE_INTERACTION_COMPLETED_LATENCY = 34,
    JLID_ACE_INTERACTION_APP_JANK = 35,
    JLID_GRAPHIC_INTERACTION_RENDER_JANK = 36,
    JLID_AAFWK_CLOSE_ABILITY = 37,
    JLID_AAFWK_PROCESS_EXIT = 38,
    JLID_SCENE_BOARD_APP_CONTAINER_ANIMATION_END = 40,
    JLID_BOARD_SCREENUNLOCK_EVENT = 41,
    JLID_BOARD_CLICK_BUTTON_EVENT = 42,
    JLID_BOARD_START_UNLOCK = 43,
    JLID_BOARD_UNLOCK_TO_GRID_ANIMATION_END = 44,
    JLID_BOARD_UNLOCK_TO_DOCK_ANIMATION_END = 45,
    JLID_SCREEN_RECORDER_STOP = 46,
    JLID_JANK_FRAME_APP = 47,
    JLID_WINDOWMANAGER_FOCUS_WINDOW = 55,
    JLID_APP_ASSOCIATED_START = 56,
    JLID_FOLD_STATE_CHANGE_BEGIN = 57,
    JLID_SCENE_BOARD_APP_SCREEN_ON_ANIMATION = 58,
    JLID_XGATE_WIFI_CONNECT_START = 59,
    JLID_XGATE_WIFI_CONNECT_END = 60,
    JLID_XGATE_SPES_LOGIN_START = 61,
    JLID_XGATE_SPES_LOGIN_END = 62,
    JLID_XGATE_IACCESS_LOGIN_START = 63,
    JLID_XGATE_IACCESS_LOGIN_END = 64,
    JLID_PERF_FACTORY_TEST_START = 65,
    JLID_PERF_FACTORY_TEST_STOP = 66,
    JLID_PERF_FACTORY_TEST_CLEAR = 67,
    JLID_LIMIT_BOOST = 68,
    JLID_LIMIT_FREQUENCY = 69,
    JLID_LTPO_DYNAMICS_FRAME = 71,
    JLID_SHADER_MALFUNCTION = 72,
    JLID_SHADER_STATS = 73,
    JLID_WEBVIEW_PAGE_LOAD = 74,
    JLID_WEBVIEW_DYNAMIC_FRAME_DROP = 75,
    JLID_WEBVIEW_AUDIO_FRAME_DROP = 76,
    JLID_WEBVIEW_VIDEO_FRAME_DROP = 77,
    JLID_GRAPHIC_INTERACTION_HITCH_TIME_RATIO = 78
};
} // HiviewDFX
} // OHOS
#endif
