# Copyright (c) 2025-2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//base/hiviewdfx/hiview/hiview.gni")
import("//build/config/components/ets_frontend/ets2abc_config.gni")
import("//build/ohos.gni")

ohos_shared_library("loglibrary_ani") {
  branch_protector_ret = "pac_ret"

  include_dirs = [
    "./include/",
    "$hiview_interfaces/inner_api/unified_collection",
    "$hiview_interfaces/js/napi/include",
  ]

  sources = [
    "$hiview_interfaces/js/napi/src/hiview_service_agent.cpp",
    "./src/loglibrary_ani.cpp",
    "./src/loglibrary_ani_util.cpp",
  ]

  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }

  deps = [
    "$hiview_adapter/service/client:hiview_service_proxy",
    "$hiview_base:hiviewbase",
  ]

  external_deps = [
    "ability_base:configuration",
    "ability_runtime:app_context",
    "access_token:libtokenid_sdk",
    "bundle_framework:appexecfwk_base",
    "bundle_framework:appexecfwk_core",
    "c_utils:utils",
    "icu:shared_icuuc",
    "hilog:libhilog",
    "ipc:ipc_single",
    "runtime_core:ani",
    "samgr:samgr_proxy",
    "storage_service:storage_manager_acl",
  ]

  subsystem_name = "hiviewdfx"
  part_name = "hiview"
  output_extension = "so"
}

generate_static_abc("loglibrary") {
  base_url = "./ets"
  files = [ "./ets/@ohos.logLibrary.ets" ]
  is_boot_abc = "True"
  device_dst_file = "/system/framework/loglibrary.abc"
}

ohos_prebuilt_etc("loglibrary_etc") {
  source = "$target_out_dir/loglibrary.abc"
  module_install_dir = "framework"
  subsystem_name = "hiviewdfx"
  part_name = "hiview"
  deps = [ ":loglibrary" ]
}
